### ISSUE TITLE
[v4] Allow configuration via config folder in addition to datapacks

### ISSUE THREAD

**Issue by ejektaflex** [ejektaflex/Bountiful#102]
Datapacks are great, but a bit confusing to create and modify for some people. The ability to load from the `serverconfig`/`config` folder last would be great for modpack makers while preserving the ability for other mods to provide custom data as well!

**Comment by koalalord9999** [comment]
Yea, I had no idea how you're supposed to add new rewards and whatnot, so I just went in the Jar and aded a few things to the configs inside the jar ... lol

**Comment by ejektaflex** [comment]
Uhhhh you're definitely supposed to use datapacks, they don't require JAR modification and they last between versions of Bountiful. You can read about them on the wiki, they can be created quite easily just by putting additional config files in the same locations in their own zip file.

Anyways, this is done in the Fabric version and I don't see myself re-implementing it for the Forge version until it gets backported from Fabric, so I'm closing this issue!

**Comment by vizthex123** [comment]
Yes please!

I can't stand datapacks. They never work and are painful to deal with, and I preferred the 1.12.2 config system so much.

Sad it won't get added though </3

**Comment by ejektaflex** [comment]
If I ever port back to the Forge version, this will be done. However, the improvements have been so extensive (and dependent on the things that make Fabric great), that it's currently quite tied to the Fabric ecosystem.

**Comment by vizthex123** [comment]
rip :c

would it be possible to keep the .json system, but just move it to the `config` folder instead?

(since the issue I have at least is just datapack formatting beind stupid af, and so they never load in)

**Comment by ejektaflex** [comment]
Not without some work. People are welcome to write this implementation, as long as it "just works", but I'm not willing to put the work in right now. In Fabric, it already pulls from the datapack folder, then overwrites any similarly named files from the config folder.

You are right that datapacks are more finicky, which is why I tried to solve this problem in Fabric :^) We'll see if the Forge version is ever as fully featured as the Fabric one again.

**Comment by vizthex123** [comment]
ah well.
