### ISSUE TITLE
[Suggestion] Boss Mob bounties using the Champions mod

### ISSUE THREAD

**Issue by Corvus20** [ejektaflex/Bountiful#104]
Boss Mob bounties

Upon taking a boss mob bounty, an elite mob from the Champions mod (https://www.curseforge.com/minecraft/mc-mods/champions) will spawn within a radius of where you got the quest. Bounties with higher ranking elite mobs give bigger rewards, but are obviously more challenging.

Additionally, making it so mobs can be added to (or removed from) the list of quest bosses (such as mobs from other mods) can make "Monster Hunter" style boss fights possible with mods like Mutant Mobs, Ice and Fire, etc.

Making quests that will have the required mob spawn nearby when accepted will make make combat bounties more appealing and more challenging, and make them less bland than the normal "kill 5 skeletons" sort of quests.

This would not only spice up the bounty board a bit, but would also provide powerful tools for modpack makers, I can think of several modpacks that would benefit from boss mob bounties being introduced to this mod. With all of the amazing mob mods coming out now, and being you are planning on a 1.16 port (last time I checked), the time to implement something like this couldn't be better than now. 

I just wanted to tack this on the end, thank you for your continued work on this amazing mod, and I can't wait to see what comes next!

**Comment by ejektaflex** [comment]
Sorry for the delay between the suggestion and my response here - I thought I'd responded already!

This is a pretty neat idea! I probably won't be adding it to base Bountiful, though. All new features are being worked on for Fabric, and Champions (sadly) does not exist for Fabric (yet! TheIllusiveC4 has created some mods for both mod loaders...).

Thank you for your time, I'm glad to hear your enthusiasm for the project - and yeah, that is something I'll have to take note of, as it would be really fun!
