### ISSUE TITLE
no licensure on latest release cant load

### ISSUE THREAD

**Issue by laureng1234** [ejektaflex/Bountiful#106]
-- NO MOD INFO AVAILABLE --
Details:
	Mod File: NO FILE INFO
	Failure message: Missing License Information in file Mod File: /Users/laurengreenspon/Library/Application Support/minecraft/mods/Bountiful-1.15.2-3.1.2.jar
	Mod Version: NO MOD INFO AVAILABLE
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE

**Comment by ejektaflex** [comment]
After a cursory Google search, it sounds like you are trying to load up the mod in a 1.16.x version of Forge. Unfortunately, Bountiful is only made for 1.12/1.14/1.15, and you are trying to use the 1.15 version of the mod there (1.15.2) with Minecraft 1.16. I do plan on updating the mod to 1.16, although I've not had a lot of time as of late.

**Comment by ejektaflex** [comment]
I do appreciate the issue report, now I know that I need to do this for the port! Thank you.
