### ISSUE TITLE
is this a bug , reward given too many items

### ISSUE THREAD

**Issue by deltaforcestronth** [ejektaflex/Bountiful#108]
so about Reward
why it given so much rewards on this ?
can i config the mod like give 5 reward for this type of quest ? if so how

been a great experience with your mod man all my friends love it
i hope i can fix this only problem so my game will be more balance and fun to play

image below
https://imgur.com/a/RznkNxK

btw that cutting log mission i typed
{
"content": "minecraft:log",
"amount": {
"min": 1,
"max": 128
},
"unitWorth": 500,
"weight": 100
},

and there are many reward that i set UnitWorth : 500

**Comment by ejektaflex** [comment]
Your oak wood log is worth a lot per log (81x500 = worth of 40500), so it has to come up with 40500 worth of rewards to give you in return. It does give an enormous amount - you are correct. I explained the reasoning why in #107 . You can mitigate this by changing the unitWorth to something better, like "30" for logs. They shouldn't be worth a lot per log.

**Comment by deltaforcestronth** [comment]
> 
> 
> Your oak wood log is worth a lot per log (81x500 = worth of 40500), so it has to come up with 40500 worth of rewards to give you in return. It does give an enormous amount - you are correct. I explained the reasoning why in #107 . You can mitigate this by changing the unitWorth to something better, like "30" for logs. They shouldn't be worth a lot per log.

thank you alot now every easy tasks i set it below 30 and make it 2 to 3 tasks per 1 quest

thx for made this mod

**Comment by deltaforcestronth** [comment]
one thing i forgot to ask

i cant reward an egg (spawn_egg) such as cow , chicken is this normal ? or i am doing something wrong

**Comment by ejektaflex** [comment]
Spawn eggs have their own NBT data that you have to include in the NBT field. Check the Wiki link from the CurseForge page to figure out how to include it :^)

**Comment by deltaforcestronth** [comment]
thx for fast responded man ! haha

**Comment by deltaforcestronth** [comment]
sorry to bother you again , how can i find each egg's nbt data ?

**Comment by deltaforcestronth** [comment]
if i straight up put 	
				{
    "content": "minecraft:potion",
    "unitWorth": 1500,
    "weight": 20,
    "amount": {
      "min": 1,
      "max": 3
    }
	},

will the mod generate random potion types as a reward ?

**Comment by ejektaflex** [comment]
Uh, no - you need to specify the NBT data for that reward, like it shows [here](https://github.com/ejektaflex/Bountiful/wiki/1.12-Customizing-Bounty-Objectives). To get NBT data, you'll have to use a different mod similar to CraftTweaker. In later versions I added my own command to get NBT data, but there's no way to do it with Bountiful in 1.12.
