### ISSUE TITLE
please give me an example of how to add nbt data of an Tinker Items

### ISSUE THREAD

**Issue by deltaforcestronth** [ejektaflex/Bountiful#109]
right now i am using CT to copy NBT data from an items
this is how i do
i selected one of an item in my hand /ct hand

this is what i got
<conarm:boots>.withTag({StatsOriginal: {Toughness: 0.0 as float, FreeModifiers: 3, Durability: 14745, Defense: 50.0 as float}, Stats: {Toughness: 0.0 as float, FreeModifiers: 3, Durability: 14745, Defense: 60.0 as float}, TinkerData: {Materials: ["dragonsteel_ice", "dragonsteel_ice", "dragonsteel_ice"], Modifiers: ["leveling_armor"]}, Modifiers: [{identifier: "indomitable_armor", color: -4463363, level: 1}, {identifier: "prideful_armor", color: -4463363, level: 1}, {identifier: "calcic_armor", color: -4463363, level: 1}, {identifier: "leveling_armor", color: 16777215, level: 1}], Traits: ["indomitable_armor", "prideful_armor", "calcic_armor", "leveling_armor"]})

and what i do with this is

[
{
"content": "conarm:boots",
  "amount": {
    "min": 1,
    "max": 1
  },
  "unitWorth": 300,
  "weight": 100,
  "nbt_data": "<conarm:boots>.withTag({StatsOriginal: {Toughness: 0.0 as float, FreeModifiers: 3, Durability: 14745, Defense: 50.0 as float}, Stats: {Toughness: 0.0 as float, FreeModifiers: 3, Durability: 14745, Defense: 60.0 as float}, TinkerData: {Materials: ["dragonsteel_ice", "dragonsteel_ice", "dragonsteel_ice"], Modifiers: ["leveling_armor"]}, Modifiers: [{identifier: "indomitable_armor", color: -4463363, level: 1}, {identifier: "prideful_armor", color: -4463363, level: 1}, {identifier: "calcic_armor", color: -4463363, level: 1}, {identifier: "leveling_armor", color: 16777215, level: 1}], Traits: ["indomitable_armor", "prideful_armor", "calcic_armor", "leveling_armor"]})"
}
]

when i hit /bo reload it said Unterminated object at line 10 column 265 which is the NBT part
i wonder what i am doing wrong so please inform me 

and thank you for your time again i am sorry i have to make a bug report which is not at all but i have nowhere to ask if you have discord or something that people make custom config please also let me know thank you

**Comment by ejektaflex** [comment]
Remove `conarm:boots.withTag(` from the start and `)` from the end. Then remove `as _` from the data. Finally, replace all instance of `"` with `\"`. 
You can run it through a website like [jsonlint](https://jsonlint.com/) to more easily see what's wrong.
The result should be like so:
```
{
	StatsOriginal: {
		Toughness: 0.0,
		FreeModifiers: 3,
		Durability: 14745,
		Defense: 50.0
	},
	Stats: {
		Toughness: 0.0,
		FreeModifiers: 3,
		Durability: 14745,
		Defense: 60.0
	},
	TinkerData: {
		Materials: [\"dragonsteel_ice\", \"dragonsteel_ice\", \"dragonsteel_ice\"],
		Modifiers: [\"leveling_armor\"]
	},
	Modifiers: [{
		identifier: \"indomitable_armor\",
		color: -4463363,
		level: 1
	}, {
		identifier: \"prideful_armor\",
		color: -4463363,
		level: 1
	}, {
		identifier: \"calcic_armor\",
		color: -4463363,
		level: 1
	}, {
		identifier: \"leveling_armor\",
		color: 16777215,
		level: 1
	}],
	Traits: [\"indomitable_armor\", \"prideful_armor\", \"calcic_armor\", \"leveling_armor\"]
}
```
put that ^ inside of `"nbt_data": "put_the_above_text_here"

This is honestly not very easy because you are using the version made for 1.12, I made this much easier to do in v1.14+. I can't offer you much more help than that.

**Comment by deltaforcestronth** [comment]
oh my god it works now thank you very much man do you have any discord ? or somekind of place where people sharing custom reward , bounty file

**Comment by ejektaflex** [comment]
I'm glad you got it working! I've not got a Discord, mostly because I wouldn't be able to reliably moderate it with a full time job as well. I appreciate your enthusiasm, though, and I'm glad I could help :^)

**Comment by deltaforcestronth** [comment]
enthusiasm haha i opened my server just to play with 3 of my best friends and also my gf 
right now i am stick with 1.12 because of millenaire mod 
i want them to have the best experience in minecraft without your mod and less of their time to play due to work it will be incredible hard and time consuming and nobody want cheats enable to ruin all the fun

i also playing with lots of tinkers stuff , ice and fire , atum ,etc a lot 
now i got your mod and its amazing , little tired that i have to make an effort but its worth it at first i made all weapons included in reward but BANG when i first got my sword during that quest it just original sword not tinker one so no one can upgrade it

thats why i am here
now its time for me put all moded tinker item armor and sword into reward tables haha.

**Comment by ejektaflex** [comment]
That's fair :^) I'm glad you're liking Bountiful, even in it's more limited state for that version. It's helped me a lot, as with a job it makes the tedium of playing Minecraft a little bit more rewarding given how little I've been playing lately.
