### ISSUE TITLE
[Suggestion] Various Server Enhancements

### ISSUE THREAD

**Issue by abboip** [ejektaflex/Bountiful#11]
These are mostly an echo of NorktheOrc's suggestions from Curseforge, for what it's worth. I didn't want to overwhelm this project's github with all of them individually.

Having some server enhancements could really provide server operators/pack makers (such as myself; this mod is an absolute blast to play on a server so thank you for making it!) with some additional options, namely:

- Recipe Disabling:
At the moment on the server we have one bounty board at a central location. Believe it or not we actually don't use Minetweaker in this pack, and adding it for one mod is a bit much probably. Just having the option to disable it via config would be excellent if it's easy enough to implement for odd cases such as myself. 

- Global Bounty Board Pool/Echo Boards
I really like the idea of everyone having the same set of bounties to choose from -- it encourages players to check the board more when they're on a server. Either they'll race to check for good bounties, or mention one to a friend. Perhaps being able to create a 'copy' or an 'echo' of a bounty board that accesses the same inventory like an Enderchest might be a way around having just one. 

- Bounties Completed Scoreboard Objective
Just something for fun; a count of how many bounties someone has fulfilled. Could make for a fun game to see who can complete the most bounties in a week, or just overall.

I realize that these suggestions are definitely not as far-reaching as the others posted thus far, and that you have plenty of ideas for the mod already. Nevertheless I want to say again that my server members and myself are having a ton of fun playing this mod, so thank you for taking the time to make it and field my suggestions!

**Comment by ejektaflex** [comment]
Thank you, @abboip !

* I'm going to add a config option for disabling recipes. 
* Global bounty boards are something that I might work towards in the future, but there are plenty of other things that need to be added first.
* Scoreboard stats sound awesome, that's going on the list. Maybe even stats per bounty tier as well :^).

**Comment by ejektaflex** [comment]
@abboip it's going to have a beta phase but global bounties seem to be done ;)

**Comment by abboip** [comment]
Hey that's awesome! Looking forward to it! 👌

**Comment by ejektaflex** [comment]
Recipe disabling and global bounties are done as of v2.0 in f991b93 and the scoreboard objective idea is added to the ideas board.
