### ISSUE TITLE
Bounties generating with Air objective/reward when Quark is installed in 1.16

### ISSUE THREAD

**Issue by JonathanMcG** [ejektaflex/Bountiful#110]
## Bug Report

**Observed Behaviour**

What happened: Bounties are generating air as an objective or reward when Quark is installed.  This is due to the iron chain item having been removed in Quark for 1.16

_Example bounty image:_
![bounty](https://user-images.githubusercontent.com/21128648/106194943-1a956b80-6175-11eb-8b11-95f48fcdec7c.png)
_Example bounty data:_
{
  "type": "item",
  "content": "bountiful:bounty",
  "nbt": {
    "boardStamp": "82803L",
    "bountyStamp": "111043L",
    "objectives": {
      "0": {
        "amount": 7,
        "type": "item",
        "unitWorth": 900,
        "content": "quark:iron_chain"
      }
    },
    "bountyTime": "45000L",
    "rewards": {
      "0": {
        "amount": 6,
        "type": "item",
        "unitWorth": 1000,
        "content": "minecraft:lapis_lazuli"
      }
    },
    "rarity": 0
  },
  "amountRange": {
    "min": 1,
    "max": 1
  },
  "unitWorth": 1000,
  "weight": 1000
}

**Expected Behaviour**

What should have happened:  Bounties should not be attempting to add an item that has been removed from the mod.

**Minimal setup needed to reproduce**

- Forge version: 35.1.36
- Bountiful version: 1.16.4-3.3.0
- Other mods: Quark r2.4-299

**Steps to reproduce**

How to recreate this:  
 1. Install both Bountiful and Quark.
 2. Wait for a bounty to generate with the invalid item.

**Comment by JonathanMcG** [comment]
I initially thought that the error was because I had disabled the iron chain item in Quark's configuration. However, upon a bit more investigation, the whole item has been removed from the mod due to Minecraft adding an iron chain item itself.  I have corrected my bug report as such.

**Comment by ejektaflex** [comment]
Gotcha, I'll change it so that vanilla bounties include the vanilla iron chain instead. Thank you!

**Comment by ejektaflex** [comment]
Fixed in Bountiful 3.3.1 with commit 81dff72!
