### ISSUE TITLE
[Suggestion] Remove STDOUT for claiming bounties

### ISSUE THREAD

**Issue by TheCoolestPaul** [ejektaflex/Bountiful#111]
## Feature Request

**Feature description**
Remove the STDOUT from players right-clicking a bounty on the board. I assume this is a debug print left in the code.

**How it improves the player experience**
A cleaner console always makes a server owner happy.

![Screenshot 2021-01-30 194241](https://user-images.githubusercontent.com/45607581/106372230-57a75c80-6333-11eb-9105-6ac1c8fc8c25.png)

**Comment by ejektaflex** [comment]
Oh, yep. That's definitely something I forgot to do, thank you 👍

**Comment by ejektaflex** [comment]
Fixed in Bountiful 3.3.1 with commit 81dff72!
