### ISSUE TITLE
[Suggestion] Repurposed Structures Integration

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [ejektaflex/Bountiful#113]
## Feature Request

**Feature description**

Repurposed Structures adds a few new biome variants of villages to the overworld (e.g Jungle villages, swamp villages, mountain villages etc.). These new types of villages do not spawn with bounty boards when bountiful is active. It would be great if these villages could generate with bounty boards just like vanilla villages do.

**How it improves the player experience**

This would make these new villages more consistent with vanilla ones when playing with both Bountiful and Repurposed Structures, Allowing players to find and take bounties no matter if they come across a modded or vanilla type of village when playing with both of these mods.

The mod's page can be found here: https://www.curseforge.com/minecraft/mc-mods/repurposed-structures

(I'm not sure if this is something that needs to be done on their end, so if it is just let me know and I'd be happy to make an issue on their github instead.)

**Comment by ejektaflex** [comment]
This is something that could be done on both ends, but as it stands the code I am using applies more to Villages and Jigsaw Pieces than it does to structures. Thus, it would probably be easier for them to check if my mod is loaded and then add my NBT file as a structure of theirs, I think?

**Comment by The-Bernician-Lamb** [comment]
Ok, I'll open an issue on their github and see what they say about it. I'll link it back to this issue once I've submitted it.

Update: Here's the issue on their github: https://github.com/TelepathicGrunt/RepurposedStructures/issues/48

**Comment by TelepathicGrunt** [comment]
@ejektaflex my villages are done through JSON. I think it might be cleaner or better if Bountiful checks if RS is on, if so, go into the jigsaw pool registry and grab all my village's house pools. And then add the bounty board there. Or do you hook onto a different place to spawn exactly 1 bounty board per village?

Here's the path for all my villages which might help. 
https://github.com/TelepathicGrunt/RepurposedStructures/tree/master/src/main/resources/data/repurposed_structures/worldgen/template_pool/village

lmk if you need help with anything and I'll try my best to assist

**Comment by ejektaflex** [comment]
I hook into the Jigsaw Registry and add my gazebo to the given village pools as a house, as you can see [here](https://github.com/ejektaflex/Bountiful/blob/206997ee17587f3e109d15deff494b69857ec5b6/src/main/kotlin/ejektaflex/bountiful/SetupLifecycle.kt#L52). 

If you're doing all of this with Jigsaws, then that seems super easy for me to do. I don't think there's an easy way of just adding one board to each village, so I use a weighted chance. Usually with the weight I provide they appear 0-2 times in a village.

Can I keep the current jigsaw piece that connects to roads? It just connects to a village road right now with the current structure. If another connector path is needed, let me know.

I'll try to get this into my next release 😬

**Comment by TelepathicGrunt** [comment]
Can you show the jigsaw block that your piece is using? My village are using vanilla target_name for the road pieces but I can go ahead and double check

**Comment by ejektaflex** [comment]
![image](https://user-images.githubusercontent.com/23628421/106402166-e678af80-63ed-11eb-8afd-0c5122e3b1fc.png)

**Comment by TelepathicGrunt** [comment]
Yep that should work with my street's jigsaws

**Comment by TelepathicGrunt** [comment]
Just want to pop-in, any luck with getting the bounty boards in my villages? If you are having issues, let me know and I can try and fork your current progress and see if I can PR getting it to work

**Comment by ejektaflex** [comment]
Yeaaahhhh, I should really take some time and update my existing mods, haha. I'll see what I can do with a couple of hours this weekend, if possible.

**Comment by ejektaflex** [comment]
Added in Bountiful 3.3.1 with commit 81dff72!

**Comment by The-Bernician-Lamb** [comment]
Nice! Thanks a lot!
