### ISSUE TITLE
[1.16.5] Bountiful java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by Cixon** [ejektaflex/Bountiful#114]
## Bug Report

**Observed Behaviour**

What happened: Client crashed upon start up.

Crash log: 
[latest.log](https://github.com/ejektaflex/Bountiful/files/5900698/latest.log) **Line 40.**
[debug.log](https://github.com/ejektaflex/Bountiful/files/5900699/debug.log)
[crash-2021-01-31_15.28.35-fml.txt](https://github.com/ejektaflex/Bountiful/files/5900700/crash-2021-01-31_15.28.35-fml.txt)

**Expected Behaviour**

What should have happened: Mod to be compatible with modpack.

**Minimal setup needed to reproduce**

- Forge version: 36.0.7
- Bountiful version: v3.3.0 _(latest)_
- Other mods: Too many to list but I will list the new ones I added that could've caused the crash.
([TRansliterationlib](https://www.curseforge.com/minecraft/mc-mods/transliterationlib), [NotEnoughAnimations](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations/files/3187616))

**Comment by Fiopon** [comment]
It's [TRansliterationlib](https://www.curseforge.com/minecraft/mc-mods/transliterationlib) that causes the load to fail.

**Comment by Cixon** [comment]
> 
> 
> It's [TRansliterationlib](https://www.curseforge.com/minecraft/mc-mods/transliterationlib) that causes the load to fail.

Figured. Unfortunate because the new animation mod that uses it as a dependency is pretty neat considering it's client sided.
Wonder if there's a fix around it...

**Comment by ejektaflex** [comment]
Yes - seems like that. I wish I could help more!
