### ISSUE TITLE
[Suggestion] Project MMO compatibility

### ISSUE THREAD

**Issue by Neko2n** [ejektaflex/Bountiful#118]
## Project MMO Mod Compatibility

**PMMO experience should be rewarded for completing bounties.**

What you want (A clear and concise description of what you want to improve):
Customizable PMMO experience rewards for completing bountiful bounties

**How it improves the player experience**
Allows specific "quests" to be done for Project MMO experience, which would drastically improve the level grinding experience and would add another reason to look for and complete bounties in mod packs that use PMMO.

How this would make Bountiful better:
More mod compatibility = a more versatile, globally-enjoyable mod that can fit into more modpacks. Also, as mentioned above, it would add another motive to do bounties.

**Comment by ejektaflex** [comment]
This is indeed a pretty cool idea! I intend to work more with Fabric than Forge right now, so if I proceed with these efforts it will most likely be to instead integrate with Age of Exile than it will be for PMMO. Thank you!

**Comment by FrannDzs** [comment]
> This is indeed a pretty cool idea! I intend to work more with Fabric than Forge right now, so if I proceed with these efforts it will most likely be to instead integrate with Age of Exile than it will be for PMMO. Thank you!

Hi! Fabric is fabulous but please don't abandon Forge, it is the home of many favorite mods! At least until Patchwork is completed. Greetings!

**Comment by ejektaflex** [comment]
@FrannDzs I agree with your sentiment. I'm looking into Architectury as a way of continuing to write the Fabric mod while also supporting Forge users. At the very least - I plan on maintaining this version for Forge on 1.16 and possibly 1.17 if it's simple enough to port.

For Fabric, expect:
* The ability to create new bounty objectives and rewards with player commands
* The ability to load bounties from the config directory in addition to the existing datapack system
* A reputation system: As your submit more bounties, they become more worthwhile
* A better rarity system: Rarity reworked, some rewards will be more rare than others.
* Eventually: An API for modders to add their own objective and reward types

For Forge, expect the current version to stay maintained with bug fixes. Eventually, we can hope for there to be a way of bridging the gap back from Fabric back over to Forge, whether it be Architectury or Patchwork or something else.

Thanks for your appreciation ✨
