### ISSUE TITLE
1.16.5 | Bizzare client crash when streaming game on discord...

### ISSUE THREAD

**Issue by Cixon** [ejektaflex/Bountiful#120]
## Bug Report

**Observed Behavior**
What happened: I was streaming my minecraft game to someone on discord in creative mode and my client died.

**### Logs:** 
[latest.log](https://github.com/ejektaflex/Bountiful/files/6027157/latest.log)    | Line 68852
[debug.log](https://github.com/ejektaflex/Bountiful/files/6027162/debug.log) | Line 78354
[crash-2021-02-23_00.51.18-client.txt](https://github.com/ejektaflex/Bountiful/files/6027169/crash-2021-02-23_00.51.18-client.txt)

**Minimal setup needed to reproduce**

- Forge version: 1.16.5 | v36.0.42
- Bountiful version: v3.3.0
- Other mods: 80+, personal modpack :P
_(Using KotlinAPI-v1.9.0)_

**Steps to reproduce**
Stream it on discord and search for the decree in creative search gui? Not sure.

**Comment by ejektaflex** [comment]
Ah - fascinating! I believe I know what's wrong with this - thank you for the report.

**Comment by Cixon** [comment]
thank you for speedy reply!

**Comment by Cixon** [comment]
Is this issue still being investigated?

**Comment by ejektaflex** [comment]
Yes - I know what's wrong with it, I've just been busy with the Fabric version of Bountiful, so I haven't had time to release a fix. For a temporary fix, just don't put any Decrees from the Creative GUI in your inventory. "Blank" decrees with no decree data will crash the game, it seems.

**Comment by Cixon** [comment]
Understandable, was just making sure the bug isn't my fault or anything.
I do have my own personal modpack.

**Comment by Cixon** [comment]
Tried to load a resourcepack and it said the decree was the issue, figured I'd plug it since it's related.
[crash-2021-03-04_16.18.47-client.txt](https://github.com/ejektaflex/Bountiful/files/6086936/crash-2021-03-04_16.18.47-client.txt)

**Comment by ejektaflex** [comment]
Interesting - yeah. Whenever it tries to render the item, it crashes because as it stands, it requires the item to have NBT data (but items are rendered w/o NBT as far as I'm aware). Decrees that are generated in the world or crafted have associated NBT. I'll have to remove them from the itemgroup.

**Comment by ejektaflex** [comment]
Should be fixed in Bountiful 3.3.1 with commit 81dff72, thank you!
