### ISSUE TITLE
1.14.4 Incompatability with Doctor Who Regeneraiton+JEI

### ISSUE THREAD

**Issue by NiaKitten** [ejektaflex/Bountiful#127]
## Bug Report

**Observed Behaviour**

What happened: JEI disappears with Bountiful + Doctor Who's Regen mod

Crash log: no crash

**Expected Behaviour**

What should have happened: JEI didn't disappear

**Minimal setup needed to reproduce**

- Forge version: 28.2.23
- Bountiful version: 3.1.2
- Other mods:
- JEI
- JER (Just Enough Resources)
- JEI Integration
- Doctor Who's Regeneration
- Bountiful

**Steps to reproduce**

How to recreate this:

Just have the above listed mods installed

NOTE: I'm not sure who's mod is causing what, though it does seem to appear when both Regen and Bountiful are together along with JEI so I'm submitting the bug to multiple parties, in case either one can fix it. Just wanted to let you know though. ^.^

**Comment by ejektaflex** [comment]
Could you please provide a log? I'm going to guess this this isn't Bountiful - the only GUI work it does is with the bounty board, whereas JEI does a lot more with GUIs and the Doctor Who one may (unsure).

**Comment by NiaKitten** [comment]
Yep, had to look up how since I didn't get crash log. :D sorry about that.

https://paste.ubuntu.com/p/r5xp2pFjXB/

**Comment by ejektaflex** [comment]
Unfortunately, I am no longer supporting the 1.16.4 version and will not be fixing it. Feel free to reopen this case if it still happens in 1.19.4+!
