### ISSUE TITLE
Missing reward: "charm:variable_redstone_lamp"

### ISSUE THREAD

**Issue by Toadby** [ejektaflex/Bountiful#128]
## Bug Report

**Observed Behaviour**

What happened:
Missing item from Charm results in "Air" as reward.
`An entry has failed validation and will not be loaded. Reason: Stack 'charm:variable_redstone_lamp' does not exist!. Skipping entry..`

**Expected Behaviour**

What should have happened:
Variable redstone lamp should probably be removed as a reward as it seems to have been removed from Charm :)

**Minimal setup needed to reproduce**

- Forge version: 36.1.1
- Bountiful version: 3.3.1
- Other mods: Charm 2.3.2

**Steps to reproduce**

How to recreate this:
Play with Charm and Bountiful on 1.16

**Comment by ejektaflex** [comment]
This is a very old bug referencing a very old version of both mods. I don't see the likelihood of thing having major repercussions if it is marked as wont-fix, and I also don't foresee it hampering the gameplay experience of many more people. It doesn't seem worth going back to the version that is two years old for this, so I'm marking it closed!
