### ISSUE TITLE
Compass bounty

### ISSUE THREAD

**Issue by AedemanZ** [ejektaflex/Bountiful#134]
Dear Ejektaflex,

Thanks for making the mod! I have added it to my personal modpack and I'm having a great time with it. 

I believe I encountered a bug today. I got a bounty to collect 24 compasses for a decree (very expensive but I really want the decree). I crafted the compasses but the bounty does not register them. I will say that Bountiful is not the only mod that I am using, so if you believe it to be a bug related to interaction with other mods, please let me know.

Thanks and hope this helps!

**Comment by ejektaflex** [comment]
Are you holding all 24 compasses in your inventory? (This sounds like 1.12, where bounties were a bit less balanced). :^)

**Comment by AedemanZ** [comment]
> Are you holding all 24 compasses in your inventory? (This sounds like 1.12, where bounties were a bit less balanced). :^)

I am, but I also tried dropping all of them and only picking one up to see if the counter rose, but it didn't. From what I understand, I have the latest version available on forge (for 1.16.5)

**Comment by ejektaflex** [comment]
Oh - this might be my fault. Compasses may have NBT data, and it's checking to see if the NBT data is the same. My bad :^)

**Comment by AedemanZ** [comment]
> Oh - this might be my fault. Compasses may have NBT data, and it's checking to see if the NBT data is the same. My bad :^)

Thanks for the quick replies!

**Comment by ejektaflex** [comment]
This should be fixed in v6.0.0 for 1.19.4+.
