### ISSUE TITLE
[1.16 Suggestion] Bring back the 1.12-style configs for objectives & rewards

### ISSUE THREAD

**Issue by vizthex123** [ejektaflex/Bountiful#135]
## Feature Request

This is really a 1.14+ suggestion, but I specified 1.16 since that's what I use. 

Being able to configure the quest objectives and rewards is what caused me to install this for 1.12.2, but I noticed that it's not int the 1.16 versions.

Could that be added back?

**How it improves the player experience**

By letting modpack creators (or individuals) fine-tune the mod for the 1.16 versions like you could in 1.12.2.

**Comment by ejektaflex** [comment]
You can still do the same with Datapacks. It's just about as easy, but requires a tiny bit of setup. I'm planning on using both systems in tandem for the Fabric version of Bountiful.

But to answer your question, this is already possible in 1.14+. You can read about it [here](https://github.com/ejektaflex/Bountiful/wiki/1.14+%20Data-Packs). :^)

**Comment by vizthex123** [comment]
Is there a way to make datapacks auto-install on newly created worlds?

If not, it's kind of useless for me...

**Comment by ejektaflex** [comment]
Yes - see OpenLoader or other related mods. It allows you to use a folder as a global datapack for all worlds!

**Comment by vizthex123** [comment]
Alright, thanks again/
