### ISSUE TITLE
generic.entity.kills

### ISSUE THREAD

**Issue by Pet-Slime** [ejektaflex/Bountiful#136]
## Bug Report

entity.generic.kills as a bounty reward

What happened: got this as a quest a few times. no other mods installed.

Crash log: No crash, just uncomeatable quest

- Forge version: latest
- Bountiful version: latest
- Other mods: just this mod

How to recreate this: it takes a while, but will eventually show up

**Comment by Duappy** [comment]
I have this same issue as a bounty that appears occasionally.

**Comment by ejektaflex** [comment]
If you could hold the affected bounty in your hand and type `/bo hand`, then send your clipboard contents (should be some JSON data) here, that would be great.

**Comment by Pet-Slime** [comment]
It's the hunting Objectives, it has "Minecraft:zombie_pigman" as an objective. Zombie pigmen are no longer the code name. Should be "minecraft:zombie_piglin"

**Comment by GatoLeyo** [comment]
I'm having the same issue but im using other mods, here's what I get with the /bo hand command:
{
  "type": "item",
  "content": "bountiful:bounty",
  "nbt": {
    "boardStamp": "826203L",
    "bountyStamp": "830063L",
    "objectives": {
      "0": {
        "killedAmount": 0,
        "amount": 4,
        "type": "entity",
        "unitWorth": 400,
        "content": "minecraft:zombie_pigman"
      }
    },
    "bountyTime": "21375L",
    "rewards": {
      "0": {
        "nbt": {
          "StoredEnchantments": [
            {
              "lvl": 1,
              "id": "minecraft:knockback"
            }
          ]
        },
        "amount": 1,
        "name": "Enchanted Book (Knockback I)",
        "type": "item",
        "unitWorth": 2000,
        "content": "minecraft:enchanted_book"
      }
    },
    "rarity": 1
  },
  "amountRange": {
    "min": 1,
    "max": 1
  },
  "unitWorth": 1000,
  "weight": 1000
}

**Comment by GatoLeyo** [comment]
Here is another example
{
  "type": "item",
  "content": "bountiful:bounty",
  "nbt": {
    "bountyStamp": "840983L",
    "objectives": {
      "0": {
        "killedAmount": 0,
        "amount": 7,
        "type": "entity",
        "unitWorth": 225,
        "content": "minecraft:spider"
      },
      "1": {
        "killedAmount": 0,
        "amount": 2,
        "type": "entity",
        "unitWorth": 400,
        "content": "minecraft:zombie_pigman"
      }
    },
    "boardStamp": "837003L",
    "bountyTime": "52500L",
    "rewards": {
      "0": {
        "amount": 1,
        "type": "item",
        "unitWorth": 2000,
        "content": "minecraft:leather_horse_armor"
      }
    },
    "rarity": 0
  },
  "amountRange": {
    "min": 1,
    "max": 1
  },
  "unitWorth": 1000,
  "weight": 1000
}

**Comment by ejektaflex** [comment]
Seems to be because "minecraft:zombie_pigman" no longer exists. I'll have to edit it to "minecraft:zombie_piglin". Thanks!

**Comment by AngleWyrm10** [comment]
Bountiful-1.16.4-3.3.1
![genericName](https://user-images.githubusercontent.com/55937426/137199703-fab5624a-b5c8-4905-b76e-9560d5ff4256.png)

**Comment by ejektaflex** [comment]
Thanks for the image!

**Comment by ejektaflex** [comment]
This should be fixed with v6.0.0 for Minecraft 1.19.4. Due to time constraints, this fix will not be backported.
