### ISSUE TITLE
not compatible with ice and fire at all [Suggestion]

### ISSUE THREAD

**Issue by yoytastic** [ejektaflex/Bountiful#138]
## Feature Request
bounties table generation compatible with ice and fire
**Feature description**
bouties table in villages isn't generating with ice and fire, as we all know ice and fire is a really popular mod and make it fully compatible would be awesome
What you want (A clear and concise description of what you want to improve):
fix bounty table generation with ice and fire
**How it improves the player experience**
lots of players uses ice and fire mod, make it fully compatible could emprove the experience
How this would make Bountiful better:
player would include in their mod packs with ice and fire

**Comment by ejektaflex** [comment]
It sounds like you want a bug fixed instead of a feature request. As far as I know, nothing about Ice & Fire should stop bounty boards from generating. 
Please provide the following so that I can look into it:

- Crash log
- Forge version
- Bountiful version
- Other mods

**Comment by yoytastic** [comment]
you so kind and im so dumb, i was messing around like 10 villages with no board and now i opened the game and just found one, anyway im really really thankful you answered that fast and im really really sorry for bothering you :c anyway i love this mod idea, basically i started playing with mods just to make an arpg style based on this mod

**Comment by ejektaflex** [comment]
I'm glad you found one! Some people get a bit unlucky. It's really hard to know whether it's working or not, so I understand :^)
