### ISSUE TITLE
[Suggestion] Multiple distinct bounty boards?

### ISSUE THREAD

**Issue by Luke616** [ejektaflex/Bountiful#14]
Kind of a big suggestion/request here. I know some mods out there (Mob Spawner Control, for example) allow for multiple of their custom blocks to be made using different versions of the configs. Any way you could add something similar for Bountiful so that multiple bounty boards can be added?

Here's the motivation behind my request. I've been putting together a pack and have been wishing I could install bountiful twice! A large part of the pack is based around agriculture with a focus on cooking and expanding a farm. I've added bountiful and have actually renamed the bounty board to be called the "order board" and have restricted the list of bounties to a bunch of complex food items from various mods, with the rewards being currency and XP bottles. In this sense, the "order board" in my pack acts as a way for players to simulate running their own restaurants and turn a much larger profit from their farms than they would using stuff like the pam's shipping bin.

However, another large part of the pack is adventuring, and I think it would be really neat to have a different "bounty board" block with the new mob hunting quests on it, for example. I don't want to just pick one and I think it would be strange having food orders and hunting quests come through on the same block. I'd also like to configure them differently. Hence, I wish I could install the mod twice, or have multiple bounty boards.

**Comment by ejektaflex** [comment]
This *does* keep getting suggested, and while it is indeed a little out of scope for Bountiful, I think that if people keep asking I will have to expand my scope :)

I wouldnt mind working on a system in the future that adds multiple different types of boards. My only question would be, how would one determine how a board gets set to pull from a specific pool?

I'm not sure what in-world way there would be for someone to change the type, or if there should be a separate block for each pool of bounties. And in that case, how would one determine the recipes? So many questions. 

Friend me on Discord (Ejektaflex#4616) and we can talk about it!

**Comment by Luke616** [comment]
Ah, didn't realize it had been suggested before! Sorry if I'd made a duplicate post. I'm not sure how the logistics of it would work out, but I'll think about it and add you on discord now (Luke616#7247)

**Comment by ejektaflex** [comment]
@esotericist That's definitely possible, although it would be even nicer to do this if there were no items invoved (What if a modpack gates name tags? What if a modpack makes them super common? Etc.)

**Comment by drakray** [comment]
Hi there, might I suggest some king of shift-clicked GUI? where the button list are the different pool available, and only OP/block-placer could change the "type"?
In JSON, using ID to link button/bounties/rewards, with a "poolname" tag for block header/name/sorting?
Maybe even another json altogether for pool-setting, with their own config(global, time for respawn, etc)

**Comment by ejektaflex** [comment]
@drakray That's a good idea. The bounty board could store a second inventory containing a single ghost slot, and depending on what you put in it, it could change the inventory for that board.

**Comment by ejektaflex** [comment]
Okay - this is coming to Bountiful v3.0, which is getting quite close to a release now. Bounty boards now have three slots, and you can put **Decrees** in them. Depending on what decrees you have on a bounty board, different objectives and rewards will show up! Since a Decree is technically just a collection of objectives and rewards, and you can mix and match them, there should be a lot of flexibility when deciding what kind of things you want to do. Plus, this is still all JSON based, so you can still customize it to your heart's content!

**Comment by drakray** [comment]
Will v3 be available for 1.12.2?

**Comment by ejektaflex** [comment]
@drakray It will not, unfortunately. I'd like to, but there are far too many differences in how the new Forge code interacts with Minecraft (e.g. rendering a different image for each bounty rarity is completely different code from 1.12 and much, much more simple in 1.13+. Same for world generation!)

Because of that, it will be for Minecraft 1.14+!

**Comment by ejektaflex** [comment]
Since this has been implemented in the in-dev version of v3.0 for 1.14, I'll be closing this issue. Feel free to create another issue if you've got any other ideas or questions.

**Comment by drakray** [comment]
Ok, that is sad :'( , but thanks for your quick answer :)
