### ISSUE TITLE
I found some objective represented as air

### ISSUE THREAD

**Issue by kruyua** [ejektaflex/Bountiful#141]
## Bug Report

**Observed Behaviour**

What happened: As I mentioned, I found some objective called 'air' with fishing decree. 

Crash log: (this behaviour didn't lead to game crash)

**Expected Behaviour**

What should have happened:

I found this in your mod. (Bountiful/src/main/resources/data/bountiful/bounties/pools/upgrade_aquatic/fisherman_objs.json)

{
      "type": "item",
      "content": "upgrade_aquatic:bedroll_leather",
      "amountRange": {
        "min": 1,
        "max": 1
      },
      "unitWorth": 2500,
      "weight": 1000
    }

But I think the item called "bedroll_leather"(I don't know the exact name) was deleted in upgrade aquatic 3.1.0 or older version. So I think this objective should be removed. 

**Minimal setup needed to reproduce**

- Forge version: 36.1.32
- Bountiful version: 3.3.1
- Other mods: farming for blockheads 7.3.1, inspirations 1.2.3.37, nature's compass 1.9.1, quark r2.4-314, upgrade aquatic 3.1.0 (I use lots of mods but I wrote some of them that are compatible with bountiful)

**Steps to reproduce**

How to recreate this:
1. Find bounty board in a village with 'fishing' decree
2. Check some objectives with 'air'

**Comment by ejektaflex** [comment]
Sounds great! Thank you. If you want to confirm the item, you can hold the bounty in your hand and type "/bo hand". This should copy some JSON into your clipboard, which you can paste here. It will probably indicate that the contents of the bounty are an aquatic bedroll.

Thank you!

**Comment by kruyua** [comment]
As you said, I checked the bounty by typing "/bo hand". This is a copy of JSON.

{
  "type": "item",
  "content": "bountiful:bounty",
  "nbt": {
    "boardStamp": "430203L",
    "bountyStamp": "451583L",
    "objectives": {
      "0": {
        "killedAmount": 0,
        "amount": 12,
        "type": "entity",
        "unitWorth": 225,
        "content": "minecraft:skeleton"
      },
      "1": {
        "amount": 1,
        "type": "item",
        "unitWorth": 2500,
        "content": "upgrade_aquatic:bedroll_leather"
      }
    },
    "bountyTime": "128250L",
    "rewards": {
      "0": {
        "amount": 2,
        "type": "item",
        "unitWorth": 3000,
        "content": "minecraft:cod_bucket"
      }
    },
    "rarity": 1
  },
  "amountRange": {
    "min": 1,
    "max": 1
  },
  "unitWorth": 1000,
  "weight": 1000
}

Thank you for letting me know how to check the 'air'! I could find if there is another 'air' in bounty objective effectively.
Anyway, would you change aquatic bedroll into another item or just delete it?

**Comment by ejektaflex** [comment]
I'd have to check the update aquatic. If there's a suitable replacement, then I'll replace it. Otherwise, I'll remove it completely. 
Thanks much for the report! I'll try get to it when I have some time.

**Comment by ejektaflex** [comment]
In 1.20.1+, air items can no longer be generated since they would fail validation before getting set as the default (air). As such, this can be closed.
