### ISSUE TITLE
[Bug]: Bounty boards are not generating

### ISSUE THREAD

**Issue by ghost** [ejektaflex/Bountiful#147]
### What happened?

I simply installed the mod with Forge 36.2.0 and the boards are not generating.

Here is my modlist [imgur](https://imgur.com/QrLQBDU)

### How can we reproduce it?

Not sure...

### Mod Version

3.3.1

### Forge Version

36.2.0

### Relevant log output

[latest.log](https://github.com/ejektaflex/Bountiful/files/7049368/latest.log)

**Comment by ejektaflex** [comment]
Have you tried changing the config option that increases how often they show up?

I've got this type of bug report several times now, but most times it has just been from very unlucky people :^)

**Comment by ghost** [comment]
> Have you tried changing the config option that increases how often they show up?
> 
> I've got this type of bug report several times now, but most times it has just been from very unlucky people :^)

I didn't changed anything at the configs but at the log there are several errors with the mod. Is it not related to this?

**Comment by ejektaflex** [comment]
There is one error related to Bountiful in the log, but it does not affect gameplay. You can view #143 , it's the same thing, but it is not an issue. I do not see any errors relating to world generation, so I think that you should change your config for that world (in serverconfigs), upping the generation frequency.

**Comment by ghost** [comment]
> There is one error related to Bountiful in the log, but it does not affect gameplay. You can view #143 , it's the same thing, but it is not an issue. I do not see any errors relating to world generation, so I think that you should change your config for that world (in serverconfigs), upping the generation frequency.

I tought the error is related to the whole mod. Thanks for the reply.
