### ISSUE TITLE
[Bug]: Game crash when Bountiful load a reward including ContentTweaker items

### ISSUE THREAD

**Issue by RisingInIris2017** [ejektaflex/Bountiful#148]
### What happened?

Game crashes during its loading.

### How can we reproduce it?

This issue happens in my modpack, you can download it [here](https://www.curseforge.com/minecraft/modpacks/blessed-or-cursed-expedition-to-infinite-force/files/3432112) for testing.

This problem cannot be reproduced at 100% probability, but only occurs sometimes.
To reproduce it, simply start the game and wait it to crash.

### Mod Version

1.12.2-2.2.2

### Forge Version

14.23.5.2855

### Relevant log output

---- Minecraft Crash Report ----
// Don't do that.

Time: 2021-08-26 11:55:43 CST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Bountiful (bountiful)
Caused by: java.lang.Exception: 'bountiful/rewards.json' contains one or more invalid rewards. Invalid rewards: [PickedEntry (Stack) [Item: contenttweaker:first_killcount_token, Amount: 60, NBT: null, Weight: 300, Stages: null], PickedEntry (Stack) [Item: contenttweaker:second_killcount_token, Amount: 1260, NBT: null, Weight: 90, Stages: null], PickedEntry (Stack) [Item: contenttweaker:lemon_battery, Amount: 60, NBT: null, Weight: 240, Stages: null]]
    at ejektaflex.bountiful.proxy.CommonProxy.postInit(CommonProxy.kt:112)
    at ejektaflex.bountiful.Bountiful.postInit(Bountiful.kt:53)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_271, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3061836208 bytes (2919 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
  JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2855 66 mods loaded, 66 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                    | Version              | Source                                          | Signature                                |
       |:----- |:--------------------- |:-------------------- |:----------------------------------------------- |:---------------------------------------- |
       | LCHIJ | minecraft             | 1.12.2               | minecraft.jar                                   | None                                     |
       | LCHIJ | mcp                   | 9.42                 | minecraft.jar                                   | None                                     |
       | LCHIJ | FML                   | 8.0.99.99            | forge-1.12.2-14.23.5.2855.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJ | forge                 | 14.23.5.2855         | forge-1.12.2-14.23.5.2855.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJ | dcs_asm               | 2.1.0                | minecraft.jar                                   | 4cd12b92959105443b7b694fffe0cea9ed004886 |
       | LCHIJ | konkrete              | 1.1.6                | konkrete_1.1.6_MC_1.12-1.12.2.jar               | None                                     |
       | LCHIJ | fancymenu             | 2.1.0                | fancymenu_2.1.0_MC_1.12-1.12.2.jar              | None                                     |
       | LCHIJ | absentbydesign        | 1.12.2-1.0.4         | absentbydesign-1.12.2-1.0.4.jar                 | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
       | LCHIJ | crafttweaker          | 4.1.20               | CraftTweaker2-1.12-4.1.20.652.jar               | None                                     |
       | LCHIJ | mtlib                 | 3.0.6                | MTLib-3.0.6.jar                                 | None                                     |
       | LCHIJ | modtweaker            | 4.0.18               | modtweaker-4.0.18.jar                           | None                                     |
       | LCHIJ | jei                   | 4.16.1.302           | jei_1.12.2-4.16.1.302.jar                       | None                                     |
       | LCHIJ | abyssalcraft          | 1.10.3               | AbyssalCraft-1.12.2-1.10.3.jar                  | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCHIJ | acintegration         | 1.11.2               | AbyssalCraft Integration-1.12.2-1.11.2.jar      | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCHIJ | applecore             | 3.4.0                | AppleCore-mc1.12.2-3.4.0.jar                    | None                                     |
       | LCHIJ | appleskin             | 1.0.14               | AppleSkin-mc1.12-1.0.14.jar                     | None                                     |
       | LCHIJ | base                  | 3.13.0               | base-1.12.2-3.13.0.jar                          | None                                     |
       | LCHIJ | baubles               | 1.5.2                | Baubles-1.12-1.5.2.jar                          | None                                     |
       | LCHIJ | blockdrops            | 1.4.0                | blockdrops-1.12.2-1.4.0.jar                     | None                                     |
       | LCHIJ | thaumcraft            | 6.1.BETA26           | Thaumcraft-1.12.2-6.1.BETA26.jar                | None                                     |
       | LCHIJ | botania               | r1.10-363            | Botania r1.10-363.jar                           | None                                     |
       | LCHIJ | forgelin              | 1.8.4                | Forgelin-1.8.4.jar                              | None                                     |
       | LCHIE | bountiful             | 2.2.2                | Bountiful-2.2.2.jar                             | None                                     |
       | LCHI  | buildinggadgets       | 2.8.4                | BuildingGadgets-2.8.4.jar                       | None                                     |
       | LCHI  | chargers              | 1.2.0.5              | Chargers-1.12.2-1.2.0.5.jar                     | 58e787c8aafad8b327883f94d4fa544f936d7b01 |
       | LCHI  | codechickenlib        | 3.2.3.358            | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHI  | contenttweaker        | 1.12.2-4.9.1         | ContentTweaker-1.12.2-4.9.1.jar                 | None                                     |
       | LCHI  | ctgui                 | 1.0.0                | CraftTweaker2-1.12-4.1.20.652.jar               | None                                     |
       | LCHI  | crafttweakerjei       | 2.0.3                | CraftTweaker2-1.12-4.1.20.652.jar               | None                                     |
       | LCHI  | customskinloader      | 14.11                | CustomSkinLoader_Forge-14.11.jar                | 52885f395e68f42e9b3b629ba56ecf606f7d4269 |
       | LCHI  | dupefixproject        | 3.1.2                | DupeFixProject-1.12.2-3.1.2.jar                 | None                                     |
       | LCHI  | durabilityviewer      | 1.4                  | DurabilityViewer-1.12-forge14.21.1.2387-1.4.jar | None                                     |
       | LCHI  | earthworks            | 1.3.4.3              | Earthworks-1.12-1.3.6.jar                       | None                                     |
       | LCHI  | enchdesc              | 1.1.20               | EnchantmentDescriptions-1.12.2-1.1.20.jar       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHI  | energyconverters      | 1.3.7.30             | energyconverters_1.12.2-1.3.7.30.jar            | None                                     |
       | LCHI  | futuremc              | 0.2.6                | future-mc-1.12.2-0.2.6.1.jar                    | None                                     |
       | LCHI  | gravestone            | 1.10.3               | gravestone-1.10.3.jar                           | None                                     |
       | LCHI  | dcs_lib               | 3.7.0                | HeatAndClimateLib_1.12.2-3.7.0.jar              | 4cd12b92959105443b7b694fffe0cea9ed004886 |
       | LCHI  | waila                 | 1.8.26               | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
       | LCHI  | incontrol             | 3.9.18               | incontrol-1.12-3.9.18.jar                       | None                                     |
       | LCHI  | ic2                   | 2.8.170-ex112        | industrialcraft-2-2.8.170-ex112.jar             | de041f9f6187debbc77034a344134053277aa3b0 |
       | LCHI  | initialinventory      | 2.0.2                | InitialInventory-3.0.0.jar                      | None                                     |
       | LCHI  | inventorytweaks       | 1.64+dev.150.7168e7a | InventoryTweaks-1.64+dev.150.jar                | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHI  | journeymap            | 1.12.2-5.5.5         | journeymap-1.12.2-5.5.5.jar                     | None                                     |
       | LCHI  | loottweaker           | 0.3.0                | LootTweaker-0.3.0+MC1.12.2.jar                  | None                                     |
       | LCHI  | jeresources           | 0.9.2.60             | JustEnoughResources-1.12.2-0.9.2.60.jar         | None                                     |
       | LCHI  | mcwfurnitures         | 1.0.1                | mcw-furniture-1.0.1-mc1.12.2beta.jar            | None                                     |
       | LCHI  | mm_lib                | 2.3.0                | MMLib-2.3.0.jar                                 | None                                     |
       | LCHI  | norecipebook          | 1.2.1                | noRecipeBook_v1.2.2formc1.12.2.jar              | None                                     |
       | LCHI  | patchouli             | 1.0-21               | Patchouli-1.0-21.jar                            | None                                     |
       | LCHI  | redstoneflux          | 2.1.1                | RedstoneFlux-1.12-2.1.1.1-universal.jar         | None                                     |
       | LCHI  | resourceloader        | 1.5.3                | ResourceLoader-MC1.12.1-1.5.3.jar               | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHI  | sakura                | 1.0.7-1.12.2         | Sakura-1.0.7-1.12.2.jar                         | None                                     |
       | LCHI  | flammpfeil.slashblade | mc1.12-r33           | SlashBlade-mc1.12-r33.jar                       | None                                     |
       | LCHI  | slashblade_addon      | 1.6.0                | SJAP-1.6.0.jar                                  | None                                     |
       | LCHI  | spawnercontrol        | 1.6.3b               | SpawnerControl-1.6.3b.jar                       | None                                     |
       | LCHI  | surge                 | 2.0.79               | Surge-1.12.2-2.0.79.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHI  | tofucraft             | 0.1.0.9              | TofuCraftReload-0.1.0.9.jar                     | None                                     |
       | LCHI  | touhou_little_maid    | 1.2.4                | touhoulittlemaid-1.12.2-1.2.4-release.jar       | None                                     |
       | LCHI  | treechopper           | 1.2.4                | TreeChopper-1.12.2-1.2.4.jar                    | None                                     |
       | LCHI  | twilightforest        | 3.10.1013            | twilightforest-1.12.2-3.10.1013-universal.jar   | None                                     |
       | LCHI  | vanillaanvilrepair    | 1.1                  | vanillaanvilrepair-1.1.jar                      | None                                     |
       | LCHI  | vanillafix            | 1.0.10-150           | VanillaFix-1.0.10-150.jar                       | None                                     |
       | LCHI  | wailaharvestability   | 1.1.12               | WailaHarvestability-mc1.12-1.1.12.jar           | None                                     |
       | LCHI  | zenutils              | 1.8.3                | zenutils-1.8.3.jar                              | None                                     |
       | LCHI  | jade                  | 0.1.0                | Jade-0.1.0.jar                                  | None                                     |
  Loaded coremods (and transformers): DupeFixProjectCoreMod (DupeFixProject-1.12.2-3.1.2.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      CustomSkinLoader (CustomSkinLoader_Forge-14.11.jar)
                                        customskinloader.forge.loader.LaunchWrapper
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      DCASMPlugin (HeatAndClimateLib_1.12.2-3.7.0.jar)
                                        defeatedcrow.hac.asm.DCMethodTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.150.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.79.jar)
                                        
                                      FutureMC (future-mc-1.12.2-0.2.6.1.jar)
                                        thedarkcolour.futuremc.asm.CoreTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 461.40' Renderer: 'GeForce GTX 1650 SUPER/PCIe/SSE2'
  Patchouli open book context: n/a
  Suspected Mods: Bountiful (bountiful)
  Launched Version: HMCL 3.3.188
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 1650 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.40, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: 简体中文 (中国)
  Profiler Position: N/A (disabled)
  CPU: 6x AMD Ryzen 5 3500X 6-Core Processor

**Comment by ejektaflex** [comment]
```
Caused by: java.lang.Exception: 'bountiful/rewards.json' contains one or more invalid rewards. Invalid rewards: 
[PickedEntry (Stack) [Item: contenttweaker:first_killcount_token, Amount: 60, NBT: null, Weight: 300, Stages: null], 
PickedEntry (Stack) [Item: contenttweaker:second_killcount_token, Amount: 1260, NBT: null, Weight: 90, Stages: null], 
PickedEntry (Stack) [Item: contenttweaker:lemon_battery, Amount: 60, NBT: null, Weight: 240, Stages: null]]
```

Your rewards.json file contains some invalid rewards. One of more of these items may be named incorrectly or may not exist. See:
[Wiki Page](https://github.com/ejektaflex/Bountiful/wiki/1.12-Home)
for a list of commands used in the 1.12 version.

I usually intend for people to be adding rewards, saving the file and then using `/bo reload` to reload their files while the game is running :^). That way, the game can tell you if any of the rewards are invalid. If they don't do that, then the game will throw this error on launch, or when it encounters the invalid reward.

To fix, remove these rewards. Then, try to re-add them while the game is running, save the file, and run `/bo reload` to see if loading the new rewards works correctly. Repeat until the rewards load as intended.

Hope that helps! :^)
