### ISSUE TITLE
[Bug]: Bountyboards are not spawning

### ISSUE THREAD

**Issue by pritam20ps05** [ejektaflex/Bountiful#149]
### What happened?

I dont know that if its a installation problem or something else but the bounty boards are not spawning in any village. Also cant find config file or folder for bountiful. BTW playing on forge server 1.16.5 on aternos. please tell what could the problem be.

### How can we reproduce it?

IDK but happens for me just installing them normally after creating a world and locating them 
my current activated mods are: 

abnormals_core-1.16.5-3.2.0
alexsmobs-1.12.0
Artifacts-1.16.5-2.10.0
atmospheric-1.16.5-3.1.0
AutoRegLib-1.6-49
BetterCaves-Forge-1.16.4-1.1.2
betterendforge-1.16.4-1.6.0
BetterMineshafts-Forge-1.16.4-2.0.4
BetterStrongholds-1.16.4-1.2.1
betterweather-2.0.1
BiomesOPlenty-1.16.5-13.1.0.482-universal
Bountiful-1.16.4-3.3.1
cgm-1.0.1-1.16.3
citadel-1.8.1-1.16.5
CTM-MC1.16.1-1.1.2.6
curios-forge-1.16.5-4.0.5.2
expandability-2.0.1-forge
iceandfire-2.1.9-1.16.5
kotlinforforge-1.14.0-obf
obfuscate-0.6.2-1.16.3
Patchouli-1.16.4-53.1
Quark-r2.4-316
repurposed_structures_forge-3.2.2+1.16.5
twilightforest-1.16.5-4.0.546-universal
upgrade_aquatic-1.16.5-3.1.0
valhelsia_core-16.0.10
valhelsia_structures-1.16.5-0.1.5
YungsApi-1.16.4-Forge-12

check if there is any possible conflict

### Mod Version

3.3.1

### Forge Version

1.16.5 (36.2.0)

### Relevant log output

the best i can provide is: 

<html>
<body>

[31Aug2021 17:35:17.740] [Worker-Main-4/ERROR] [net.minecraft.loot.LootTableManager/]: Couldn't parse loot table bountiful:blocks/bountyboard
--
233 | com.google.gson.JsonSyntaxException: Missing ops, expected to find a JsonArray
234 | at net.minecraft.util.JSONUtils.func_151214_t(SourceFile:425) ~[?:?]
235 | at net.minecraft.loot.functions.CopyNbt$Serializer.func_186530_b(SourceFile:245) ~[?:?]
236 | at net.minecraft.loot.functions.CopyNbt$Serializer.func_186530_b(SourceFile:231) ~[?:?]
237 | at net.minecraft.loot.LootFunction$Serializer.func_230423_a_(SourceFile:99) ~[?:?]
238 | at net.minecraft.loot.LootFunction$Serializer.func_230423_a_(SourceFile:88) ~[?:?]
239 | at net.minecraft.loot.LootTypesManager$Serializer.deserialize(SourceFile:83) ~[?:?]
240 | at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[server-1.16.5-20210115.111550-extra.jar:?]
241 | at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[server-1.16.5-20210115.111550-extra.jar:?]
242 | at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[server-1.16.5-20210115.111550-extra.jar:?]
243 | at com.google.gson.Gson.fromJson(Gson.java:887) ~[server-1.16.5-20210115.111550-extra.jar:?]
244 | at com.google.gson.Gson.fromJson(Gson.java:952) ~[server-1.16.5-20210115.111550-extra.jar:?]
245 | at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[server-1.16.5-20210115.111550-extra.jar:?]
246 | at net.minecraft.util.JSONUtils.func_188179_a(SourceFile:440) ~[?:?]
247 | at net.minecraft.util.JSONUtils.func_188177_a(SourceFile:456) ~[?:?]
248 | at net.minecraft.loot.StandaloneLootEntry$Serializer.func_230421_b_(SourceFile:149) ~[?:?]
249 | at net.minecraft.loot.StandaloneLootEntry$Serializer.func_230421_b_(SourceFile:129) ~[?:?]
250 | at net.minecraft.loot.LootEntry$Serializer.func_230423_a_(SourceFile:86) ~[?:?]
251 | at net.minecraft.loot.LootEntry$Serializer.func_230423_a_(SourceFile:74) ~[?:?]
252 | at net.minecraft.loot.LootTypesManager$Serializer.deserialize(SourceFile:83) ~[?:?]
253 | at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[server-1.16.5-20210115.111550-extra.jar:?]
254 | at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[server-1.16.5-20210115.111550-extra.jar:?]
255 | at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[server-1.16.5-20210115.111550-extra.jar:?]
256 | at com.google.gson.Gson.fromJson(Gson.java:887) ~[server-1.16.5-20210115.111550-extra.jar:?]
257 | at com.google.gson.Gson.fromJson(Gson.java:952) ~[server-1.16.5-20210115.111550-extra.jar:?]
258 | at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[server-1.16.5-20210115.111550-extra.jar:?]
259 | at net.minecraft.util.JSONUtils.func_188179_a(SourceFile:440) ~[?:?]
260 | at net.minecraft.util.JSONUtils.func_188174_a(SourceFile:448) ~[?:?]
261 | at net.minecraft.loot.LootPool$Serializer.deserialize(LootPool.java:183) ~[?:?]
262 | at net.minecraft.loot.LootPool$Serializer.deserialize(LootPool.java:180) ~[?:?]
263 | at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[server-1.16.5-20210115.111550-extra.jar:?]
264 | at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[server-1.16.5-20210115.111550-extra.jar:?]
265 | at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[server-1.16.5-20210115.111550-extra.jar:?]
266 | at com.google.gson.Gson.fromJson(Gson.java:887) ~[server-1.16.5-20210115.111550-extra.jar:?]
267 | at com.google.gson.Gson.fromJson(Gson.java:952) ~[server-1.16.5-20210115.111550-extra.jar:?]
268 | at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[server-1.16.5-20210115.111550-extra.jar:?]
269 | at net.minecraft.util.JSONUtils.func_188179_a(SourceFile:440) ~[?:?]
270 | at net.minecraft.util.JSONUtils.func_188177_a(SourceFile:456) ~[?:?]
271 | at net.minecraft.loot.LootTable$Serializer.deserialize(LootTable.java:252) ~[?:?]
272 | at net.minecraft.loot.LootTable$Serializer.deserialize(LootTable.java:249) ~[?:?]
273 | at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[server-1.16.5-20210115.111550-extra.jar:?]
274 | at com.google.gson.Gson.fromJson(Gson.java:887) ~[server-1.16.5-20210115.111550-extra.jar:?]
275 | at com.google.gson.Gson.fromJson(Gson.java:952) ~[server-1.16.5-20210115.111550-extra.jar:?]
276 | at com.google.gson.Gson.fromJson(Gson.java:925) ~[server-1.16.5-20210115.111550-extra.jar:?]
277 | at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:881) ~[forge:?]
278 | at net.minecraft.loot.LootTableManager.lambda$apply$0(LootTableManager.java:40) ~[?:?]
279 | at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_282]
280 | at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:38) ~[?:?]
281 | at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:16) ~[?:?]
282 | at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?]
283 | at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_282]
284 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_282]
285 | at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_282]
286 | at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
287 | at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?]
288 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) ~[?:1.8.0_282]
289 | at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) ~[?:1.8.0_282]
290 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_282]
291 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_282]
292 | at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575) ~[?:1.8.0_282]
293 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649) ~[?:1.8.0_282]
294 | at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_282]
295 | at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
296 | at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?]
297 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) ~[?:1.8.0_282]
298 | at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) ~[?:1.8.0_282]
299 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_282]
300 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_282]
301 | at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575) ~[?:1.8.0_282]
302 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649) ~[?:1.8.0_282]
303 | at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_282]
304 | at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
305 | at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?]
306 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) ~[?:1.8.0_282]
307 | at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) ~[?:1.8.0_282]
308 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_282]
309 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_282]
310 | at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575) ~[?:1.8.0_282]
311 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649) ~[?:1.8.0_282]
312 | at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_282]
313 | at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
314 | at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?]
315 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) ~[?:1.8.0_282]
316 | at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) ~[?:1.8.0_282]
317 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_282]
318 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_282]
319 | at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575) ~[?:1.8.0_282]
320 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649) ~[?:1.8.0_282]
321 | at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_282]
322 | at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
323 | at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?]
324 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) ~[?:1.8.0_282]
325 | at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) ~[?:1.8.0_282]
326 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_282]
327 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_282]
328 | at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575) ~[?:1.8.0_282]
329 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649) ~[?:1.8.0_282]
330 | at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_282]
331 | at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
332 | at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?]
333 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) ~[?:1.8.0_282]
334 | at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) ~[?:1.8.0_282]
335 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_282]
336 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_282]
337 | at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) ~[?:1.8.0_282]
338 | at net.minecraft.resources.AsyncReloader$1.func_216873_a(SourceFile:53) ~[?:?]
339 | at net.minecraft.resources.AsyncReloader$1.func_216872_a(SourceFile:50) ~[?:?]
340 | at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) [?:1.8.0_282]
341 | at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) [?:1.8.0_282]
342 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_282]
343 | at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) [?:1.8.0_282]
344 | at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_282]
345 | at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_282]
346 | at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_282]
347 | at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_282]
348 | at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_282]
349 | [31Aug2021 17:35:18.862] [Worker-Main-4/WARN] [net.minecraft.loot.LootTableManager/]: Found validation problem in {alexsmobs:gameplay/seal_reward}.pools[0].entries[1].functions[0]: Parameters [<parameter minecraft:origin>] are not provided in this context
350 | [31Aug2021 17:35:19.991] [Worker-Main-4/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 2013 advancements
351 | [31Aug2021 17:35:20.056] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Loading Bounty Data. We will probably skip some data since certain mods are not loaded.
352 | [31Aug2021 17:35:20.109] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/simplytea/chef_objs as dependencies are not met: [simplytea]
353 | [31Aug2021 17:35:20.120] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/inspirations/farmer_rews as dependencies are not met: [inspirations]
354 | [31Aug2021 17:35:20.131] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/vanillafoodpantry/chef_objs as dependencies are not met: [vanillafoodpantry]
355 | [31Aug2021 17:35:20.140] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/apotheosis/fletcher_rews as dependencies are not met: [apotheosis]
356 | [31Aug2021 17:35:20.148] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/aquaculture/fisherman_rews as dependencies are not met: [aquaculture]
357 | [31Aug2021 17:35:20.151] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/mysticalworld/armorer_rews as dependencies are not met: [mysticalworld]
358 | [31Aug2021 17:35:20.152] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/comforts/shepherd_objs as dependencies are not met: [comforts]
359 | [31Aug2021 17:35:20.158] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/charm/tinker_objs as dependencies are not met: [charm]
360 | [31Aug2021 17:35:20.159] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/mysticalworld/armorer_objs as dependencies are not met: [mysticalworld]
361 | [31Aug2021 17:35:20.167] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/aquaculture/fisherman_objs as dependencies are not met: [aquaculture]
362 | [31Aug2021 17:35:20.170] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/simplefarming/chef_objs as dependencies are not met: [simplefarming]
363 | [31Aug2021 17:35:20.174] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/upgrademodifiers/armorer_rews as dependencies are not met: [upgrademodifiers]
364 | [31Aug2021 17:35:20.181] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/charm/tinker_rews as dependencies are not met: [charm]
365 | [31Aug2021 17:35:20.182] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/naturescompass/toolsmith_rews as dependencies are not met: [naturescompass]
366 | [31Aug2021 17:35:20.185] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/storagedrawers/tinker_rews as dependencies are not met: [storagedrawers]
367 | [31Aug2021 17:35:20.197] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/inspirations/tinker_rews as dependencies are not met: [inspirations]
368 | [31Aug2021 17:35:20.205] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/farmingforblockheads/farmer_objs as dependencies are not met: [farmingforblockheads]
369 | [31Aug2021 17:35:20.209] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/upgrademodifiers/toolsmith_rews as dependencies are not met: [upgrademodifiers]
370 | [31Aug2021 17:35:20.215] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/mysticalworld/chef_objs as dependencies are not met: [mysticalworld]
371 | [31Aug2021 17:35:20.216] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/vanillafoodpantry/chef_rews as dependencies are not met: [vanillafoodpantry]
372 | [31Aug2021 17:35:20.220] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/inspirations/fletcher_rews as dependencies are not met: [inspirations]
373 | [31Aug2021 17:35:20.221] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/aquaculture/tinker_rews as dependencies are not met: [aquaculture]
374 | [31Aug2021 17:35:20.222] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/farmingforblockheads/farmer_rews as dependencies are not met: [farmingforblockheads]
375 | [31Aug2021 17:35:20.224] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/xlfoodmod/chef_objs as dependencies are not met: [xlfoodmod]
376 | [31Aug2021 17:35:20.228] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/mysticalworld/farmer_objs as dependencies are not met: [mysticalworld]
377 | [31Aug2021 17:35:20.232] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/simplefarming/farmer_objs as dependencies are not met: [simplefarming]
378 | [31Aug2021 17:35:20.235] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/xlfoodmod/chef_rews as dependencies are not met: [xlfoodmod]
379 | [31Aug2021 17:35:20.235] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Skipping load of bountiful:pools/simplefarming/farmer_rews as dependencies are not met: [simplefarming]
380 | [31Aug2021 17:35:20.236] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Found decrees: [hunting, butcher, mason, librarian, farmer, toolsmith, chef, mapper, armorer, fletcher, fisherman, cleric, leatherer, shepherd, tinker]
381 | [31Aug2021 17:35:20.237] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Merging Entry Pools..
382 | [31Aug2021 17:35:20.237] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating Entry Pools..
383 | [31Aug2021 17:35:20.237] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'toolsmith_objs'
384 | [31Aug2021 17:35:20.241] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'butcher_rews'
385 | [31Aug2021 17:35:20.242] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'tinker_objs'
386 | [31Aug2021 17:35:20.242] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'common_enchants'
387 | [31Aug2021 17:35:20.243] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'fisherman_rews'
388 | [31Aug2021 17:35:20.243] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'shepherd_objs'
389 | [31Aug2021 17:35:20.303] [Worker-Main-4/WARN] [ejektaflex.bountiful.BountifulMod/]: Invalid pool item: BountyEntry (item-tag) [Item: minecraft:wool, Amount: 0 [[4..32]], Worth: 250, NBT: null, Weight: 1000]
390 | [31Aug2021 17:35:20.304] [Worker-Main-4/WARN] [ejektaflex.bountiful.BountifulMod/]: Invalid pool item: BountyEntry (item-tag) [Item: forge:dyes, Amount: 0 [[2..16]], Worth: 200, NBT: null, Weight: 1000]
391 | [31Aug2021 17:35:20.304] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'chef_objs'
392 | [31Aug2021 17:35:20.309] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'toolsmith_rews'
393 | [31Aug2021 17:35:20.323] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'fisherman_objs'
394 | [31Aug2021 17:35:20.324] [Worker-Main-4/WARN] [ejektaflex.bountiful.BountifulMod/]: Invalid pool item: BountyEntry (item) [Item: upgrade_aquatic:bedroll_leather, Amount: 0 [[1..1]], Worth: 2500, NBT: null, Weight: 1000]
395 | [31Aug2021 17:35:20.324] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'leatherer_rews'
396 | [31Aug2021 17:35:20.325] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'farmer_rews'
397 | [31Aug2021 17:35:20.325] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'cleric_objs'
398 | [31Aug2021 17:35:20.325] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'shepherd_rews'
399 | [31Aug2021 17:35:20.326] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'farmer_objs'
400 | [31Aug2021 17:35:20.330] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'tinker_rews'
401 | [31Aug2021 17:35:20.331] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'butcher_objs'
402 | [31Aug2021 17:35:20.331] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'librarian_objs'
403 | [31Aug2021 17:35:20.331] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'common_crafts'
404 | [31Aug2021 17:35:20.331] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'librarian_rews'
405 | [31Aug2021 17:35:20.331] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'armorer_objs'
406 | [31Aug2021 17:35:20.333] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'mason_objs'
407 | [31Aug2021 17:35:20.359] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'hunting_objs'
408 | [31Aug2021 17:35:20.359] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'hunting_rews'
409 | [31Aug2021 17:35:20.360] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'all_villager_objs'
410 | [31Aug2021 17:35:20.360] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'armorer_rews'
411 | [31Aug2021 17:35:20.360] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'cleric_rews'
412 | [31Aug2021 17:35:20.361] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'all_villager_rews'
413 | [31Aug2021 17:35:20.361] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'chef_rews'
414 | [31Aug2021 17:35:20.361] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'fletcher_objs'
415 | [31Aug2021 17:35:20.361] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'mapper_rews'
416 | [31Aug2021 17:35:20.361] [Worker-Main-4/WARN] [ejektaflex.bountiful.BountifulMod/]: Invalid pool item: BountyEntry (item-tag) [Item: minecraft:banners, Amount: 0 [[1..3]], Worth: 750, NBT: null, Weight: 400]
417 | [31Aug2021 17:35:20.362] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'leatherer_objs'
418 | [31Aug2021 17:35:20.362] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'fletcher_rews'
419 | [31Aug2021 17:35:20.376] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'mapper_objs'
420 | [31Aug2021 17:35:20.377] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Validating pool 'mason_rews'
421 | [31Aug2021 17:35:20.377] [Worker-Main-4/INFO] [ejektaflex.bountiful.BountifulMod/]: Found Entry Pools: [hunting, butcher, mason, librarian, farmer, toolsmith, chef, mapper, armorer, fletcher, fisherman, cleric, leatherer, shepherd, tinker]
422 | [31Aug2021 17:35:43.939] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Starting minecraft server version 1.16.5

</body>
</html>

**Comment by ejektaflex** [comment]
This error is not related to bounty boards not spawning. See #143  and #147 . Did you change the config to make bounty boards more common?

**Comment by pritam20ps05** [comment]
Yea I know the parsing error is due to some update features discussed earlier. But where is the config file I searched for it in the config folder and couldn't find it.

**Comment by ejektaflex** [comment]
It's where all Forge serverside configs are. I haven't touched Forge in a while, but I believe it's in `[world folder]/serverconfigs/bountiful-server.toml`.

**Comment by pritam20ps05** [comment]
Yea yea got it
