### ISSUE TITLE
Minor Config Typo

### ISSUE THREAD

**Issue by NillerMedDild** [ejektaflex/Bountiful#15]
Hey o/

There's a little typo in the config, the comment says the default is 4800, but it's actually 6000.

    # The minimum bountyTime, in ticks, that a bounty can take to complete (Default: 4800)
        I:"Minimum Bounty Time"=6000

**Comment by NillerMedDild** [comment]
Oh a small question to accompany the report, I hope that's alright: Does the above mentioned config control the minimum time the player has to complete a bounty?

**Comment by ejektaflex** [comment]
Oops, yeah, that somehow go changed. It's the minimum time required to complete a bounty, yes.

**Comment by NillerMedDild** [comment]
The phrasing is throwing me off, minimum time required makes it sound like you have to wait before handing it in. It might just be me.

**Comment by ejektaflex** [comment]
Global bounties are also false by default, even those it's written to be true. My bad. Will be fixed :)
I'll change that phrasing for the future as well.

**Comment by ejektaflex** [comment]
Fixed as of a80af78, will be in the next update.
