### ISSUE TITLE
Localization bug in 1.16.5

### ISSUE THREAD

**Issue by MarijnIsN00B** [ejektaflex/Bountiful#152]
### What happened?

When you right-click a bountiful thing with an expired bounty, it says bountiful.bounty.expired

### How can we reproduce it?

Right-click a bountiful thing with an expired bounty, and it will say bountiful.bounty.expired

### Mod Version

3.3.0

### Forge Version

36.2.0

**Comment by ejektaflex** [comment]
I don't think I have time to maintain this version anymore. However, this should be fixed on 1.19.4+!
