### ISSUE TITLE
[Bug]: Can't use for 1.17 forge

### ISSUE THREAD

**Issue by LonelyLullaby** [ejektaflex/Bountiful#156]
### What happened?

i did download kotlin and it still doesn't work 
![image](https://user-images.githubusercontent.com/93275054/139100893-b86e1bba-2d89-4fab-a008-c143cb9db2ed.png)

### How can we reproduce it?

download the mod with kotlin for forge and run it 

### Mod Version

1.16.4 

### Forge Version

1.17.1

**Comment by ejektaflex** [comment]
There is no 1.17 version of the mod as of yet. I've been a bit busy, but I'll probably skip and port it to 1.18 at this rate!

**Comment by TheTexasDev** [comment]
> There is no 1.17 version of the mod as of yet. I've been a bit busy, but I'll probably skip and port it to 1.18 at this rate!

Did this ever happen and I'm missing it? I would love a version of this on 1.18.2 (forge) and I can't seem to find it

**Comment by ejektaflex** [comment]
That did not happen - the last Forge version was for 1.16.4, before I switched to Fabric for a while and then eventually merged the projects and released for 1.19.x and 1.20.1 on Fabric and Forge. 1.20.(4? 5?) and onwards will be Fabric and NeoForge. :)

**Comment by TheTexasDev** [comment]
If I knew how I would port it myself but neither java nor kotlin make any sense to me lol. Thank you anyway, this mod is awesome
