### ISSUE TITLE
Missing config file [Bug]: 

### ISSUE THREAD

**Issue by GiZM059** [ejektaflex/Bountiful#160]
### What happened?

Well, thats about it, i installed the mod for 1.16.5 but i am missing the config file, i dont know if i can just write a config myself, if that is possible i still would need the code, otherwise i would like to get another solution.

### Mod Version

Bountiful-1.16.4-3.3.1.

### Forge Version

36.2.20

**Comment by ejektaflex** [comment]
The config file shows up in `[your-world-folder]/serverconfigs/bountiful-server.toml`. This is standard practice for server-only configs made with Forge. If you want to make a config that works for all worlds that you create, you can create a `defaultconfigs` folder and copy the toml file into there!

I get this question a lot, so it feels like a failing on Forge's part that nobody knows where to look to find this.
