### ISSUE TITLE
[Bug][1.12.2] Bountiful ignoring config

### ISSUE THREAD

**Issue by Gideon9212** [ejektaflex/Bountiful#165]
### What happened?

Version: Bountiful-1.12.2-2.2.3
Modpack used: RLCraft

Issue:
Changing the bountiful.cfg on server side of things doesn't change how it interacts. 
Example:
Changing board breakable from false to true will still cause the board to be unbreakable.
Changing board recipe to enabled still cause the board to not be craftable.

### How can we reproduce it?

Step 1: Change something on the config from false to true.
Step 2. Launch the game to see it that the config change didn't work.

### Mod Version

1.12.2-2.2.3

### Forge Version

2860

### Relevant log output

No log as no errors show.

**Comment by ejektaflex** [comment]
I'm not maintaining 1.12.x anymore - that version was contributed by the creator of RLCraft for RLCraft - @Charles445, could you look into this?

**Comment by Charles445** [comment]
This was reported earlier but I didn't figure it out until now

For those two config options, the server and the client have to have matching config
1. The client doesn't have the recipe enabled, so even though it's enabled on the server, the client doesn't have it
2. The client still thinks the block is unbreakable, even though breaking it was enabled on the server

I think those are the only two config options that have to match on both the server and client

**Comment by Gideon9212** [comment]
That sounds like a bug considering most server configs with mods overwrite client. 

Should I test to see if pick up needs to match as well?

**Comment by ejektaflex** [comment]
Unfortunately, I won't be doing any further bugfixes for 1.12. That version of Minecraft is over five years old, and I don't have enough time to support it. Sorry!
