### ISSUE TITLE
[Bug]: Server crashes while ticking block entity

### ISSUE THREAD

**Issue by lunofe** [ejektaflex/Bountiful#167]
### What happened?

Unfortunately I am not aware of what happened to cause this crash. Bountiful was working without any problems for a while, then suddenly the server wasn't able to stay online longer than 5 minutes with Bountiful loaded.

### How can we reproduce it?

N/A, see above

### Mod Version

3.3.1

### Forge Version

36.2.23

### Relevant log output

[https://pastebin.com/raw/FAzasnK6](https://pastebin.com/raw/FAzasnK6)

**Comment by ejektaflex** [comment]
Very odd, but indeed a valid bug. For now, you can turn on the Forge option that removes erroring block/tile entities.
I'll look into it.

**Comment by lunofe** [comment]
Forgot to mention, I'm using "Mohist" which is a modern hybrid server like Cauldron back in the 1.7.10 days if that rings a bell. It's possible that this error only occurs on, or is caused by Mohist, as their changes sometimes break certain functions. Thanks for looking into it.

**Comment by ejektaflex** [comment]
I'm thinking that this could have been a problem with that. I've not heard of anything like this since. As such, I'm going to close this issue. Feel free to reopen it in case this is still happening on newer versions (1.19.4+ of Minecraft)!
