### ISSUE TITLE
[bug report]: GoodOlCurrency compat

### ISSUE THREAD

**Issue by AndMattBurt** [ejektaflex/Bountiful#169]
### What happened?

I recieved the wrong currency as a reward, it would only give me 1 dollar bills despite using /bo hand

interestingly though, only the same value rewards would stack even though they look the same

[currency_rews (broken).zip](https://github.com/ejektaflex/Bountiful/files/8079284/currency_rews.broken.zip)

### How can we reproduce it?

use /bo hand on any value of note from the mod, paste that as a reward
complete a task for the reward, recieve 1 dollar bill

(note: all say 1 dollar in the reward even though its identifying the tag of a higher value

### Mod Version

1.16.4 - 3.3.1

### Forge Version

1.16.5 - 36.2.26

**Comment by ejektaflex** [comment]
It's because they are using a byte value for the currency size - this is one of the few times where the NBT won't work here ("0b"), I don't think. I switched to using the uglier, but more correct version for Fabric. I'll leave this open, but it's not my priority to fix.

**Comment by Aiyron** [comment]
I said this to help but my mod is functional with since the currency is named "coin_stone" for example.

"Aiycoin" for the name take a look to see

**Comment by ejektaflex** [comment]
Hi - I won't be releasing new updates for the 1.16.5 version, so this will not be resolved. However, I don't think that this would have been easily solved, because it sounds like coins have assigned NBT with that mod, and the NBT counts them as separate coins.
