### ISSUE TITLE
[Bug]: No config for server

### ISSUE THREAD

**Issue by JakesAtLarge** [ejektaflex/Bountiful#177]
### What happened?

Hello I’m currently playing on a small server with friends using bisect hosting. Though we would like to edit the bounty requirements and rewards for the server. The issue though is that when I go into the config file there is no Bountiful config file and therefore no rewards.json file. I did find the .think file in server config though the file seems to be only used to edit the spawn rate of new bounties and their quality. Though also in my pack itself there is no file for bountiful.

### Mod Version

1.16.4

### Forge Version

36.2.20

**Comment by ejektaflex** [comment]
See the [wiki](https://github.com/ejektaflex/Bountiful/wiki/1.14+%20Data-Packs) for bounty customization in 1.14+. Thanks! :)
