### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by GoldenLambMC** [ejektaflex/Bountiful#179]
### What happened?

Unable to set items with data values as a reward (1.12.2)

example: /give minecraft:dye 1 4 [gives 1 Lapis Lazuli]

"content": "minecraft:dye 1 4"

doesn't run and skips over the line

### How can we reproduce it?

try setting a reward to give out an item with a data value like Lapis Lazuli

### Mod Version

Bountiful-2.2.2.jar

### Forge Version

Forge - 14.23.5.2859 [1.12.2]

### Relevant log output

  {
    "content": "minecraft:dye 1 4",
    "unitWorth": 75,
    "weight": 5,
    "amount": {
      "min": 1,
      "max": 40
    }
  }

**Comment by ejektaflex** [comment]
The ID for lapis in 1.12 is `minecraft:dye:4`. So the line should be:
```json
"content": "minecraft:dye:4"
```
Items amounts should not be included in the content. I hope that makes sense!
