### ISSUE TITLE
Where to put decree and pool files?

### ISSUE THREAD

**Issue by oasisismywaifu** [ejektaflex/Bountiful#180]
### What happened?

Hi I'm new to datapacks and I'm trying to use them to make custom pools and decrees. I'm also using the open loader mod (version 9.0.3), and im using curseforge  36.2.34 on minecraft 1.16.5. right now my decree jsons are in modpack/openloader/data/customdatapack/data/bounties/decrees/bountiful. i've made sure to add the right pack.mcmeta, and i see the datapack in the datapack menu when im creating a world. i believe ive made the jsons correctly, ive followed all the directions here, but i dont know where to put them. help would be much appreciated! thanks

### Mod Version

3.3.1

### Forge Version

36.2.34

**Comment by GoldenStag** [comment]
Unsure how openloader works but for without it essentially you just want to recreate the exact same path as the mod after the data folder.

Example:
yourdatapacknamehere/data/bountiful/bounties/decrees/bountiful/

drop your decree json file in there and it should pop up in the world

For the pool json file it should go
yourdatapacknamehere/data/bountiful/bounties/pools/

create a folder, doesn't really matter the name and drop your pool json files in there.

Putting it here to revisit when I eventually forget.

**Comment by ejektaflex** [comment]
Thanks @GoldenStag - that sounds correct!
