### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by ghost** [ejektaflex/Bountiful#181]
### Feature Description

Hello developer, I have some doubts about this mod. My idea is to use this mod with other currency mods to achieve the mechanism of submitting currency for rewards. I don't know if it can achieve my idea through data packets?

My mod version is 1.16.5

My English is not very good, so my sentences may not be very fluent, sorry

### Feature Benefits

Wish the wiki could be more detailed

**Comment by ejektaflex** [comment]
This is now very easy to do using a datapack in v6.0.0+ for Minecraft 1.19.4. 

You can find details here:
https://kambrik.ejekta.io/mods/bountiful/
