### ISSUE TITLE
[Feature]: Update to current MC version

### ISSUE THREAD

**Issue by Developer2704** [ejektaflex/Bountiful#185]
### Feature Description

I think that if you have extra time bountiful should be updated to newer versions or you could reach out to other devs to ask them to update the mod

### Feature Benefits

Bountiful is a great mod and i think it would help more people download it if it was not constrained to 1.16.

**Comment by ejektaflex** [comment]
Hey! I agree. I'm prioritizing the update for Fabric first, but anybody is free to spend their time contributing to this repository, if they wish.

**Comment by ejektaflex** [comment]
It's been done! I just released both Forge and Fabric versions for 1.19.4.
