### ISSUE TITLE
Unlocalized entity names containing colons are marked as invalid entities for bounties

### ISSUE THREAD

**Issue by ejektaflex** [ejektaflex/Bountiful#20]
Adding an entity bounty with an unlocalized name such as `mocreatures:pandabear` seems to be invalid, because an Entity Entry lookup seems to make the assumption that the lookup will only contain one colon as shown [here](https://github.com/ejektaflex/Bountiful/blob/045587cc49cefa9ff1236cf2e9b6cfea01344f8b/src/api/kotlin/ejektaflex/bountiful/api/ext/ExtString.kt#L16).

**Comment by AdaraChristine** [comment]
Ahh so this is why my custom bounties don't work.

**Comment by ejektaflex** [comment]
Perhaps. Did you use "/bo entities" to see what the entity name should be? If the entity name in that list contains a colon, it won't currently work.

I made an assumption that the entity registry's EntityEntries had names that all matched 1:1 with an Entity's name, but it seems that some mod makers defy this assumption (And it's not quite their fault, I don't blame them for using the registry name as the EntityEntry's unlocalized name I suppose....?).

This is a bit tricky to work around right now.

**Comment by ejektaflex** [comment]
Fixed as of bd5903b. @AdaraChristine, for the next version you'll have to provide the entity's registry name instead of it's unlocalized name (`entity:lycanitesmobs:eyewig` instead of `entity:eyewig`). The "`/bo entities`" command now shows these registry names correctly to match.

**Comment by ejektaflex** [comment]
@AdaraChristine This command does also print the output in the log, so you can view it there!

**Comment by AdaraChristine** [comment]
Thanks! Looking forward to adding your mod to Mystical Village 2 upon your update. Hopefully its its this week! :)

**Comment by ejektaflex** [comment]
Probably! The last feature that I really want to add right now is village generation, so expect it sometime later this week.
