### ISSUE TITLE
PSD file is included in the jars - doot3.psd alongside doot3.png.

### ISSUE THREAD

**Issue by K0-RR** [ejektaflex/Bountiful#206]
https://github.com/ejektaflex/Bountiful-Fabric/blob/master/src/main/resources/assets/bountiful/textures/gui/container/doot3.psd
https://github.com/ejektaflex/Bountiful-Fabric/blob/master/src/main/resources/assets/bountiful/textures/gui/container/doot3.png

**Comment by ejektaflex** [comment]
That's fair - I should move these to an art folder.

**Comment by ejektaflex** [comment]
These no longer exist in the 1.19.4+ versions.
