### ISSUE TITLE
[Bug]: Bountiful structures do not generate with Repurposed structures

### ISSUE THREAD

**Issue by PranavSakthivel** [ejektaflex/Bountiful#207]
Loaded up a creative world, tried to go around to 4 or 5 RS villages but could not find a single gazebo. However, there is always a gazebo in a vanilla world. I can provide logs or anything else necessary. Thanks!

Going through past issues it seems like More Villagers or Farmer's Delight may cause issues, but I don't have Farmer's Delight.

Repro steps:
1. Generate world with mods above
2. Use /locate rs:village_x to find custom village
3. Look for bounty board

Mod Version: 2.02
(MultiMC and the logs say it is 2.01 but I redownloaded 2.02 jar multiple times and added it)

Log: https://paste.ee/p/XZDdS

Mods:
  [✔️] AdditionalAdditions-3.0.1
  [✔️] AdvancementPlaques-1.18-fabric-1.4.4
  [✔️] appleskin-fabric-mc1.18.1-2.3.0
  [✔️] arcanus-1.27
  [✔️] architectury-3.7.22
  [✔️] artifacts-6.0.0+fabric
  [✔️] atlantis-2022.2.12-1.18.1-1.1.1-fabric
  [✔️] Autofish-0.9.4-fabric-mc1.18
  [✔️] automated-crafting-1.4.3+MC1.18-1.18.1
  [✔️] AwesomeDungeonEnd-Fabric-1.18.1-1.0.0
  [✔️] AwesomeDungeonFabric-1.18.1-2.0.4
  [✔️] AwesomeDungeonNether-Fabric-1.18.1-1.0.0
  [✔️] AwesomeDungeonOcean-Fabric-1.18-2.0.5
  [✔️] backtools-1.18.1
  [✔️] balm-fabric-2.4.3+0
  [✔️] bclib-1.3.4
  [✔️] BeaconOverhaul-1.5.0+1.18
  [✔️] betteranimalsplus-1.18.1-11.0.4-fabric
  [✔️] BetterControls-Fabric-1.18+v1.2.3
  [✔️] better-end-1.0.2
  [✔️] BetterF3-1.2.2-Fabric-1.18
  [✔️] better-nether-6.0.10
  [✔️] BetterPingDisplay-Fabric-1.18.1-1.1.1
  [✔️] bettersleeping-0.5.1+1.18
  [✔️] BetterStrongholds-Fabric-1.18.1-1.0.1
  [✔️] betterthanmending-1.3.0
  [✔️] BetterThirdPerson-Fabric-1.18-1.6.0
  [✔️] better-wandering-trader-1.8.0
  [✔️] BiomeWeatherEffects-1.3.2
  [✔️] Botania-1.18.1-429-FABRIC
  [✔️] BountifulFabric-2.0.2
  [✔️] BowInfinityFix-1.18.x-fabric-rv11
  [✔️] brb-Fabric-1.5.6
  [✔️] cleancut-1.18-4.0-fabric
  [✔️] clickthrough-1.18-fabric0.43.1-0.4
  [✔️] clienttweaks-fabric-1.18-7.0.1
  [✔️] cloth-config-6.2.57-fabric
  [✔️] collective-fabric-1.18.x-4.9
  [✔️] comforts-fabric-1.0.2-1.18.1
  [✔️] continuity-1.1.0+1.18
  [✔️] Controlling-forge-1.18.1-9.0+15
  [✔️] copper-mod-1.9.1
  [✔️] Couplings-1.7.1+1.18
  [✔️] craftingpad-1.18-rc4-1.0.7
  [✔️] Croptopia-1.18-FABRIC-1.8.1
  [✔️] drinkbeer-v3.0.2+for+1.18.1
  [✔️] DungeonsArise-1.18.1-2.1.49d-fabric-beta
  [✔️] DynamicSoundFilters-1.3.0+1.18
  [✔️] easiervillagertrading-1.18-fabric0.43.1-1.5.4
  [✔️] EasyMagic-v3.2.1-1.18.1-Fabric
  [✔️] EditSign-1.18.1-2.2.7
  [✔️] effective-1.1
  [✔️] emotecraft-for-MC1.18.1-2.1-fabric
  [✔️] EnchantingInfuser-v3.1.1-1.18.1-Fabric
  [✔️] entityculling-fabric-mc1.18-1.5.0
  [✔️] expandedstorage-7.3.6+1.18
  [✔️] ExplorersCompass-1.18.1-2.0.2-fabric
  [✔️] extraalchemy-fabric-1.18.1-1.7.0
  [✔️] Fabric-1.18-SmoothSwapping-0.4.4
  [✔️] fabric-api-0.46.4+1.18
  [✔️] fabric-language-kotlin-1.7.1+kotlin.1.6.10
  [✔️] farmers-delight-fabric-1.18.1-0.2.0
  [✔️] farmingforblockheads-fabric-1.18.1-9.0.3
  [✔️] feature_nbt_deadlock_be_gone_fabric-1.0.1+1.18.1
  [✔️] ferritecore-4.1.2-fabric
  [✔️] flytre_lib-1.18.1-1.7.1-fabric
  [✔️] ForgeConfigAPIPort-v3.1.1-1.18.1-Fabric
  [✔️] forgottenrecipes-fabric-1.18.1-1.0.0
  [✔️] fortune-gives-experience-fabric-1.18-1.1
  [✔️] furnacerecycle-fabric_1.18.x-1.0
  [✔️] geckolib-fabric-1.18.2-3.0.35
  [✔️] goldenhoppers-1.2.0
  [✔️] guardvillagers-1.18.1.4.0
  [✔️] hookshot-r24
  [✔️] Iceberg-1.18.1-fabric-1.0.38
  [✔️] illuminations-1.10.2
  [✔️] illuminations-uninstaller
  [✔️] improved-stations-2.0.8
  [✔️] incantationem-1.1.3+1.18.1
  [✔️] indium-1.0.2-alpha2+mc1.18.1
  [✔️] interactic-0.1.8+1.18
  [✔️] iris-mc1.18.1-1.2.0-pre
  [✔️] Kambrik-3.1.0-1.18
  [✔️] lambdynamiclights-2.1.0+1.17
  [✔️] lazydfu-0.1.2
  [✔️] levelz-1.1.6
  [✔️] LibraryFerret-Fabric-1.18.1-1.0.3
  [✔️] lifts-1.4-BETA+1.18
  [✔️] lithium-fabric-mc1.18.1-0.7.8
  [✔️] mcda-2.0.1
  [✔️] mcdar-1.4.3-1.18
  [✔️] mcdw-4.0.4
  [✔️] medievalweapons-1.1.8
  [✔️] megane-7.1.3
  [✔️] MobCatcher-Fabric-1.18.1-1.1.23
  [✔️] modmenu-3.0.1
  [✔️] mores-1.2.8
  [✔️] morevillagers-FABRIC-1.18.1-3.1.1
  [✔️] MouseTweaks-fabric-mc1.18-2.22
  [✔️] mousewheelie-1.8.0+mc1.18-pre5
  [✔️] NaturesCompass-1.18.1-2.0.2-fabric
  [✔️] netherchest-mc1.18-3.1
  [✔️] ninjaphenix-container-library-1.3.0+1.18-fabric
  [✔️] no_null_processors_fabric-2.0.1+1.18.1
  [✔️] NoChatLag-1.1.0
  [✔️] notenoughanimations-fabric-1.4.0-mc1.18-pre1
  [✔️] notenoughcrashes-4.1.4+1.18.1-fabric
  [✔️] npc-variety-1.18-2.2.2
  [✔️] okzoomer-5.0.0-beta.3+1.17.1
  [✔️] Patchouli-1.18.1-65-FABRIC
  [✔️] pettable-1.2.1
  [✔️] phosphor-fabric-mc1.18.x-0.8.1
  [✔️] PickUpNotifier-v3.1.0-1.18.1-Fabric
  [✔️] pipe-1.18-1.6.2
  [✔️] pluckablearrows-1.2.3
  [✔️] polymorph-fabric-0.0.19-1.18.1
  [✔️] PresenceFootsteps-1.4.0
  [✔️] PuzzlesLib-v3.2.0-1.18.1-Fabric
  [✔️] quarry-reborn-1.18-0.5.5
  [✔️] rangers_haven-1.18.1-2.3.1
  [✔️] repurposed_structures_fabric-3.3.12+1.18.1
  [✔️] rocks-1.5.2
  [✔️] RoughlyEnoughItems-7.3.432
  [✔️] rpgz-0.4.11
  [✔️] ruined-equipment-1.4.0
  [✔️] saplanting-fabric-1.18-1.0
  [✔️] skeletonfix-1.1.1+1.18
  [✔️] smoothboot-fabric-1.18-1.7.0
  [✔️] sodium-extra-mc1.18.1-0.4.0
  [✔️] sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14
  [✔️] stoneholm-1.4.2
  [✔️] TechReborn-5.1.0
  [✔️] Terralith_v2.0.12_Fabric+Forge
  [✔️] time-in-a-bottle-1.6-mc1.17-fabric
  [✔️] totw_additions-1.1.0-1.18.1-fabric
  [✔️] towers_of_the_wild_reworked-2.1.1
  [✔️] trade-cycling-fabric-1.18.1-1.0.2
  [✔️] TradingPost-v3.1.2-1.18.1-Fabric
  [✔️] transportables-1.1
  [✔️] travelers-backpack-1.18.1-7.0.0
  [✔️] trinkets-3.2.0
  [✔️] villagernames-1.18.1-3.0.3
  [✔️] visuality-0.4.1
  [✔️] VisualWorkbench-v3.1.0-1.18.1-Fabric
  [✔️] whats-that-slot-fabric-1.2.3+1.18.1
  [✔️] wraith-waystones-2.4.1
  [✔️] wthit-fabric-4.5.2
  [✔️] Xaeros_Minimap_22.2.0.1_Fabric_1.18
  [✔️] XaerosWorldMap_1.20.3.1_Fabric_1.18
  [✔️] xp_storage-1.4.3+1.18
  [✔️] YungsApi-1.18-Fabric-36

**Comment by Gilithrimm** [comment]
I know t[here's a datapack](https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-bountiful-datapack-compat) for this
I hope it helps

**Comment by ejektaflex** [comment]
Yes, TelepathicGrunt has added a datapack for this, which you can find here:
https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-bountiful-datapack-compat
https://modrinth.com/datapack/repurposed-structures-bountiful-compat
