### ISSUE TITLE
[Bug]: Items don't show up in REI/JEI in 1.19.4

### ISSUE THREAD

**Issue by flungip** [ejektaflex/Bountiful#229]
### What happened?

i added it to my server and everytime i look it up in jei it doesnt exist or the creative menu ether 

### How can we reproduce it?

i dont know what this mean tbh lol

### Mod Version

 Bountiful-6.0.0-beta.3+1.19.4-forge.jar

### Mod Loader

Forge

### Mod Loader Version

1.19.4

### Relevant log output

theres no logs cause it doesnt know it exist or something

**Comment by ejektaflex** [comment]
Did you install it on the client as well?

With some rare exceptions, almost every mod that adds content to the game is required to have the same mods installed on the client too!

**Comment by flungip** [comment]
yeah i made the mod pack all on the client then added it to the server

**Comment by ejektaflex** [comment]
Ah - I might not have added the items to the new item group alternative in this version yet - you should still be able to spawn a board with `/give [yourname] bountiful:bountyboard 1` :)

**Comment by flungip** [comment]
that was the issue thanks

**Comment by ejektaflex** [comment]
I just got another report that this was still happening in 1.20.1. When attempting to reproduce this, mod items notably do show up using REI but not using JEI. I have a feeling that JEI might only pull items that are registered with an item group, which might make a good amount of sense.

**Comment by ejektaflex** [comment]
This was fixed in 6bc7c2f by implementing item groups. It will be included in the next version (presumably 6.0.3+)!
