### ISSUE TITLE
[Bug]: Russian language typo for decree

### ISSUE THREAD

**Issue by ghost** [ejektaflex/Bountiful#231]
### What happened?

For decree "Картографа" there is a word "Картографая" which makes no sense. So "Картографа" is right spelling

### Mod Version

BountifulFabric-4.1.1-1.19.3.jar

### Mod Loader

None

### Mod Loader Version

0.14.19

**Comment by ejektaflex** [comment]
Hi! We have CrowdIn, so that people can contribute towards translations - if I don't get to it soon, feel free.
https://crowdin.com/project/bountiful

**Comment by ghost** [comment]
Thank you, I've done this. Hope this'll help

**Comment by ghost** [comment]
But I kinda translated almost everything
