### ISSUE TITLE
[Bug]: Crash while loading the mod in a modpack

### ISSUE THREAD

**Issue by Samy8z** [ejektaflex/Bountiful#253]
### What happened?

After a quick time of loading, the game crash and says bountiful failed load, I'm using it in a modpack with curseforge. Looks like it's crashing for idk what reason.  Modlist (Can also be found in crash report) :

>

[Inoxia Temporis-V1.zip](https://github.com/ejektaflex/Bountiful/files/12860908/Inoxia.Temporis-V1.zip)

### How can we reproduce it?

Just start the game with bountiful and the modlist.

### Mod Version

6.0.3

### Mod Loader

Forge

### Mod Loader Version

Forge 47.1.43

### Relevant log output

[crash-2023-10-10_21.06.48-fml.txt](https://github.com/ejektaflex/Bountiful/files/12861009/crash-2023-10-10_21.06.48-fml.txt)

**Comment by ejektaflex** [comment]
Thanks!
This doesn't happen every time you load the game, does it?
Interestingly, this is not code that I'm directly calling, so it's a bit difficult to diagnose. It seems that Minecraft's code itself is running into the concurrent modification exception when I register the dynamic item textures. The solution may be as easy as changing the timing of the texture registration.

**Comment by Samy8z** [comment]
Sometimes it does, sometimes it doesn't really weird situation. I've tried changing Forge Version but I'm not sure it fix anything. Sometimes I fix it by deleting the .jar file and downloading it again. Or we just completely redownload the custom profile. Oh and btw we're like 20 on the server and it doesn't happen to everyone

**Comment by ejektaflex** [comment]
That's what I figured. Concurrent modification exceptions usually are not guaranteed to crash every time. Luckily, this only seems to happen on startup, so restarting the game until it launches successfully is probably the best thing you can do right now.

I'm still on vacation until the end of this month, but I'll be looking into a fix once I get back. Thanks!

**Comment by Samy8z** [comment]
No problem, enjoy your vacation!

**Comment by ejektaflex** [comment]
This should be fixed in a36e945 and will be present in Bountiful 7.0.0 - it won't be making it's way back to older versions. Since not a whole lot of mods use item properties with dynamic textures, I don't think this will affect a large number of people (it just happened to be used in a very large modpack where the number of mods doing this is higher, so we clashed).
