### ISSUE TITLE
[Bug]: Not working correctly with Cadmus/Prometheus Mod (Fabric 1.20.1)

### ISSUE THREAD

**Issue by ItsCliffGaming** [ejektaflex/Bountiful#255]
### What happened?

When using Cadmus / Prometheus - if the Bounty Board is inside of a Claim it cannot be interacted with. Even with the flags for all interactions set to true (use true, use-chests true, block-interactions true, entity-interactions true, use-blocks true). When placed outside of a claim it works just fine, though.

### How can we reproduce it?

Place a Bounty Board inside of an Admin Claim

### Mod Version

Bountiful 6.0.3+1.20.1-Fabric

### Mod Loader

Fabric

### Mod Loader Version

0.14.23

**Comment by ejektaflex** [comment]
This doesn't sound like Bountiful's problem to solve - Rather, if Cadmus is modifying game code to enforce claims, then it's their responsibility to make it work the way they intend. We're just using the basic interaction code that any other block entity would be using to open a GUI / turn in a bounty.

I would report this issue on their issue tracker instead:
https://github.com/terrarium-earth/Cadmus/issues

If they have any advice for how I can handle my bounty board block interactions in a way that's easier for them to hook via Mixins (I assume that's how they do it), then I'm willing to change my code to do so, but as it stands this is a bug with Cadmus' implementation and not an inherent flaw with how Bountiful works.

Thanks for the report!

**Comment by ItsCliffGaming** [comment]
Thank you for the prompt response. I will do that now.
