### ISSUE TITLE
[Bug]: Crash upon world creation when using the mod with Lithium

### ISSUE THREAD

**Issue by mapokapo** [ejektaflex/Bountiful#268]
### What happened?

Upon world creation using the Lithium and Bountiful mods, Lithium will throw many errors due to some sort of mixin issue. When the world generation process reaches 100%, the game crashes.

### How can we reproduce it?

I have successfully reproduced the issue with the following mods enabled:
- **Fabric API** (_fabric-api-0.96.4+1.20.4_)
- **Lithium** (_lithium-fabric-mc1.20.4-0.12.1_)
- **Bountiful** (_Bountiful-7.0.1+1.20.4-fabric_)
- **Kambrik** (_Kambrik-7.0.0+1.20.4-fabric_)

All mods were downloaded from Modrinth.
Once the game is successfully started, proceeding to create a new singleplayer world will crash once the loading progress bar reaches 100%.

Specifications:
- Windows 10 IoT LTSC
- OpenJDK 17
- 8GB of RAM (out of a total of 16GB)
- The latest Prism launcher
- Fabric Loader 0.15.7
- Fabric API 0.96.4+1.20.4
- Aikar's Java flags with no modifications

### Mod Version

Bountiful-7.0.1+1.20.4-fabric

### Mod Loader

Fabric

### Mod Loader Version

fabric-api-0.96.4+1.20.4

### Relevant log output

Log file of crash:
[latest.log](https://github.com/ejektaflex/Bountiful/files/14469861/latest.log)

**Comment by ejektaflex** [comment]
Hi @mapokapo! Thanks for the report. The log that you've provided does not indicate that this is a problem with Bountiful, although I can reproduce it. Note that Lithium is a very mixin-invasive mod and it's their onus to try and remain a drop-in replacement for Minecraft's default ~renderer~ server code. I see no mixin conflicts, and Bountiful doesn't do any fancy rendering, especially on world load, so this should be reported on Lithium's issue tracker instead.

**Comment by ejektaflex** [comment]
Actually, there's a chance of conflict here - Lithium is mixing into entity brains, which Bountiful also does. It seems like Bountiful might be elevating a field to public, and Lithium is trying to access it with reduced visibility? I will investigate.

**Comment by ejektaflex** [comment]
Ha, turns out it was because of a field we changed visibility on, but no longer access. I removed it and updated the Fabric releases to version 7.0.2. It's out on Modrinth and will soon be approved on CurseForge as well.

Enjoy!
