### ISSUE TITLE
[Bug]: Bounty board recipe only accepts oak wood

### ISSUE THREAD

**Issue by cuberyl-catastrophe** [ejektaflex/Bountiful#271]
### What happened?

The bounty board recipe only accepts oak wood.

### How can we reproduce it?

Try to craft the bounty board with any other wood. It won't work.

### Mod Version

6.0.3

### Mod Loader

Forge

### Mod Loader Version

47.2.20

**Comment by ejektaflex** [comment]
Hi @cubebotfan ! Unfortunately, this isn't a bug. Oak wood planks are the intended way of crafting a bounty board. If you'd like to add an alternate recipe, feel free to use something like KubeJS or CraftTweaker!
