### ISSUE TITLE
[Bug, 1.20.1]: Items held in cursor when closing bounty board UI voided

### ISSUE THREAD

**Issue by Chakyl** [ejektaflex/Bountiful#279]
### What happened?

Issue in the bounty board UI causing items held in hand to void whenever closing instead of returning to inventory

### How can we reproduce it?

1. Open bounty board
2. Left click item in your inventory to hold
3. Press e/esc. It reliably voids the held item every single time 

Video:

![Recording2024-04-29002533-ezgif com-video-to-gif-converter](https://github.com/ejektaflex/Bountiful/assets/2364840/4fb6540f-804a-4add-8642-b614e32f0bbd)

### Mod Version

6.0.3

### Mod Loader

Forge

### Mod Loader Version

47.2.30

**Comment by ejektaflex** [comment]
Fixed in [f17f587](https://github.com/ejektaflex/Bountiful/commit/f17f587c5423edabe413f51c7d377b2bd6ae26ed). Will come to the last update for 1.20.4. :)
