### ISSUE TITLE
[Bug]: With few rewards, unitWorth is far from expected

### ISSUE THREAD

**Issue by LTCatt** [ejektaflex/Bountiful#287]
### What happened?

![image](https://github.com/ejektaflex/Bountiful/assets/40348278/18541bd5-9f99-449e-bf53-9d6231c41761)
![image](https://github.com/ejektaflex/Bountiful/assets/40348278/a17a67d8-6a3e-4635-85be-7ebbd0b2e2d8)

They have same unitWorth.

### How can we reproduce it?

[emerald_reward.json](https://github.com/user-attachments/files/15759435/emerald_reward.json)
[emerald.json](https://github.com/user-attachments/files/15759437/emerald.json)
https://discord.com/channels/687015972892311563/687016154702807064/1249389874373591080

### Mod Version

6.0.3-1.20.1

### Mod Loader

Forge

### Mod Loader Version

47.2.23

**Comment by ejektaflex** [comment]
Fixed in 6.0.4-1.20.1!
