### ISSUE TITLE
[Bug]: Error and Exit Code: -1 due to bountiful

### ISSUE THREAD

**Issue by Valentara** [ejektaflex/Bountiful#292]
### What happened?

Mod installed on Rlcraft, have played the game no problem, around 60 hours with it installed, then this morning game was a little buggy, closed computer/game for a break, came back this afternoon and when game was launching it crashed, and received the message:
Error: net.minecraftforg.fml.common.loaderExceptionModCrash: Caught exception from Bountiful (bounfiful)
Exit code: -1 

### How can we reproduce it?

not sure, went to launch game like normal and this started happening.

### Mod Version

Bountiful-1.12.2-2.2.3

### Mod Loader

Forge

### Mod Loader Version

14.23.5.2860

### Relevant log output

[crash-2024-07-29_16.53.24-client.txt](https://github.com/user-attachments/files/16419174/crash-2024-07-29_16.53.24-client.txt)

**Comment by ejektaflex** [comment]
It says this in your crash log:
```text
Caused by: java.lang.Exception: 'bountiful/rewards.json' contains one or more invalid rewards. Invalid rewards: [PickedEntry (Stack) [Item: rlmixins:cleansing_talisman, Amount: 750, NBT: null, Weight: 50, Stages: null]]
```
Your modpack's bountiful config contains an item (`rlmixins:cleansing_talisman`) which no longer exists (perhaps you removed the mod?). Removing this entry from your config will fix it.
