### ISSUE TITLE
[Bug]: Cannot edit emerald

### ISSUE THREAD

**Issue by MasterNotlucky** [ejektaflex/Bountiful#294]
### What happened?

I am not able to edit the objective for emeralds. I can add another objective, but there is another one that i cant edit?

Like I put min 64, and max 64. But its still showing sometimes 2 emeralds or 1 digit amounts. idk if im stupit or what.

### Mod Version

6.0.3

### Mod Loader

Forge

### Mod Loader Version

47.3.1

### Relevant log output

{
    "content": {
        "earn_spur": {
            "type": "item",
            "content": "numismatics:spur",
            "amount": {
                "min": 1,
                "max": 2
            },
            "unitWorth": 300,
            "rarity": "UNCOMMON",
            "timeMult": 1,
            "repRequired": 4
        },
        "earn_diamond": {
            "type": "item",
            "content": "minecraft:diamond",
            "amount": {
                "min": 32,
                "max": 44
            },
            "unitWorth": 430,
            "rarity": "RARE",
            "timeMult": 1.0
        },
        "earn_iron": {
            "type": "item",
            "content": "minecraft:iron_ingot",
            "amount": {
                "min": 58,
                "max": 79
            },
            "unitWorth": 360,
            "rarity": "COMMON",
            "timeMult": 1.0
        },
        "earn_dirt": {
            "type": "item",
            "content": "minecraft:dirt",
            "amount": {
                "min": 32,
                "max": 128
            },
            "unitWorth": 1,
            "rarity": "COMMON",
            "timeMult": 1.0
        },
        "earn_emerald": {
            "type": "item",
            "content": "minecraft:emerald",
            "amount": {
                "min": 64,
                "max": 128
            },
            "unitWorth": 35,
            "rarity": "COMMON",
            "timeMult": 1.0
        },
        "earn_sugarcane": {
            "type": "item",
            "content": "minecraft:sugar_cane",
            "amount": {
                "min": 5,
                "max": 32
			},
            "unitWorth": 75,
            "rarity": "COMMON",
            "timeMult": 1.0
        },
        "earn_ironblock": {
            "type": "item",
            "content": "minecraft:iron_block",
            "amount": {
                "min": 8,
                "max": 12
            },
            "unitWorth": 400,
            "rarity": "RARE"
        },
        "earn_book": {
            "type": "item",
            "content": "minecraft:book",
            "amount": {
                "min": 48,
                "max": 64
            },
            "unitWorth": 500,
            "rarity": "UNCOMMON"
        },
        "earn_stone_bricks": {
            "type": "item",
            "content": "minecraft:stone_bricks",
            "amount": {
                "min": 64,
                "max": 128
            },
            "unitWorth": 40,
            "rarity": "COMMON"
        },
        "earn_copper_ingot": {
            "type": "item",
            "content": "minecraft:copper_ingot",
            "amount": {
                "min": 25,
                "max": 48
            },
            "unitWorth": 85,
            "rarity": "UNCOMMON"
        },
        "earn_gold_ingot": {
            "type": "item",
            "content": "minecraft:gold_ingot",
            "amount": {
                "min": 9,
                "max": 27
            },
            "unitWorth": 55,
            "rarity": "COMMON"
        },
        "earn_stick": {
            "type": "item",
            "content": "minecraft:stick",
            "amount": {
                "min": 32,
                "max": 64
            },
            "unitWorth": 2,
            "rarity": "COMMON"
        },
        "earn_anvil": {
            "type": "item",
            "content": "minecraft:anvil",
            "amount": {
                "min": 1,
                "max": 3
            },
            "unitWorth": 450,
            "rarity": "RARE"
        },
        "kill_troll": {
            "type": "entity",
            "content": "iceandfire:troll",
            "unitWorth": 1000,
            "rarity": "EPIC"
        },
        "cog_reward": {
            "type": "item",
            "content": "numismatics:cog",
            "amount": {
                "min": 1,
                "max": 4
            },
            "unitWorth": 12000,
            "rarity": "EPIC",
            "forbids": [
                {
                    "type": "item",
                    "content": "minecraft:dirt"
                },
                {
                    "type": "item",
                    "content": "minecraft:emerald"
                },
                {
                    "type": "item",
                    "content": "minecraft:stick"
                },
                {
                    "type": "item",
                    "content": "minecraft:stone_bricks"
                },
                {
                    "type": "item",
                    "content": "minecraft:planks"
                }
            ]
        }
    }
}

**Comment by ejektaflex** [comment]
Do you mean the objectives for emeralds that already exist in default Bountiful? If so, you just create a pool with the same name as those objectives and set their content key to null, as shown [in the wiki](https://kambrik.ejekta.io/mods/bountiful/1-20-1/FileStructure#removing-content). :^)

**Comment by MasterNotlucky** [comment]
I made a severe and continuous lapse in my judgement...
