### ISSUE TITLE
[Bug]:  Missing language

### ISSUE THREAD

**Issue by nmundo2** [ejektaflex/Bountiful#303]
### What happened?

Hello, I am writing because I put your mod on the server and I get this error: Missing language

22:03:21] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 8 dependencies adding them to mods collection
[22:03:21] [main/ERROR] [ne.mi.fm.lo.LanguageLoadingProvider/LOADING]: Missing language kotlinforforge version [4,) wanted by Bountiful-6.0.3+1.20.1-forge.jar
[22:03:23] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments []
[22:03:29] [main/FATAL] [ne.mi.fm.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod File Bountiful-6.0.3+1.20.1-forge.jar needs language provider kotlinforforge:4 or above to load
§7We have found none

### Mod Version

1.20.1

### Mod Loader

Forge

### Mod Loader Version

Bountiful-6.0.3+1.20.1-forge.jar

**Comment by ejektaflex** [comment]
You need Kotlin for Forge additionally to run this mod - it should be listed in the dependencies on the mod page. That mod specifically it can be finicky with alerting people about when it's not present because of the way that it works. Thanks :^)

**Comment by nmundo2** [comment]
I didn't know because on the page it says that I didn't have dependence

![image_2024-11-30_192313487](https://github.com/user-attachments/assets/26cd901d-463d-415c-9ae3-a7358f05eb2e)

**Comment by nmundo2** [comment]
But thanks 👍
