### ISSUE TITLE
[Bug]: Multiple Bounty Boards Per Village

### ISSUE THREAD

**Issue by laxlacks888** [ejektaflex/Bountiful#304]
### What happened?

I have Better Villages installed and each village will have 5-9 bounty boards, even with the boardGenFrequency set 1.  Remove Better Villages and 1 board per village.

### How can we reproduce it?

Install both Better Villages and Bountiful, Forge 1.20.1 47.2.30

### Mod Version

6.0.4-1.20.1

### Mod Loader

Forge

### Mod Loader Version

47.2.30

**Comment by ejektaflex** [comment]
This is a problem with the village piece weighting in Better Villages. You should use something like this (created by the author of Better Villages) to fix it :^)
https://www.curseforge.com/minecraft/texture-packs/better-villages-bountiful

**Comment by laxlacks888** [comment]
Thank you :)
