### ISSUE TITLE
[Bug]: (1.20.1) Editing the Bounty config does not add the bounty to the bounty board

### ISSUE THREAD

**Issue by Lampent51** [ejektaflex/Bountiful#305]
### What happened?

I tried to edit the config to add a bounty to the bounty board, but none of it shows up from what I've checked. 

### How can we reproduce it?

After adding the new "_all_objs.json" to the config and loading the server, nothing new appears on the bounty board.

### Mod Version

6.0.4

### Mod Loader

Forge

### Mod Loader Version

Neoforge 47.1.106 (1.20.1)

### Relevant log output

{
	"content": {
		"jasper_obj": {
			"type": "item",
			"content": "quark:jasper",
			"amount": {
				"min": 16,
				"max": 64
			},
			"unitWorth": 20,
			"weightMult": 4
		},

	}

}

**Comment by ejektaflex** [comment]
It could be a lot of things. Are you sure that the file is located at `config/bountiful/bounty_pools/_all_rews.json`?
Also, the end of your code comment seems broken, but you might have an incorrect number of closing brackets, or a trailing comma (a comma with no new entries after it).

Feel free to hop over to the [Discussions page](https://github.com/ejektaflex/Bountiful/discussions) and use the Discord link if you'd like help a bit faster. :^)
Thanks!

**Comment by Lampent51** [comment]
Thank you for the fast response! Currently it's at `config\bountiful\bounty_pools\_all_objs.json`

I've copy and pasted the code from the wiki, making the edit with quark:jasper, so I hope it wouldn't be a code error.

To make the issue less complex, I've trimmed the modpack to only these mods on a separate instance: 
Quark 4.0-460
Zeta 1.0-24 (quark library)
JEI 15.20.0.105
Kotlin for Forge 4.11.0
Kambrik 6.1.1+1.20.1

**Comment by Lampent51** [comment]
It was the trailing comma... I didn't realize that's what it meant, but yes that was the problem. Thank you, sorry for the simple error.

**Comment by ejektaflex** [comment]
@Lampent51 , don't worry, it's all good! Recently, KotlinX Serialization actually added the ability to ignore trailing commas, even though it's invalid syntax. So in 1.20.4 and beyond this would not have even been an error ;) I'm glad we figured it out! Thanks for enjoying the mod :^)
