### ISSUE TITLE
unable to change reward from gold to other item 

### ISSUE THREAD

**Issue by vampwolf28** [ejektaflex/Bountiful#31]

**Comment by ejektaflex** [comment]
Which version of Bountiful is this? @vampwolf28

**Comment by vampwolf28** [comment]
newest one

**Comment by ejektaflex** [comment]
I'm fairly certain that you were using an older version, but didn't update it correctly. Delete your `bounties.json` and `rewards.json` and then run the game so that they can reset themselves. Then try modify the files, save them and run `/bo reload`.

**Comment by vampwolf28** [comment]
[
  {
    "itemString":"minecraft:emerald",
    "unitWorth":2000
  },
  {
    "itemString":"minecraft:diamond",
    "unitWorth":500
  }
]

did that
 still getting gold bounty

**Comment by ejektaflex** [comment]
Did it say that the config files reloaded, or did it state that there was an error? And are you *sure* that you saved the file? There's no way that it would still be showing gold bounties, so you've done something wrong. If you don't provide any more information, there's no way I can help you!

**Comment by vampwolf28** [comment]
so i did do the "/bo reload " and it does say Json config flies reloaded and i made sure i've save the files

**Comment by vampwolf28** [comment]
![image](https://user-images.githubusercontent.com/47279656/52172015-0bad8700-271c-11e9-8fe0-6f8bec168ec6.png)

**Comment by ejektaflex** [comment]
Wait wait. You didn't delete those files, or you copy pasted old data into your new file. Your key is still `itemString` and not `content` so I know you are still using out of data JSON data.

Proof that v2.1 uses `content` and not `itemString`:
https://github.com/ejektaflex/Bountiful/blob/b8a5c383bbc1b1e13267322f042fed12450179a4/src/api/kotlin/ejektaflex/bountiful/api/logic/pickable/PickedEntry.kt#L7

It's a bit odd that it wouldn't be causing any errors, but try that.

**Comment by vampwolf28** [comment]
so i did that, and i'm still getting gold 
maybe i'm in the wrong flie? i go to assets/bountiful/content/rewards.json and thats where i've been changing my flies at

**Comment by ejektaflex** [comment]
You're in the wrong file, you need to be editing `config/bountiful/rewards.json` inside of your main instance location (That's the location I mentioned in the original post on CurseForge). All of the stuff in the assets folder is hardcoded into the mod (Although it is unused and should be deleted, so this is a good reminder).

**Comment by vampwolf28** [comment]
I'M A BIG DUMB IDIOT!!!! thank you sooo much, i feel so bad that you have to good through all the stuff only because i had the wrong file thank you again.

**Comment by ejektaflex** [comment]
You're welcome. I hope you enjoy using Bountiful :^)
