### ISSUE TITLE
[Suggestion] Have /bo entities print to a file instead of in chat.

### ISSUE THREAD

**Issue by katubug** [ejektaflex/Bountiful#37]
Firstly, thank you for the wonderful mod! I'm having a lot of fun with it. And your documentation is wonderfully thorough.

I'm customizing the bounties, and I'm so glad you included the /bo entities command, as it makes my life much easier. However, what would be great is if it could print to a text file with line breaks, rather than all clumped up in chat. Not sure if that's possible, but I thought I'd suggest it!

In any case, thanks for your time! :)

**Comment by ejektaflex** [comment]
This is a good idea - I'm going to keep it up as an enhancement. For now, though, you can retrieve the game log and easily grab specific data from there. I understand the utility in having this print to it's own file, though, and will probably implement this in a future update!

**Comment by ejektaflex** [comment]
Implemented for v3.1.0 as of 2bd12e8. Typing `/bo entities` will now output a list of entities to `[your modpack]/logs/bountiful.log`.
