### ISSUE TITLE
Having trouble with configuring monster kill goal.

### ISSUE THREAD

**Issue by mactso** [ejektaflex/Bountiful#40]
We are running a Magiculture 2 - 0.6.0.5 server.  
Minecraft version 1.12.2. 
Bountiful-2.2.0.jar

Magiculture has focused Bountiful on food rewards but we saw on Vallon's "Bit by Bit" that it could be set up for killing monsters.   Looking at your wiki, it seemed pretty straightforward but when i set it up as follows

      {
      "content": "minecraft:Skeleton",
      "amount": {
        "min": 1,
        "max": 3
      },
      "unitWorth": 800,
      "weight": 150
    },
      {
      "content": "thaumcraft:wisp",
      "amount": {
        "min": 1,
        "max": 3
      },
      "unitWorth": 800,
      "weight": 150
    },

and do a /bo reload- it says (in red)

Invalid bounty: minecraft:skeleton. Reverting to original data.
Invalid bounty: thaumcraft:wisp. Reverting to original data.

Am I not on a version that supports this feature?
Or is the syntax different for monster kill quests?

Thanks!

**Comment by ejektaflex** [comment]
It needs to be `entity:minecraft:skeleton`, as stated in [the wiki](https://github.com/ejektaflex/Bountiful/wiki/Customizing-Bounty-Objectives).

I hope that helps!

**Comment by mactso** [comment]
Very helpful.  Don't know how I missed it!

Thank you!
