### ISSUE TITLE
Server Crash 2.2.0

### ISSUE THREAD

**Issue by Desoroxxx** [ejektaflex/Bountiful#45]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (AdChimneys-1.12.2-3.5.0.0-build.0353.jar)
  HCASM (HammerCore-1.12.2-2.0.4.7.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  LoadingPlugin (AdPother.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  LittlePatchingLoader (LittleTiles.jar)
  FirstAid CoreMod (firstaid-core-1.6.3.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.4.10.6.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CreativePatchingLoader (CreativeCore.jar)
  CorePlugin (ForgeEndertech.jar)
  RandomPatches (randompatches.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 07/06/19 12:09
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Bountiful (bountiful)
Caused by: java.lang.Exception: JSON Structure of 'bounties.json' is incorrect! Reverting to previous data. Details: com.google.gson.stream.MalformedJsonException: Expected value at line 65 column 3 path $[7]
	at ejektaflex.bountiful.config.BountifulIO.hotReload(BountifulIO.kt:94)
	at ejektaflex.bountiful.config.BountifulIO.hotReloadBounties(BountifulIO.kt:100)
	at ejektaflex.bountiful.proxy.CommonProxy.postInit(CommonProxy.kt:90)
	at ejektaflex.bountiful.Bountiful.postInit(Bountiful.kt:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.14.82-mtxserv-version1
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1484783616 bytes (1416 MB) / 2147483648 bytes (2048 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 18 total; -Xms2048M -Xmx4096M -XX:MaxMetaspaceSize=512M -XX:+UseFastAccessorMethods -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:MaxGCPauseMillis=100 -XX:+ParallelRefProcEnabled -XX:ParallelGCThreads=3 -XX:ConcGCThreads=1 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=60 -XX:UseSSE=4 -XX:+UseNUMA
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 82 mods loaded, 82 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                            | Version                  | Source                                             | Signature                                |
	|:------ |:----------------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| UCHIJ  | minecraft                     | 1.12.2                   | minecraft.jar                                      | None                                     |
	| UCHIJ  | mcp                           | 9.42                     | minecraft.jar                                      | None                                     |
	| UCHIJ  | FML                           | 8.0.99.99                | minecraft_server.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | forge                         | 14.23.5.2768             | minecraft_server.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | creativecoredummy             | 1.0.0                    | minecraft.jar                                      | None                                     |
	| UCHIJ  | littletilescore               | 1.0.0                    | minecraft.jar                                      | None                                     |
	| UCHIJ  | openmodscore                  | 0.12.2                   | minecraft.jar                                      | None                                     |
	| UCHIJ  | obfuscate                     | 0.2.6                    | minecraft.jar                                      | None                                     |
	| UCHIJ  | firstaidcore                  | 1.0.0                    | minecraft.jar                                      | None                                     |
	| UCHIJ  | dsurroundcore                 |                          | minecraft.jar                                      | None                                     |
	| UCHIJ  | randompatches                 | 1.12.2-1.15.0.2          | randompatches.jar                                  | None                                     |
	| UCHIJ  | itemblacklist                 | 1.4.1                    | ItemBlacklist-1.4.1.jar                            | None                                     |
	| UCHIJ  | additionalcompression         | 3.3                      | AdditionalCompression.jar                          | None                                     |
	| UCHIJ  | forgeendertech                | 1.12.2-4.4.20.0          | ForgeEndertech.jar                                 | None                                     |
	| UCHIJ  | adpother                      | 1.12.2-1.0.15.0          | AdPother.jar                                       | None                                     |
	| UCHIJ  | alesiamod                     | 1.1.4                    | Alesia Mod 1.1.4.jar                               | None                                     |
	| UCHIJ  | athenaeum                     | 1.12.2-1.16.0-1-g05e9939 | athenaeum-1.12.2-1.16.0.jar                        | None                                     |
	| UCHIJ  | bottledmilk                   | 1.0.0                    | BottledMilk-1.12-1.1.0.jar                         | None                                     |
	| UCHIJ  | forgelin                      | 1.8.2                    | Forgelin-1.8.2.jar                                 | None                                     |
	| UCHIEE | bountiful                     | 2.2.0                    | Bountiful-2.2.0.jar                                | None                                     |
	| UCHI   | breadbox                      | 1.2.1                    | BreadBox-1.12.2-1.2.1.jar                          | None                                     |
	| UCHI   | chameleon                     | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                           | None                                     |
	| UCHI   | clothingmodbetav04bytitoo8899 | v.0.4                    | Clothing.jar                                       | None                                     |
	| UCHI   | codechickenlib                | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHI   | redstoneflux                  | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | cofhcore                      | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar             | None                                     |
	| UCHI   | cofhworld                     | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | colouredchat                  | 0.3.0-beta               | colouredchat-1.12.2-0.3.0-beta.jar                 | None                                     |
	| UCHI   | cookingforblockheads          | 6.4.69                   | CookingForBlockheads_1.12.2-6.4.69.jar             | None                                     |
	| UCHI   | cosmeticbeds                  | 1.12.2-1.0.2.2           | cosmeticbeds-1.12.2-1.0.2.2.jar                    | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHI   | craftstudioapi                | 1.0.0                    | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| UCHI   | creativecore                  | 1.9.9                    | CreativeCore.jar                                   | None                                     |
	| UCHI   | customnpcs                    | 1.12                     | Customnpc.jar                                      | None                                     |
	| UCHI   | cdm                           | 0.4.1                    | device-mod-0.4.1-1.12.2.jar                        | None                                     |
	| UCHI   | df-roads                      | 1.5.2-mc1.12.2           | df-roads-1.5.2-mc1.12.2.jar                        | None                                     |
	| UCHI   | discordinvite                 | 1.0.4                    | discordinvite.jar                                  | None                                     |
	| UCHI   | drugs_mod                     | 1.0.0                    | Drugzmod.jar                                       | None                                     |
	| UCHI   | dynamictrees                  | 1.12.2-0.9.4             | DynamicTrees.jar                                   | None                                     |
	| UCHI   | fastleafdecay                 | v14                      | FastLeafDecay-v14.jar                              | None                                     |
	| UCHI   | foodexpansion                 | 1.3                      | FoodExpansion1.3.3-1.12.2.jar                      | None                                     |
	| UCHI   | cfm                           | 6.3.0                    | furniture-6.3.0-1.12.2.jar                         | None                                     |
	| UCHI   | cgm                           | 0.12.1                   | guns.jar                                           | None                                     |
	| UCHI   | hammercore                    | 2.0.4.7                  | HammerCore-1.12.2-2.0.4.7.jar                      | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHI   | hidenames                     | 1.4                      | HideNames-1.12-1.4.jar                             | None                                     |
	| UCHI   | ironbackpacks                 | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                  | None                                     |
	| UCHI   | lagbgonreborn                 | 1.0.4                    | lagbgonreborn-1.0.4.jar                            | None                                     |
	| UCHI   | littletiles                   | 1.5.0                    | LittleTiles.jar                                    | None                                     |
	| UCHI   | malisiscore                   | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                       | None                                     |
	| UCHI   | malisisdoors                  | 1.12.2-7.3.0             | malisisdoors.jar                                   | None                                     |
	| UCHI   | mcjtylib_ng                   | 2.6.5                    | mcjtylib-1.12-2.6.5.jar                            | None                                     |
	| UCHI   | currency                      | 3.1.5                    | NeverEnoughCurrency-4.0.1.jar                      | None                                     |
	| UCHI   | nospawnzone                   | 1.12.2.1.3               | NoSpawnZone-1.12.2.1.3.jar                         | None                                     |
	| UCHI   | openmods                      | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHI   | openblocks                    | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHI   | p455w0rdslib                  | 2.0.36                   | p455w0rdslib-1.12.2-2.0.36.jar                     | None                                     |
	| UCHI   | pizzacraft                    | 1.4.1                    | PizzaCraft-1.12.2-1.4.1.jar                        | None                                     |
	| UCHI   | pneumaticcraft                | 1.12.2-0.11.1-361        | pneumaticcraft-repressurized.jar                   | None                                     |
	| UCHI   | realserene                    | 1.4.3                    | realserene-1.4.3.jar                               | None                                     |
	| UCHI   | rftools                       | 7.25                     | rftools-1.12-7.25.jar                              | None                                     |
	| UCHI   | rpgloot                       | 1.0                      | rpgloot-1.12.2-1.10.jar                            | None                                     |
	| UCHI   | securitycraft                 | v1.8.10                  | SecurityCraft.jar                                  | None                                     |
	| UCHI   | solarflux                     | 4.32r                    | SolarFluxReborn_1.12.2-4.32r.jar                   | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHI   | storagedrawers                | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                    | None                                     |
	| UCHI   | survivaltweaks                | 5.1.0                    | SurvivalTweaks-5.1.1-1.12.2.jar                    | None                                     |
	| UCHI   | thermalfoundation             | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | thermalexpansion              | 5.5.4                    | ThermalExpansion-1.12.2-5.5.4.43-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | thermaldynamics               | 2.5.5                    | ThermalDynamics-1.12.2-2.5.5.21-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | thutcore                      | 5.21.0                   | thutcore-1.12.2-5.21.0.jar                         | None                                     |
	| UCHI   | thutcore_compat               | 1.0                      | thutcore-1.12.2-5.21.0.jar                         | None                                     |
	| UCHI   | thutessentials                | 2.2.22                   | thutessential.jar                                  | None                                     |
	| UCHI   | worldedit                     | 6.1.10-SNAPSHOT          | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar  | None                                     |
	| UCHI   | thutperms                     | 2.1.9@                   | thutpermissions-1.12.2-2.1.9.jar                   | None                                     |
	| UCHI   | thuttech                      | 6.1.6                    | thuttech.jar                                       | None                                     |
	| UCHI   | toughasnails                  | 3.1.0.140                | ToughAsNails-1.12.2-3.1.0.140-universal.jar        | None                                     |
	| UCHI   | of                            | 0.13                     | UsefulInterior.jar                                 | None                                     |
	| UCHI   | vehicle                       | 0.41.0                   | vehicle mod.jar                                    | None                                     |
	| UCHI   | imvoice                       | 0.7.0                    | VoiceChat-1.12.2-0.7.0.jar                         | None                                     |
	| UCHI   | watercan                      | 1.12.2-1.1.1             | watercan-1.12.2-1.1.1.jar                          | None                                     |
	| UCHI   | dsurround                     | 3.4.10.6                 | DynamicSurroundings-1.12.2-3.4.10.6.jar            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHI   | firstaid                      | 1.6.3                    | firstaid-1.6.3.jar                                 | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| UCHI   | adchimneys                    | 1.12.2-3.5.0.0           | AdChimneys-1.12.2-3.5.0.0-build.0353.jar           | None                                     |
	| UCHI   | coffeework                    | @version@                | CoffeeWorkshop_V1.2.5_MC1.12.2.jar                 | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (AdChimneys-1.12.2-3.5.0.0-build.0353.jar)
  com.endertech.minecraft.mods.adchimneys.world.WorldData$BlockRandomTick
HCASM (HammerCore-1.12.2-2.0.4.7.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
LoadingPlugin (AdPother.jar)
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$Vanilla
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$DynamicSurroundings
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$Weather2$Mesh
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$Weather2$Render
  com.endertech.minecraft.mods.adpother.transformers.ActuallyAdditions$FurnaceDouble
  com.endertech.minecraft.mods.adpother.transformers.ActuallyAdditions$CoalGenerator
  com.endertech.minecraft.mods.adpother.transformers.BetterWithMods$Furnace
  com.endertech.minecraft.mods.adpother.transformers.CookingForBlockheads$Oven
  com.endertech.minecraft.mods.adpother.transformers.DraconicEvolution$Generator
  com.endertech.minecraft.mods.adpother.transformers.EnderIO$StirlingGenerator
  com.endertech.minecraft.mods.adpother.transformers.EmbersRekindled$EmberBore
  com.endertech.minecraft.mods.adpother.transformers.EmbersRekindled$SteamEngine
  com.endertech.minecraft.mods.adpother.transformers.FastFurnace
  com.endertech.minecraft.mods.adpother.transformers.FloodLights$CarbonFloodlight
  com.endertech.minecraft.mods.adpother.transformers.Galacticraft$AutoRocket
  com.endertech.minecraft.mods.adpother.transformers.Galacticraft$Buggy
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveCraft$FurnaceTE
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityCokeOven
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityBlastFurnace
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityDieselGenerator
  com.endertech.minecraft.mods.adpother.transformers.ImmersivePetroleum$Motorboat
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveRailroading$LocomotiveDiesel
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveRailroading$LocomotiveSteam
  com.endertech.minecraft.mods.adpother.transformers.Mekanism$FuelwoodHeater
  com.endertech.minecraft.mods.adpother.transformers.MoreFurnaces$IronFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$InferiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$IntermediumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$PrudentiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$SuperiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$SupremiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$UltimateFurnace
  com.endertech.minecraft.mods.adpother.transformers.RealisticTorches$BlockTorch
  com.endertech.minecraft.mods.adpother.transformers.RFTools$CoalGenerator
  com.endertech.minecraft.mods.adpother.transformers.StevesCarts$ModuleCoal
  com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileIronAlloyFurnace
  com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileIronFurnace
  com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileSolidFuelGenerator
  com.endertech.minecraft.mods.adpother.transformers.TinkersConstruct$HeatingStructure
  com.endertech.minecraft.mods.adpother.transformers.SimpleGrinder$CoalGrinder
  com.endertech.minecraft.mods.adpother.renders.AerometerRender
  com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockCaughtFire
  com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockUpdateTick
  com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockExploded
  com.endertech.minecraft.mods.adpother.pollution.WorldData$GetSkyColor
  com.endertech.minecraft.mods.adpother.pollution.WorldData$FurnaceFuelBurned
  com.endertech.minecraft.mods.adpother.pollution.WorldData$LavaTouchesWater
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
LittlePatchingLoader (LittleTiles.jar)
  com.creativemd.littletiles.LittleTilesTransformer
FirstAid CoreMod (firstaid-core-1.6.3.jar)
  ichttt.mods.firstaid.common.asm.PotionTransformer
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.4.10.6.jar)
  org.blockartistry.DynSurround.asm.Transformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
CreativePatchingLoader (CreativeCore.jar)
  
CorePlugin (ForgeEndertech.jar)
  
RandomPatches (randompatches.jar)
  com.therandomlabs.randompatches.core.RPTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:ENABLED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 710 names; 806 stacks.
Pastebin Connection: Okay.
Dependent Mods: None.

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by ejektaflex** [comment]
`Caused by: java.lang.Exception: JSON Structure of 'bounties.json' is incorrect! Reverting to previous data. Details: com.google.gson.stream.MalformedJsonException: Expected value at line 65 column 3 path $[7]`

This isn't a problem with Bountiful, your JSON file is just invalid. Try running it through a JSON validator.

To make sure this doesn't happen again, you should try reloading the bounty data in-game with `/bo reload`. Loading the game with an invalid config file will crash the game, while reloading it in game will just tell you that the new files are invalid.

**Comment by Desoroxxx** [comment]
Ok thank you thanks to you the problem is now settled and my player can play without planting everything.
Sublime Text 3 my good help actually he told me that there was an error.

**Comment by ejektaflex** [comment]
I'm glad you got it figured out!
