### ISSUE TITLE
Crash Server 2.2.0

### ISSUE THREAD

**Issue by Desoroxxx** [ejektaflex/Bountiful#46]
Hum ...

Sorry, but I don't understand the Crah Report the server crashed when I take a bounty :

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (AdChimneys-1.12.2-3.5.0.0-build.0353.jar)
  HCASM (HammerCore-1.12.2-2.0.4.7.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  LoadingPlugin (AdPother.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  LittlePatchingLoader (LittleTiles.jar)
  FirstAid CoreMod (firstaid-core-1.6.3.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.4.10.6.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CreativePatchingLoader (CreativeCore.jar)
  CorePlugin (ForgeEndertech.jar)
  RandomPatches (randompatches.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 16/06/19 01:31
Description: Ticking player

java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at ejektaflex.bountiful.item.ItemBounty.func_77653_i(ItemBounty.kt:89)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
	at thut.essentials.util.InventoryLogger$Listener.func_71111_a(InventoryLogger.java:62)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:91)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
	at net.minecraft.world.World.func_72939_s(World.java:1734)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at ejektaflex.bountiful.item.ItemBounty.func_77653_i(ItemBounty.kt:89)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
	at thut.essentials.util.InventoryLogger$Listener.func_71111_a(InventoryLogger.java:62)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:91)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 555
	Entity Name: Desoroxxx
	Entity's Exact location: 310,72, 70,00, 280,89
	Entity's Block location: World: (310,70,280), Chunk: (at 6,4,8 in 19,17; contains blocks 304,0,272 to 319,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0,00, -0,08, 0,00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
	at net.minecraft.world.World.func_72939_s(World.java:1734)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['Desoroxxx'/555, l='world', x=310,72, y=70,00, z=280,89]]
	Chunk stats: ServerChunkCache: 328 Drop: 0
	Level seed: 3632738606462468653
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (214,63,278), Chunk: (at 6,3,6 in 13,17; contains blocks 208,0,272 to 223,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 174192542 game time, 19523 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 33570 (now: false), thunder time: 77267 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.14.82-mtxserv-version1
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 627047936 bytes (597 MB) / 2290089984 bytes (2184 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 18 total; -Xms2048M -Xmx4096M -XX:MaxMetaspaceSize=512M -XX:+UseFastAccessorMethods -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:MaxGCPauseMillis=100 -XX:+ParallelRefProcEnabled -XX:ParallelGCThreads=3 -XX:ConcGCThreads=1 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=60 -XX:UseSSE=4 -XX:+UseNUMA
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 76 mods loaded, 76 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                            | Version                  | Source                                            | Signature                                |
	|:--------- |:----------------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                     | 1.12.2                   | minecraft.jar                                     | None                                     |
	| UCHIJAAAA | mcp                           | 9.42                     | minecraft.jar                                     | None                                     |
	| UCHIJAAAA | FML                           | 8.0.99.99                | minecraft_server.jar                              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                         | 14.23.5.2768             | minecraft_server.jar                              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | creativecoredummy             | 1.0.0                    | minecraft.jar                                     | None                                     |
	| UCHIJAAAA | littletilescore               | 1.0.0                    | minecraft.jar                                     | None                                     |
	| UCHIJAAAA | openmodscore                  | 0.12.2                   | minecraft.jar                                     | None                                     |
	| UCHIJAAAA | obfuscate                     | 0.2.6                    | minecraft.jar                                     | None                                     |
	| UCHIJAAAA | firstaidcore                  | 1.0.0                    | minecraft.jar                                     | None                                     |
	| UCHIJAAAA | dsurroundcore                 |                          | minecraft.jar                                     | None                                     |
	| UCHIJAAAA | randompatches                 | 1.12.2-1.15.0.2          | randompatches.jar                                 | None                                     |
	| UCHIJAAAA | itemblacklist                 | 1.4.1                    | ItemBlacklist-1.4.1.jar                           | None                                     |
	| UCHIJAAAA | additionalcompression         | 3.3                      | AdditionalCompression.jar                         | None                                     |
	| UCHIJAAAA | forgeendertech                | 1.12.2-4.4.20.0          | ForgeEndertech.jar                                | None                                     |
	| UCHIJAAAA | adpother                      | 1.12.2-1.0.15.0          | AdPother.jar                                      | None                                     |
	| UCHIJAAAA | alesiamod                     | 1.1.4                    | Alesia Mod 1.1.4.jar                              | None                                     |
	| UCHIJAAAA | athenaeum                     | 1.12.2-1.16.0-1-g05e9939 | athenaeum-1.12.2-1.16.0.jar                       | None                                     |
	| UCHIJAAAA | bottledmilk                   | 1.0.0                    | BottledMilk-1.12-1.1.0.jar                        | None                                     |
	| UCHIJAAAA | forgelin                      | 1.8.2                    | Forgelin-1.8.2.jar                                | None                                     |
	| UCHIJAAAA | bountiful                     | 2.2.0                    | Bountiful-2.2.0.jar                               | None                                     |
	| UCHIJAAAA | chameleon                     | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| UCHIJAAAA | clothingmodbetav04bytitoo8899 | v.0.4                    | Clothing.jar                                      | None                                     |
	| UCHIJAAAA | codechickenlib                | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux                  | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | cofhcore                      | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar            | None                                     |
	| UCHIJAAAA | cofhworld                     | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | colouredchat                  | 0.3.0-beta               | colouredchat-1.12.2-0.3.0-beta.jar                | None                                     |
	| UCHIJAAAA | cookingforblockheads          | 6.4.69                   | CookingForBlockheads_1.12.2-6.4.69.jar            | None                                     |
	| UCHIJAAAA | creativecore                  | 1.9.9                    | CreativeCore.jar                                  | None                                     |
	| UCHIJAAAA | customnpcs                    | 1.12                     | Customnpc.jar                                     | None                                     |
	| UCHIJAAAA | cdm                           | 0.4.1                    | device-mod-0.4.1-1.12.2.jar                       | None                                     |
	| UCHIJAAAA | df-roads                      | 1.5.2-mc1.12.2           | df-roads-1.5.2-mc1.12.2.jar                       | None                                     |
	| UCHIJAAAA | discordinvite                 | 1.0.4                    | discordinvite.jar                                 | None                                     |
	| UCHIJAAAA | drugs_mod                     | 1.0.0                    | Drugzmod.jar                                      | None                                     |
	| UCHIJAAAA | dynamictrees                  | 1.12.2-0.9.4             | DynamicTrees.jar                                  | None                                     |
	| UCHIJAAAA | fastleafdecay                 | v14                      | FastLeafDecay-v14.jar                             | None                                     |
	| UCHIJAAAA | cfm                           | 6.3.0                    | furniture-6.3.0-1.12.2.jar                        | None                                     |
	| UCHIJAAAA | cgm                           | 0.12.1                   | guns.jar                                          | None                                     |
	| UCHIJAAAA | hammercore                    | 2.0.4.7                  | HammerCore-1.12.2-2.0.4.7.jar                     | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHIJAAAA | hidenames                     | 1.4                      | HideNames-1.12-1.4.jar                            | None                                     |
	| UCHIJAAAA | ironbackpacks                 | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                 | None                                     |
	| UCHIJAAAA | lagbgonreborn                 | 1.0.4                    | lagbgonreborn-1.0.4.jar                           | None                                     |
	| UCHIJAAAA | littletiles                   | 1.5.0                    | LittleTiles.jar                                   | None                                     |
	| UCHIJAAAA | malisiscore                   | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                      | None                                     |
	| UCHIJAAAA | malisisdoors                  | 1.12.2-7.3.0             | malisisdoors.jar                                  | None                                     |
	| UCHIJAAAA | mcjtylib_ng                   | 2.6.5                    | mcjtylib-1.12-2.6.5.jar                           | None                                     |
	| UCHIJAAAA | currency                      | 3.1.5                    | NeverEnoughCurrency-4.0.1.jar                     | None                                     |
	| UCHIJAAAA | openmods                      | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJAAAA | openblocks                    | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                       | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJAAAA | p455w0rdslib                  | 2.0.36                   | p455w0rdslib-1.12.2-2.0.36.jar                    | None                                     |
	| UCHIJAAAA | pizzacraft                    | 1.4.1                    | PizzaCraft-1.12.2-1.4.1.jar                       | None                                     |
	| UCHIJAAAA | pneumaticcraft                | 1.12.2-0.11.1-361        | pneumaticcraft-repressurized.jar                  | None                                     |
	| UCHIJAAAA | realserene                    | 1.4.3                    | realserene-1.4.3.jar                              | None                                     |
	| UCHIJAAAA | rftools                       | 7.25                     | rftools-1.12-7.25.jar                             | None                                     |
	| UCHIJAAAA | rpgloot                       | 1.0                      | rpgloot-1.12.2-1.10.jar                           | None                                     |
	| UCHIJAAAA | securitycraft                 | v1.8.10                  | SecurityCraft.jar                                 | None                                     |
	| UCHIJAAAA | solarflux                     | 4.32r                    | SolarFluxReborn_1.12.2-4.32r.jar                  | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHIJAAAA | storagedrawers                | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                   | None                                     |
	| UCHIJAAAA | survivaltweaks                | 5.1.0                    | SurvivalTweaks-5.1.1-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | thermalfoundation             | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermalexpansion              | 5.5.4                    | ThermalExpansion-1.12.2-5.5.4.43-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermaldynamics               | 2.5.5                    | ThermalDynamics-1.12.2-2.5.5.21-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thutcore                      | 5.21.0                   | thutcore-1.12.2-5.21.0.jar                        | None                                     |
	| UCHIJAAAA | thutcore_compat               | 1.0                      | thutcore-1.12.2-5.21.0.jar                        | None                                     |
	| UCHIJAAAA | thutessentials                | 2.2.22                   | thutessential.jar                                 | None                                     |
	| UCHIJAAAA | worldedit                     | 6.1.10-SNAPSHOT          | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| UCHIJAAAA | thutperms                     | 2.1.9@                   | thutpermissions-1.12.2-2.1.9.jar                  | None                                     |
	| UCHIJAAAA | toughasnails                  | 3.1.0.140                | ToughAsNails-1.12.2-3.1.0.140-universal.jar       | None                                     |
	| UCHIJAAAA | of                            | 0.13                     | UsefulInterior.jar                                | None                                     |
	| UCHIJAAAA | vehicle                       | 0.41.0                   | vehicle mod.jar                                   | None                                     |
	| UCHIJAAAA | imvoice                       | 0.7.0                    | VoiceChat-1.12.2-0.7.0.jar                        | None                                     |
	| UCHIJAAAA | watercan                      | 1.12.2-1.1.1             | watercan-1.12.2-1.1.1.jar                         | None                                     |
	| UCHIJAAAA | dsurround                     | 3.4.10.6                 | DynamicSurroundings-1.12.2-3.4.10.6.jar           | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJAAAA | firstaid                      | 1.6.3                    | firstaid-1.6.3.jar                                | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| UCHIJAAAA | adchimneys                    | 1.12.2-3.5.0.0           | AdChimneys-1.12.2-3.5.0.0-build.0353.jar          | None                                     |
	| UCHIJAAAA | coffeework                    | @version@                | CoffeeWorkshop_V1.2.5_MC1.12.2.jar                | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (AdChimneys-1.12.2-3.5.0.0-build.0353.jar)
  com.endertech.minecraft.mods.adchimneys.world.WorldData$BlockRandomTick
HCASM (HammerCore-1.12.2-2.0.4.7.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
LoadingPlugin (AdPother.jar)
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$Vanilla
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$DynamicSurroundings
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$Weather2$Mesh
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$Weather2$Render
  com.endertech.minecraft.mods.adpother.transformers.ActuallyAdditions$FurnaceDouble
  com.endertech.minecraft.mods.adpother.transformers.ActuallyAdditions$CoalGenerator
  com.endertech.minecraft.mods.adpother.transformers.BetterWithMods$Furnace
  com.endertech.minecraft.mods.adpother.transformers.CookingForBlockheads$Oven
  com.endertech.minecraft.mods.adpother.transformers.DraconicEvolution$Generator
  com.endertech.minecraft.mods.adpother.transformers.EnderIO$StirlingGenerator
  com.endertech.minecraft.mods.adpother.transformers.EmbersRekindled$EmberBore
  com.endertech.minecraft.mods.adpother.transformers.EmbersRekindled$SteamEngine
  com.endertech.minecraft.mods.adpother.transformers.FastFurnace
  com.endertech.minecraft.mods.adpother.transformers.FloodLights$CarbonFloodlight
  com.endertech.minecraft.mods.adpother.transformers.Galacticraft$AutoRocket
  com.endertech.minecraft.mods.adpother.transformers.Galacticraft$Buggy
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveCraft$FurnaceTE
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityCokeOven
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityBlastFurnace
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityDieselGenerator
  com.endertech.minecraft.mods.adpother.transformers.ImmersivePetroleum$Motorboat
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveRailroading$LocomotiveDiesel
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveRailroading$LocomotiveSteam
  com.endertech.minecraft.mods.adpother.transformers.Mekanism$FuelwoodHeater
  com.endertech.minecraft.mods.adpother.transformers.MoreFurnaces$IronFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$InferiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$IntermediumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$PrudentiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$SuperiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$SupremiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$UltimateFurnace
  com.endertech.minecraft.mods.adpother.transformers.RealisticTorches$BlockTorch
  com.endertech.minecraft.mods.adpother.transformers.RFTools$CoalGenerator
  com.endertech.minecraft.mods.adpother.transformers.StevesCarts$ModuleCoal
  com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileIronAlloyFurnace
  com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileIronFurnace
  com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileSolidFuelGenerator
  com.endertech.minecraft.mods.adpother.transformers.TinkersConstruct$HeatingStructure
  com.endertech.minecraft.mods.adpother.transformers.SimpleGrinder$CoalGrinder
  com.endertech.minecraft.mods.adpother.renders.AerometerRender
  com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockCaughtFire
  com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockUpdateTick
  com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockExploded
  com.endertech.minecraft.mods.adpother.pollution.WorldData$GetSkyColor
  com.endertech.minecraft.mods.adpother.pollution.WorldData$FurnaceFuelBurned
  com.endertech.minecraft.mods.adpother.pollution.WorldData$LavaTouchesWater
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
LittlePatchingLoader (LittleTiles.jar)
  com.creativemd.littletiles.LittleTilesTransformer
FirstAid CoreMod (firstaid-core-1.6.3.jar)
  ichttt.mods.firstaid.common.asm.PotionTransformer
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.4.10.6.jar)
  org.blockartistry.DynSurround.asm.Transformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
CreativePatchingLoader (CreativeCore.jar)
  
CorePlugin (ForgeEndertech.jar)
  
RandomPatches (randompatches.jar)
  com.therandomlabs.randompatches.core.RPTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:ENABLED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 710 names; 806 stacks.
Pastebin Connection: Okay.
Dependent Mods: None.

	Profiler Position: N/A (disabled)
	Player Count: 1 / 150; [EntityPlayerMP['Desoroxxx'/555, l='world', x=310,72, y=70,00, z=280,89]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by ejektaflex** [comment]
Yep, this is the same as #43. It's a localization bug that I need to fix. I'm going to close this issue because that issue is already open, but thank you for the report! There will be a fix in the next update.
