### ISSUE TITLE
[Suggestion] Add Advancements

### ISSUE THREAD

**Issue by Desoroxxx** [ejektaflex/Bountiful#47]
That "Enhancenment"

Hello you may have already seen my nickname I have a server and your mod on I thought that adding goals via achievements would be a good idea for you to see.

**Comment by ejektaflex** [comment]
This is a good idea - it's something that I can look into.

**Comment by CalaMariGold** [comment]
As far as achievements, I think you could do "Complete X bounties" every 10 or 25 bounties or so. Have it go all the way up to 100 or some other number.

Although, this wouldn't be useful in my case, as I use Triumph to add custom achievements. If you could add Triumph compatibility, that would be a huuuge plus!

**Comment by Yourname942** [comment]
Yes please add this feature!

**Comment by ejektaflex** [comment]
This is implemented in Bountiful v3.0.0, on Minecraft 1.14!
