### ISSUE TITLE
Game refuses to start

### ISSUE THREAD

**Issue by ShikharBasnet** [ejektaflex/Bountiful#48]
I keep getting this error:

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2019-07-17 10:01:53 NPT
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Bountiful (bountiful)
Caused by: java.lang.Exception: 'bountiful/rewards.json' contains one or more invalid rewards. Invalid rewards: [PickedEntry (Stack) [Item: chancecubes:chance_cube, Amount: 1000, NBT: null, Weight: 100, Stages: null]]
    at ejektaflex.bountiful.proxy.CommonProxy.postInit(CommonProxy.kt:107)
    at ejektaflex.bountiful.Bountiful.postInit(Bountiful.kt:53)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_171, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 237606248 bytes (226 MB) / 1151660032 bytes (1098 MB) up to 6989021184 bytes (6665 MB)
  JVM Flags: 3 total; -Xmn128M -Xmx6677M -XX:+UseConcMarkSweepGC
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2796 66 mods loaded, 66 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                   | Version          | Source                                         | Signature                                |
       |:----- |:-------------------- |:---------------- |:---------------------------------------------- |:---------------------------------------- |
       | LCHIJ | minecraft            | 1.12.2           | minecraft.jar                                  | None                                     |
       | LCHIJ | mcp                  | 9.42             | minecraft.jar                                  | None                                     |
       | LCHIJ | FML                  | 8.0.99.99        | forge-1.12.2-14.23.5.2796.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJ | forge                | 14.23.5.2796     | forge-1.12.2-14.23.5.2796.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJ | itemphysic           | 1.4.0            | minecraft.jar                                  | None                                     |
       | LCHIJ | ivtoolkit            | 1.3.3-1.12       | minecraft.jar                                  | None                                     |
       | LCHIJ | otgcore              | 1.12.2 - v7      | minecraft.jar                                  | None                                     |
       | LCHIJ | foamfixcore          | 7.7.4            | minecraft.jar                                  | None                                     |
       | LCHIJ | aether_legacy        | 1.4.4            | aether_legacy-1.12.2-v1.4.4.jar                | None                                     |
       | LCHIJ | akashictome          | 1.2-12           | AkashicTome-1.2-12.jar                         | None                                     |
       | LCHIJ | aroma1997core        | 2.0.0.2          | Aroma1997Core-1.12.2-2.0.0.2.jar               | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCHIJ | autoreglib           | 1.3-30           | AutoRegLib-1.3-30.jar                          | None                                     |
       | LCHIJ | baubles              | 1.5.2            | Baubles-1.12-1.5.2.jar                         | None                                     |
       | LCHIJ | bibliocraft          | 2.4.5            | BiblioCraft[v2.4.5][MC1.12.2].jar              | None                                     |
       | LCHIJ | openterraingenerator | v6               | OpenTerrainGenerator-1.12.2 - v6.jar           | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
       | LCHIJ | biomebundle          | 5.1              | Biome_Bundle-1.12.2-v6.1.jar                   | None                                     |
       | LCHIJ | forgelin             | 1.8.2            | Forgelin-1.8.2.jar                             | None                                     |
       | LCHIE | bountiful            | 2.2.0            | Bountiful-2.2.0.jar                            | None                                     |
       | LCHI  | controlling          | 3.0.6            | Controlling-3.0.6.jar                          | None                                     |
       | LCHI  | crafttweaker         | 4.1.19           | CraftTweaker2-1.12-4.1.19.jar                  | None                                     |
       | LCHI  | ctgui                | 1.0.0            | CraftTweaker2-1.12-4.1.19.jar                  | None                                     |
       | LCHI  | jei                  | 4.15.0.268       | jei_1.12.2-4.15.0.268.jar                      | None                                     |
       | LCHI  | crafttweakerjei      | 2.0.3            | CraftTweaker2-1.12-4.1.19.jar                  | None                                     |
       | LCHI  | creeperconfetti      | 1.4.2            | creeperconfetti-1.4.2.jar                      | None                                     |
       | LCHI  | cyclicmagic          | 1.19.12          | Cyclic-1.12.2-1.19.12.jar                      | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
       | LCHI  | dimdoors             | 3.0.9+287        | DimensionalDoors-3.0.9-287.jar                 | None                                     |
       | LCHI  | disenchanter         | 1.6              | disenchanter-[1.12]1.6.jar                     | None                                     |
       | LCHI  | dungeontactics       | DT-0.16.5        | DungeonTactics-1.12.2-0.16.5.jar               | None                                     |
       | LCHI  | ebwizardry           | 4.1.4            | Electroblob's+Wizardry+-+4.1.4+-+MC+1.12.2.jar | None                                     |
       | LCHI  | enchdesc             | 1.1.15           | EnchantmentDescriptions-1.12.2-1.1.15.jar      | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHI  | extra_spells         | 1.0.7            | ExtraSpells-1.12.2-1.0.7.jar                   | None                                     |
       | LCHI  | foamfix              | 0.10.5-1.12.2    | foamfix-0.10.5-1.12.2.jar                      | None                                     |
       | LCHI  | forgeendertech       | 1.12.2-4.4.20.1  | ForgeEndertech-1.12.2-4.4.20.1-build.0362.jar  | None                                     |
       | LCHI  | ftblib               | 5.4.3.103        | FTBLib-5.4.3.103.jar                           | None                                     |
       | LCHI  | ftbutilities         | 5.4.0.97         | FTBUtilities-5.4.0.97.jar                      | None                                     |
       | LCHI  | heroicarmory         | 1.1.3            | heroicarmory-1.2.0.jar                         | None                                     |
       | LCHI  | improvedbackpacks    | 1.12.2-1.4.0.0   | ImprovedBackpacks-1.12.2-1.4.0.0.jar           | None                                     |
       | LCHI  | infernalmobs         | 1.7.6            | InfernalMobs-1.12.1.jar                        | None                                     |
       | LCHI  | ironbackpacks        | 1.12.2-3.0.8-12  | IronBackpacks-1.12.2-3.0.8-12.jar              | None                                     |
       | LCHI  | landmanager          | 1.3.1            | landmanager-1.12.2-1.3.1.jar                   | None                                     |
       | LCHI  | lex                  | 1.0.8            | LibEx-1.12.2-1.0.8.jar                         | None                                     |
       | LCHI  | livingenchantment    | 3.1.9            | living_enchantment-3.1.9.jar                   | None                                     |
       | LCHI  | lost_aether          | 0.0.3            | lost_aether-content-1.12.2-v0.0.3.jar          | None                                     |
       | LCHI  | llibrary             | 1.7.19           | llibrary-1.7.19-1.12.2.jar                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHI  | mowziesmobs          | 1.5.4            | mowziesmobs-1.5.4.jar                          | None                                     |
       | LCHI  | nex                  | 2.0.8            | NetherEx-1.12.2-2.0.8.jar                      | None                                     |
       | LCHI  | recipehandler        | 0.13             | NoMoreRecipeConflict-0.13(1.12.2).jar          | None                                     |
       | LCHI  | norecipebook         | 1.2.1            | noRecipeBook_v1.2.2formc1.12.2.jar             | None                                     |
       | LCHI  | notes                | 1.1.1            | Notes-1.12-1.1.1.jar                           | None                                     |
       | LCHI  | placeableitems       | 3.3              | placeableitems-3.3.jar                         | None                                     |
       | LCHI  | potioncore           | 1.8_for_1.12.2   | PotionCore-1.8_for_1.12.2.jar                  | None                                     |
       | LCHI  | progressivebosses    | 1.5.0            | ProgressiveBosses-1.5.0-mc1.12.x.jar           | None                                     |
       | LCHI  | qualitytools         | 1.0.6_for_1.12.2 | QualityTools-1.0.6_for_1.12.2.jar              | None                                     |
       | LCHI  | randomloot           | 1.3              | RandomLoot-1.4.3.jar                           | None                                     |
       | LCHI  | xreliquary           | 1.12.2-1.3.4.786 | Reliquary-1.12.2-1.3.4.786.jar                 | None                                     |
       | LCHI  | roughtweaks          | 1.0              | roughTweaks0.2.4-1.12.2.jar                    | None                                     |
       | LCHI  | rustic               | 1.1.0            | rustic-1.1.0.jar                               | None                                     |
       | LCHI  | silentlib            | 3.0.13           | SilentLib-1.12.2-3.0.13+167.jar                | None                                     |
       | LCHI  | scalinghealth        | 1.3.37           | ScalingHealth-1.12.2-1.3.38+143.jar            | None                                     |
       | LCHI  | skewers              | 1.1              | Skewers-1.1.jar                                | None                                     |
       | LCHI  | tombmanygraves       | 1.12-4.2.0       | TombManyGraves-1.12-4.2.0.jar                  | None                                     |
       | LCHI  | tropicraft           | 7.1.9.115        | tropicraft-MC1.12.2-7.1.9.115.jar              | None                                     |
       | LCHI  | vanillafix           | 1.0.10-SNAPSHOT  | VanillaFix-1.0.10-99.jar                       | None                                     |
       | LCHI  | vtweaks              | 2.0.2            | VTweaks-1.12.2-2.0.2.jar                       | None                                     |
       | LCHI  | waystones            | 4.0.67           | Waystones_1.12.2-4.0.67.jar                    | None                                     |
       | LCHI  | vt                   | 1.4.8            | VanillaTweaks-1.4.8.jar                        | None                                     |
  Loaded coremods (and transformers): llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      CorePlugin (ForgeEndertech-1.12.2-4.4.20.1-build.0362.jar)
                                        
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.OTGClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
                                        
                                      ItemPatchingLoader (ItemPhysic Lite 1.3.7 mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      ForgelinPlugin (Forgelin-1.8.2.jar)
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.36' Renderer: 'GeForce GTX 1050/PCIe/SSE2'
  Suspected Mods: Bountiful (bountiful)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2796
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.36, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
![image](https://user-images.githubusercontent.com/52988968/61346949-ae953000-a87a-11e9-807c-523c54159c47.png)

**Comment by ejektaflex** [comment]
`Caused by: java.lang.Exception: 'bountiful/rewards.json' contains one or more invalid rewards. Invalid rewards: [PickedEntry (Stack) [Item: chancecubes:chance_cube, Amount: 1000, NBT: null, Weight: 100, Stages: null]]`

It looks like you or someone else tried to add a chance cube as a reward, however `chancecubes:chance_cube` does not exist in the game.

If I had to guess, you may have disabled Chance Cubes from the modpack? If so, then you just have to remove the entry from your `rewards.json` config file (located in `config/bountiful/rewards.json`). Just CTRL+F for `chancecubes:chance_cube` to find it and remove that whole entry. Look at (this)[https://github.com/ejektaflex/Bountiful/wiki/Customizing-Bounty-Rewards] to see an example of adding a bounty.

I hope that helps @ShikharBasnet !
