### ISSUE TITLE
Option to stop hoppers from extracting bounties

### ISSUE THREAD

**Issue by TheDeviantCrafter** [ejektaflex/Bountiful#50]
A bounty inside of a hopper or chest doesn't tick, meaning the timer doesn't count down. Combined with a hopper and a lot of waiting, it's possible to gather huge numbers of bounties to turn in all at once.

An 8 hour overnight AFK session will yield 240 bounties with default config settings.

**Comment by ejektaflex** [comment]
Hey, I never quite thought about this. That's a very good point! I might make it like this:
1) Bounties can't be sucked out of a hopper
2) Bounties can be sucked out of a hopper, but their timers will start when that happens.

**Comment by ejektaflex** [comment]
This is done for v3.0 as of a little while ago!
