### ISSUE TITLE
Mixin-related crash when Lag Goggles is also installed 

### ISSUE THREAD

**Issue by TheDeviantCrafter** [ejektaflex/Bountiful#53]
[LagGoggles issue](https://github.com/TerminatorNL/LagGoggles/issues/80)

[Another LagGoggles issue that explains how to fix it](https://github.com/TerminatorNL/LagGoggles/issues/71)

**Describe the bug**

When both Lag Goggles and Bountiful are installed, the game crashes early in the startup sequence and does not create a 

**To Reproduce**

Install these three mods:
- Lag Goggles FAT 4.8
- Bountiful 2.2.0
- Forgelin 1.8.3

Latest.log: https://pastebin.com/0RPK7Rni
Debug.log: https://pastebin.com/vruepAre

**Comment by ejektaflex** [comment]
```Caused by: java.lang.Exception: 'bountiful/bounties.json' contains one or more invalid bounties.```

Sounds like you have an invalid JSON file. I'd delete your Bountiful configs and try edit them again, or run them through a JSON validator, or especially so: Make sure that all items in the JSON exist. LagGoggles messes with ASM code, something Bountiful doesn't do. Even if your JSON was perfect, any meddling with ASM code is on on their end, not mine, and they're the ones responsible for fixing it.
