### ISSUE TITLE
ToroQuest Compatibility

### ISSUE THREAD

**Issue by CalaMariGold** [ejektaflex/Bountiful#56]
It would be awesome if completing bounties also gives you rep for the village it spawned in.

Another thing I noticed is that sometimes the ToroQuest structures will spawn over the bounty board, overwriting it. I'm not sure if that's what happens, but it's worth noting. Either way it's not a big deal because it only happens sometimes.

Thanks!

**Comment by ejektaflex** [comment]
Hey, that's a good idea. I probably won't be adding any more compatibility for v1.12 of Minecraft, though, since most of my time is being put towards v1.14+. If ToroQuest gets an update to the newer versions that I'm working on, I will 100% reopen this issue!
