### ISSUE TITLE
[Feature request] Make rewards only be emeralds

### ISSUE THREAD

**Issue by thegamerx1** [ejektaflex/Bountiful#57]

**Comment by faeldray** [comment]
Unless I'm misreading the question, you can already do this yourself. There's a wiki page that provides the details: https://github.com/ejektaflex/Bountiful/wiki/Customizing-Bounty-Rewards

**Comment by ejektaflex** [comment]
Yep, this is already provided by Bountiful via the wiki! Just change the config.
