### ISSUE TITLE
Configuration is wrong but cannot find where

### ISSUE THREAD

**Issue by American-Gamer** [ejektaflex/Bountiful#59]
Been messing around with your mod for a modpack im creating and i just about have it but after fixing all the errors i can I now get the error:
Invalid bounty json data detail:
Cannot get random in empty range:100..10
attached is my bounties.json file
Could i get help finding the error cause I have referenced the original setup and even talking to a duck isnt helping me find the error
[bounties.txt](https://github.com/ejektaflex/Bountiful/files/4115510/bounties.txt)

**Comment by TheDeviantCrafter** [comment]
```
{
		"content": "minecraft:gunpowder",
		"amount": {
			"min": 100,
			"max": 10
		},
```

The min is higher than the max. Try swapping those around.

**Comment by ejektaflex** [comment]
Yep, you just need to switch the min and max values, @TheDeviantCrafter is correct. Thanks!

**Comment by American-Gamer** [comment]
Sorry for responding late. Been a little busy. However thank you very much and I can't believe I didn't notice that. Again thank you guys
