### ISSUE TITLE
Bountiful Rewards - Oxygen Currency

### ISSUE THREAD

**Issue by dracoattila** [ejektaflex/Bountiful#65]
I working on a modpack and the items I saw as rewards is not fit to the modpack so I wanted to change it, but when I added the rewards.json these lines :

{
   "content": "oxygen_core.currency.money",
   "unitWorth": 100,
   "weight": 100,
   "amount": 50
}
I got a crash, all time, and I tried to edit many ways, but nothing worked

The following crash :
[crash-2020-03-13_17.10.43-client.txt](https://github.com/ejektaflex/Bountiful/files/4331637/crash-2020-03-13_17.10.43-client.txt)

**Comment by ejektaflex** [comment]
That's not the right registry name for the item, that's why. If you use the mod CraftTweaker, you can get the right name by using "/ct hand"

**Comment by dracoattila** [comment]
Its okay, but how can I check the name of the currency when it's a digital thing, the player can't keep in it's hand.

**Comment by ejektaflex** [comment]
Oh, you can currently only make bounties for items in hand or for killing mobs. If there's a way to add currency to a player with commands, then you'll be able to do that in the future because I'll be making a new bounty type then (running commands as rewards)

**Comment by dracoattila** [comment]
Then this issue seems to closed for the next update.
Thanks for helping and I'll waiting then for that update.

**Comment by ejektaflex** [comment]
Well, only for 1.12. I won't be updating 1.12 anymore, unless there are some important bug fixes. Sorry about that!
