### ISSUE TITLE
[Feature] Korean language support

### ISSUE THREAD

**Issue by MilkissWhite** [ejektaflex/Bountiful#66]
## Feature Request

**Feature description**

What you want (A clear and concise description of what you want to improve):
 Korean language support & make lauguage file have "kills" text

**How it improves the player experience**

How this would make Bountiful better:
 Korean language users can play this mod easier

----
here is language file for 3.0.0-1.15.2-
[ko_kr.zip](https://github.com/ejektaflex/Bountiful/files/4336129/ko_kr.zip)

I coudn't find where I can see these strings:
"bountiful.tooltip.advanced", "bountiful.tooltip.time"
and monster killing requirements show me "kills" text but this language file not have it.

**Comment by ejektaflex** [comment]
Cool! Thank you for the language file, I'll add it in for v3.1.0. What would "kills" be in Korean in this sense for the tooltip?

**Comment by MilkissWhite** [comment]
about [Mob name "Kills"].
 I think [Mob name "처치"] will be good. "처치" mean similar to "defeat" or "beat". baisically "처치하기" is full word, but it be used with shorten version 처치 often.
 "죽이기" is directly same word meaning 'killing', but korean games usually avoid to using that word(especially games that kids can play).

**Comment by ejektaflex** [comment]
Sure thing, thank you!

**Comment by ejektaflex** [comment]
Completed as of f84a2ef. Will be included in Bountiful v3.1.0!
