### ISSUE TITLE
I'm having a crashing issue and I hope you can help me.

### ISSUE THREAD

**Issue by thedeerirty** [ejektaflex/Bountiful#69]
## Bug Report

**Observed Behaviour**

What happened: I attempted to edit the rewards and bounty requirments to include creatures and items from different mods, and now the mod fails to start, crashing the game. If this isn't like, the place to report this or ask for assistance, I am **super** sorry for bugging you/wasting your time.

Crash log: https://paste.dimdev.org/fipilatubu.mccrash

**Expected Behaviour**

What should have happened: I think, assuming I did things right, that the game simply should have started correctly.

**Minimal setup needed to reproduce**

- Forge version: 1.12.2
- Bountiful version: 2.2.1
- Other mods: RLcraft + https://docs.google.com/document/d/18gh2dTmBVxdS6rC7E8gvGse7hDVuagZkz_nMsOosiI0/edit

**Steps to reproduce**

How to recreate this: 
i've added these parameters to the bounties and rewards config
![error1](https://user-images.githubusercontent.com/58305182/77254355-ec7efb00-6c36-11ea-882e-2a65ab8aea06.PNG)
![error2](https://user-images.githubusercontent.com/58305182/77254361-f43e9f80-6c36-11ea-812f-b1a1dfd440f2.PNG)
![error3](https://user-images.githubusercontent.com/58305182/77254363-f99bea00-6c36-11ea-99d7-e857db2fea81.PNG)
![error4](https://user-images.githubusercontent.com/58305182/77254371-002a6180-6c37-11ea-9349-0097482d4e97.PNG)
![error5](https://user-images.githubusercontent.com/58305182/77254385-08829c80-6c37-11ea-9cf4-c71c3fec371f.PNG)
![error6](https://user-images.githubusercontent.com/58305182/77254388-0e787d80-6c37-11ea-8c0d-7b37ac4ed807.PNG)

simply start the game, and it seems to crash.

(Again, sorry if this is the wrong place to report this. Have a nice day.)

**Comment by ejektaflex** [comment]
Looks like your JSON file (bounties.json) has incorrect syntax somewhere. Try copy-and-paste the contents of your `bounties.json` into a JSON validator such as [JSONLint](https://jsonlint.com/), it will tell you if there are any problems. I hope that's your answer 👍

**Comment by thedeerirty** [comment]
thank you for responding, I shall attempt this shortly.

**Comment by thedeerirty** [comment]
https://paste.dimdev.org/ibojoxemet.mccrash

I edited the bounties file and it was validated by JSONLint, but it still fails. Sorry to trouble you.

**Comment by ejektaflex** [comment]
Now your error logs says this at the top:
```
Caused by: java.lang.Exception: 'bountiful/bounties.json' contains one or more invalid bounties. Invalid bounty objectives: [Pickable [Item: minecraft:entity:spider, Amount: 1..10, Unit Worth: 130, Weight: 100, Stages: []], Pickable [Item: entity:lycanitesmobs:comba, Amount: 2..2, Unit Worth: 200, Weight: 100, Stages: []], Pickable [Item: entity:howlingmoon:werewolf, Amount: 1..1, Unit Worth: 800, Weight: 100, Stages: []]]
```
It looks like of those three bounties, the first is wrong (it should be `entity:minecraft:spider`, not `minecraft:entity:spider`)
The second I `think` is wrong, I think it's a `conba`, not a `comba`. No idea about the werewolf, though. You can see a list of all entities in the game by typing `/bo entities` in 1.12.

**Comment by thedeerirty** [comment]
Oh dang, I did not know that last part, thank you. Also, thank you for taking time to assist me; I imagine this error is more on my behalf than the actual mods, and yet you helped me anyhow. Appericate it.

**Comment by thedeerirty** [comment]
I imagine I'm still going to have issues, but I'll stop bothering you pal.

**Comment by ejektaflex** [comment]
It looks like you've got it figured out, but you can always reopen this issue if you need. Good luck! :)
