### ISSUE TITLE
[Suggestion] Tier-Lock Certain Rewards

### ISSUE THREAD

**Issue by abboip** [ejektaflex/Bountiful#7]
Being able to tier-lock certain rewards behind certain bounty tiers could be useful. While the tiers may offer more rewards, it can also be odd seeing high-valued rewards in the common tier. Ideally this could be done per reward?

**Comment by ejektaflex** [comment]
Hey, that's a good idea. I was originally thinking of adding a weight to each item so that people could tweak it so some items appeared less or more frequently - and doing both of these might be unnecessarily complicated.

**Comment by ejektaflex** [comment]
Weighted bounty objectives have been added as of v2.0 in f991b93.
