### ISSUE TITLE
Some Bounties cause crashes

### ISSUE THREAD

**Issue by andrew-diminutto** [ejektaflex/Bountiful#71]
SORRY, here's the proper format thanks!

**Observed Behaviour**
What happened:
I finished this bounty and went to cash in for my reward and got a crash. I tried again, got another crash. The items however do drop, but the crash seems to happen just after they drop. I am with 64 other mods, all which are very minor. 
![image](https://user-images.githubusercontent.com/60979100/77369863-f50a2b00-6d35-11ea-8179-06bb6e1207bc.png)

Crash Log:
[crash-2020-03-23_22.40.28-server.txt](https://github.com/ejektaflex/Bountiful/files/4372345/crash-2020-03-23_22.40.28-server.txt)

**Expected Behaviour**
Should have provided me the banner rewards

Fore Version: forge-1.15.2-31.1.27
Bountiful Verison: Morpheus-1.15.2-4.2.50
Other Mods:

[mods.zip](https://github.com/ejektaflex/Bountiful/files/4372334/mods.zip)

**Steps to reproduce**
Finish above bounty and try to get the reward

**Comment by ejektaflex** [comment]
Please conform to the [GitHub issue template](https://github.com/ejektaflex/Bountiful/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md) so that I have all the information necessary to see what's causing the crash. I need a crash log, plus all version numbers (Forge, in this case)

**Comment by ejektaflex** [comment]
Got the info - I'll look into this!

**Comment by ejektaflex** [comment]
@andrew-diminutto  What pack is this from, and what Decrees were on the board when you took this? It looks like it could be a custom reward that a modpack maker made that's causing the crash.

**Comment by andrew-diminutto** [comment]
> 
> 
> Got the info - I'll look into this! It looks like a problem with Item-Tag objectives (e.g. Random Banners) that reward a random item from a tag list. Most of these objectives come from the shepherding decree - so I suspect that's what you're using. For now, avoid bounties that ask for / reward "Any ___" or "Random ___" (Other decrees usually don't have these).

Thanks, appreciate the fast response, really awesome!

**Comment by andrew-diminutto** [comment]
> 
> 
> Got the info - I'll look into this! It looks like a problem with Item-Tag objectives (e.g. Random Banners) that reward a random item from a tag list. Most of these objectives come from the shepherding decree - so I suspect that's what you're using. For now, avoid bounties that ask for / reward "Any ___" or "Random ___" (Other decrees usually don't have these).

It isn't an official modpack, just some mods I threw together to play with my friends. As for the decree I'm not sure about the name, but there was only 1 decree in the bounty board, and it allowed the banner bounties to spawn. As far as I'm aware there are no custom bounties.

**Comment by ejektaflex** [comment]
I've figured out the problem - I was using a clientside method `getDefaultInstance`, but I will switch it to creating a wholly new itemstack. This will be fixed with v3.1.0 and be out quite soon - all I've got left for v3.1.0 is some testing.

**Comment by andrew-diminutto** [comment]
> 
> 
> I've figured out the problem - I was using a clientside method `getDefaultInstance` which does not exist on the server. I will switch it to creating a wholly new itemstack. This ~will be fixed~ has been fixed with v3.1.0 and be out quite soon - all I've got left for v3.1.0 is some testing.

Cheers, appreciate your hard work to get this fixed. We are still thoroughly enjoying your mod and look forward to the updates.
