### ISSUE TITLE
[1.15.2]Console error

### ISSUE THREAD

**Issue by EnterFor** [ejektaflex/Bountiful#73]
## Bug Report

**Observed Behaviour**

What happened:Console error

Console log: https://paste.ubuntu.com/p/NFgjKmYXhX/

**Expected Behaviour**

I don't know if that's normal

**Minimal setup needed to reproduce**

- Forge version: 31.1.35
- Bountiful version: 3.1.0
- Other mods:1.15.2

**Comment by ejektaflex** [comment]
Yep, I know about this. I already have it [written down here](https://github.com/ejektaflex/Bountiful/projects/5). It shouldn't affect anything in Bountiful v3.1.0, and as you can see it's on my list of things to work on for the next version 👍

**Comment by ejektaflex** [comment]
I'm going to close this just because it doesn't affect gameplay in v3.1, so while it is a bug it really isn't an *issue*. It's getting fixed for v3.2.0 regardless!
