### ISSUE TITLE
Issue in conjunction with Potion Core

### ISSUE THREAD

**Issue by Tylundja** [ejektaflex/Bountiful#78]
## Bug Report

**Observed Behaviour**

What happened: when i kill any kind of mob (enemy, neutral, etc) a problem happens. i have also noticed that kill bounties dont record kill counts. i also specifically have a bounty im working on with me.

Crash log: https://paste.dimdev.org/jodilavuxi.mccrash

**Expected Behaviour**

What should have happened: kills would be counted towards applicable bounties.

**Minimal setup needed to reproduce**

- Forge version: unsure.
- Bountiful version: 2.2.1
- Other mods: Potion Core
im playing in a modpack called Roguelike Adventures and Dungeons.
i will be forwarding this to the Potion Core author as well.

**Steps to reproduce**

How to recreate this: kill literally anything

**Comment by ejektaflex** [comment]
If you could check for me: it seems like there's a bounty in your inventory that has no objectives or rewards attached to it. Is this true?

**Comment by Tylundja** [comment]
yes. i had a few empty bounty pages.

**Comment by ejektaflex** [comment]
Okay, that's helpful. Is this part of a modpack? I'm getting an influx of issues at once, so I'm inclined to believe that it is. Which one is it? Did these empty bounties spawn on a bounty board, or how did you get them? Commands?

It seems to be crashing because when you kill a mob, it tries to update all of the bounties in your inventory and one of them has no NBT data (aka is a blank bounty)

**Comment by Tylundja** [comment]
Yes. the modpack is Roguelike Adventures and Dungeons. i think the empty bounties were a reward for completing other bounties.

**Comment by ejektaflex** [comment]
I'm also not seeing what connection to Potion Core there is. Does the mod work fine without Potion Core? 

It could be that one of the custom bounties that the mod author made is from Potion Core. I'll have to check it out.

**Comment by Tylundja** [comment]
yeah im not sure what the connection to Potion Core is either. i noticed when i dropped all bounty pages, i stopped getting the error. i didnt test whether or not it was due to the empty pages. i just got rid of all of them and it was fine.

**Comment by ejektaflex** [comment]
Thanks for the speedy replies. For now, store them in a chest and try work on some other bounties, and see if that "fixes" it. Bountiful isn't liking the fact that those invalid bounties have no data, and so I'm going to try talk to the modpack author and see what he's trying to do (in case there's an error on their end). I'll also look into changing the obvious - I'll have it skip updating mob kills on bounties with no data.

Thank you!

**Comment by Tylundja** [comment]
absolutely. thank you for looking into this!

**Comment by ejektaflex** [comment]
This is fixed as of a44a57e. The update [can be found here](https://www.curseforge.com/minecraft/mc-mods/bountiful/files/2949667). Feel free to reopen this issue if anything else comes up!
