### ISSUE TITLE
Crash when getting bounty box in creative

### ISSUE THREAD

**Issue by VoiidInVaiin** [ejektaflex/Bountiful#79]
## Bug Report

**Observed Behaviour**

What happened: Tried to get the bounty box in creative, Once I clicked on the item to drag it.. the game crashed.

Crash log: https://pastebin.com/kmL4ihXV

**Expected Behaviour**

What should have happened: Should of being able to drag the item to my hotbar.

**Minimal setup needed to reproduce**

- Forge version: Forge-31.1.45
- Bountiful version: Bountiful-1.15.2-3.1.0
- Other mods: In Crash Log..

**Steps to reproduce**

How to recreate this: Try and grab the item in creative mode?

**Comment by ejektaflex** [comment]
This one is peculiar, but it sounds like I made an assumption about the data Minecraft sending me and the assumption was wrong. I'll look into it!

**Comment by VoiidInVaiin** [comment]
Newer version of forge, same crash: https://pastebin.com/KWQCdqnf

**Comment by ejektaflex** [comment]
I've figured it out. It looks like Project MMO is calling a client event and passing `null` into the world for `getBlockHardness` when transforming tooltips, and I naively assume that it's never null. I suppose I'm too trusting of other modders when programming :^)

A fix is coming real soon.

**Comment by ejektaflex** [comment]
Fixed as of 1525424. The new version exists for 1.14 and 1.15 [on CurseForge](https://www.curseforge.com/minecraft/mc-mods/bountiful/files). Thank you!
