### ISSUE TITLE
[Suggestion] Different item icons for bounties depending on tier/enchantment shine

### ISSUE THREAD

**Issue by abboip** [ejektaflex/Bountiful#8]
At a glance, all bounties look the same until you mouse over them to view the details in the tool tip. An easy way to make the higher tiers more distinct would be to have different icons/textures for the different tiers, or adding an enchantment "shine" to them so the player is immediately drawn to them.

**Comment by ejektaflex** [comment]
This is finished, and so in v2.2+ each rarity will have a different icon.
