### ISSUE TITLE
Unable to complete missions [1.15]

### ISSUE THREAD

**Issue by MazeusXenon** [ejektaflex/Bountiful#82]
## Bug Report

**Observed Behaviour**

What happened:
-- Everything appears to work other than claiming the reward

-- Held it in hand, tried empty hand, everything and right clicked in space and against the bounty board with no success

-- We are running 1.15; I do remember we got a server crash when confirming a reward involving wool if the wool was a collection of colors and the mission was not specific

-- No log files; it just doesn't work (easily the biggest annoyance; with a log file, we would have an error to track down!)

Crash log: 
No log; just doesn't work

**Expected Behaviour**

What should have happened:
As per instruction, should be able to right-click on Bounty Board and get reward

**Minimal setup needed to reproduce**

- Forge version: 31.1.77
- Bountiful version: 3.1.1
- Other mods: many (110+) -- did you want them all?

**Steps to reproduce**

How to recreate this:
-- "build" bounty board (not use one in a town)
-- Get bounty (my test was to get 4 gold ingots to get a brewing station)
-- Complete bounty (grabbed gold bar, made nuggets, put into inventory)
-- Right click with bounty in hand on board (Just opens the board)
-- Right click with empty hand on board (just opens the board)
-- Right click in space with bounty - tells me to right-click bounty board
(repeat last three with sneak-right click; same results)

Happy hunting and stay well!

**Comment by apotatomachine** [comment]
+1

This issue happens on a dedicated server. Running the same modpack in singleplayer/lan server works fine.
Console output when right-clicking with a fullfilled bounty on the bounty board:

```
18.05 21:56:52 [Server] Server thread/FATAL [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
18.05 21:56:52 [Server] Server thread/ERROR [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
18.05 21:56:52 [Server] INFO Index: 5
18.05 21:56:52 [Server] INFO Listeners:
18.05 21:56:52 [Server] INFO 0: HIGHEST
18.05 21:56:52 [Server] INFO 1: ASM: net.quetzi.morpheus.helpers.MorpheusEventHandler@55451969 bedClicked(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
18.05 21:56:52 [Server] INFO 2: NORMAL
18.05 21:56:52 [Server] INFO 3: ASM: com.branders.spawnermod.event.SpawnerEventHandler@3e19137b onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
18.05 21:56:52 [Server] INFO 4: ASM: class cjminecraft.doubleslabs.Events onItemUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
18.05 21:56:52 [Server] INFO 5: ASM: com.natamus.naturallychargedcreepers.events.EntityEvent@5f4fc7a3 onClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
18.05 21:56:52 [Server] INFO 6: ASM: com.sk89q.worldedit.forge.ForgeWorldEdit@13364103 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
18.05 21:56:52 [Server] INFO java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
18.05 21:56:52 [Server] INFO at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClass(RuntimeDistCleaner.java:71)
18.05 21:56:52 [Server] INFO at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClass(ILaunchPluginService.java:103)
18.05 21:56:52 [Server] INFO at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
18.05 21:56:52 [Server] INFO at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115)
18.05 21:56:52 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:239)
18.05 21:56:52 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:126)
18.05 21:56:52 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96)
18.05 21:56:52 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
18.05 21:56:52 [Server] INFO at ejektaflex.bountiful.item.ItemBounty.func_200295_i(ItemBounty.kt:65)
18.05 21:56:52 [Server] INFO at net.minecraft.item.ItemStack.func_200301_q(ItemStack.java:509)
18.05 21:56:52 [Server] INFO at com.natamus.naturallychargedcreepers.events.EntityEvent.onClick(EntityEvent.java:35)
18.05 21:56:52 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler_110_EntityEvent_onClick_RightClickBlock.invoke(.dynamic)
18.05 21:56:52 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
18.05 21:56:52 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
18.05 21:56:52 [Server] INFO at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:785)
18.05 21:56:52 [Server] INFO at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:315)
18.05 21:56:52 [Server] INFO at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:853)
18.05 21:56:52 [Server] INFO at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36)
18.05 21:56:54 [Multicraft] Skipped 128 lines due to rate limit (30/s)
```

**Comment by ejektaflex** [comment]
Ah, that looks useful!
```
18.05 21:56:52 [Server] Server thread/FATAL [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
18.05 21:56:52 [Server] Server thread/ERROR [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
...
18.05 21:56:52 [Server] INFO at ejektaflex.bountiful.item.ItemBounty.func_200295_i(ItemBounty.kt:65)
18.05 21:56:52 [Server] INFO at net.minecraft.item.ItemStack.func_200301_q(ItemStack.java:509)
```

There are a worrying amount of things using ASM to modify the right click event there, so lets hope it's not another mod causing this to happen. Luckily, it looks like I accidentally called some client code from the server side. I'll look into it when I have some time in the next couple of days, thank you @apotatomachine !

**Comment by Tander** [comment]
My players are also complaining about inability to complete quests, so it may be connected with issue #89

**Comment by Tander** [comment]
@MazeusXenon Do you use ThutEssentials or another mod for land protection? I found out that outside land claims quest can be completed successfully (but there is still errors in console)

**Comment by ejektaflex** [comment]
@Tander A crash log from them would be useful. I still haven't verified whether it's my mod or another that's caused this to happen.

**Comment by ejektaflex** [comment]
It looks like something to do with Naturally Charged Creepers. Their mod is closed source and uses ASM so I imagine there's some sort of problem there, I'm looking into it.

**Comment by ejektaflex** [comment]
Yes, I just figured out the mapping. Naturally Charged Creepers, in their `EntityEvent::onClick` method, checks something that has to do with the display name (`func_200301_q` -> `getDisplayName`) .

~~This obviously crashes on a dedicated server~~ I lied, my memory is fuzzy after using Fabric for so long. 

For now, removing Naturally Charged Creepers from your game will fix this issue.

**Comment by ejektaflex** [comment]
I lied - this is a problem of Bountiful's. There is some client logic being run on the server - my bad. However, they still shouldn't be checking spawn egg display names for validation of anything, it's rather strange. I'll roll out a fix soon.

**Comment by ejektaflex** [comment]
Fixed as of 21f62e1 for release 3.1.2

**Comment by ricksouth** [comment]
I agree checking for display names is not the best idea. But my younger less experienced self took those risks back in the day ;) Glad you've found the issue.

**Comment by ejektaflex** [comment]
@ricksouth That's totally okay, it worked flawlessly until now! We all start somewhere :^)
