### ISSUE TITLE
Bounty Board Consuming Items

### ISSUE THREAD

**Issue by kornfan6589** [ejektaflex/Bountiful#84]
## Bug Report

**Observed Behaviour**

What happened:  The bounty Board is kind of glitched. When you go over to right click it, if you are holding a consumable item, it will consume that item and bring up the bounty menu instead of just opening the menu. 

Crash log: no crash

**Expected Behaviour**

What should have happened: Board menu should open without consuming item

**Minimal setup needed to reproduce**

- Forge version: 31.1.46
- Bountiful version: 5.3.11
- Other mods: https://www.curseforge.com/minecraft/modpacks/tengen-toppa/files/2944016

**Steps to reproduce**

How to recreate this: Hold a consumable, click bounty board

**Comment by ejektaflex** [comment]
You mean that if it's edible, you have to eat it before opening up the board?

**Comment by kornfan6589** [comment]
Sorry no, bad description. Items like Ender Pearls, Torches, backpacks, anything that has a use function when right clicking takes priority over the bounty board. Food attempts to start eating but then opens the board.

So specifically and ender pearl in your hand causes you to throw the pearl and opens the board at the same time, so you teleport.

A torch in your hand, or even in your off hand, causes you to place the torch and the board opens at the same times. so my servers bounty boards are now covered in torches.

If you have a backpack (from a mod) in your hand you open the backpack instead of the bounty board.

**Comment by ejektaflex** [comment]
Yeah, I think that I'm not cancelling their click events when you right click on a bounty board :^)

I know the fix for this, and I'll release one soon. I'm waiting a little bit on another bug (#82) to see if I can resolve both of these at the same time 👍

**Comment by kornfan6589** [comment]
awesome, thank you!

**Comment by ejektaflex** [comment]
Fixed as of 21f62e1 for 3.1.2 release
