### ISSUE TITLE
Bountiful Bounty Board doesn't accept ingots from the same forge:ingots tag

### ISSUE THREAD

**Issue by NielsPilgaard** [ejektaflex/Bountiful#85]
## Bug Report

**Observed Behaviour**

What happened: A common Bounty asked for `Tin Ingot` - 
I supplied Tin Ingots from Silent's Mechanism, which did not work. 
I then tried with Tin Ingots from Mystical World which did work.

**Expected Behaviour**

What should have happened: Both ingots should have been accepted, as they are both part of the same tag.

**Minimal setup needed to reproduce**

- Forge version: 1.14.4-28.2.16
- Bountiful version: Bountiful-1.14.4-3.1.1

Any 2 mods that add the same Ingot type should do the trick, but I know these would reproduce the behaviour:
- mysticalworld-1.14.4-1.9.3
- mysticallib-1.14.4-1.16.1
- SilentMechanisms-1.14.4-0.6.13+49
- SilentLib-1.14.4-4.4.0+44

**Steps to reproduce**

How to recreate this: Follow the `What happened` description - I got the Bounty I was looking for by placing 31 of them and waiting.

**Comment by ejektaflex** [comment]
Ah - Yeah, currently it only accepts Tin ingots from Mystical World. I'll have to change that data value to check for a Tin ingot tag.

**Comment by ejektaflex** [comment]
Fixed in f0f4c0a for 3.1.2 release
