### ISSUE TITLE
Air on Chef's Supplies Bounty

### ISSUE THREAD

**Issue by NielsPilgaard** [ejektaflex/Bountiful#86]
## Bug Report

**Observed Behaviour**

What happened: Several Chef's Supplies bounties require Air:
https://prnt.sc/shjaje

**Expected Behaviour**

What should have happened: A different requirement than air, as it is unobtainable.

**Minimal setup needed to reproduce**

- Forge version: 1.14.4-28.2.16
- Bountiful version: Bountiful-1.14.4-3.1.1
- Other mods: Enigmatica 4 modpack

**Steps to reproduce**

How to recreate this: Get a hold of a Bounty Board with Chef's Supplies Decree, and wait for one of the air bounties shows up.

**Comment by ejektaflex** [comment]
Interesting. If you could give me a log, that would be great. Even though there should be no crashes, I think it should mention in the log if the bounty is invalid.

Also, putting a bounty in hand and typing `/bo hand` will copy a JSONified version of the bounty to your clipboard. You can paste the result here and I can take a look at it 👍 

In other news: My mod has been included in Enigmatica 4, neat!

**Comment by DoctorShtroumphi** [comment]
I'm also having the same issue! Here's the JSON as requested:

{
  "type": "item",
  "content": "bountiful:bounty",
  "nbt": {
    "boardStamp": "2707203L",
    "bountyStamp": "2712883L",
    "objectives": {
      "0": {
        "amount": 46,
        "type": "item",
        "unitWorth": 100,
        "content": "vanillafoodpantry:natron_crystals"
      },
      "1": {
        "amount": 14,
        "type": "item",
        "unitWorth": 225,
        "content": "minecraft:melon"
      }
    },
    "bountyTime": "114390L",
    "rewards": {
      "0": {
        "amount": 21,
        "type": "item",
        "unitWorth": 300,
        "content": "minecraft:carrot"
      },
      "1": {
        "amount": 1,
        "type": "item",
        "unitWorth": 1500,
        "content": "aquaculture:redstone_hook"
      },
      "2": {
        "amount": 1,
        "type": "item",
        "unitWorth": 1500,
        "content": "bountiful:decree"
      }
    },
    "rarity": 3
  },
  "amountRange": {
    "min": 1,
    "max": 1
  },
  "unitWorth": 1000,
  "weight": 1000
}

**Comment by DoctorShtroumphi** [comment]
Just looking at the JSON, it seems I need "vanillafoodpantry:natron_crystals". Is this a dependency that I missed?

**Comment by ejektaflex** [comment]
That seems to be it - I added a few VanillaFoodPantry entries into the Simple Farming folder on accident, and your pack doesn't have VFP. This should be a quick fix.

**Comment by ejektaflex** [comment]
Fixed in f0f4c0a for 3.1.2 release
