### ISSUE TITLE
How to add more Exp on reward

### ISSUE THREAD

**Issue by fr4nc090** [ejektaflex/Bountiful#87]
when you read, i dont know how to add rewards and Exp need some help

**Comment by ejektaflex** [comment]
In 1.12, you just modify the config at `config/bountiful/bountiful.cfg`. In 1.14/1.15, there are no modifiable experience bonus when completing a reward. To add new rewards, refer to the wiki [right here](https://github.com/ejektaflex/Bountiful/wiki).

**Comment by fr4nc090** [comment]
dont work haha no worries i use this experience_bottle Ty
