### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Levion1** [ejektaflex/Bountiful#88]
To put it quite simply, the game crashes when I've got only Bountiful and Forgelin in. I am currently using the latest version of Forge for 1.12.2 as well as the latest versions of both mods present.
[crash-2020-05-26_21.10.32-client.txt](https://github.com/ejektaflex/Bountiful/files/4686276/crash-2020-05-26_21.10.32-client.txt)

**Comment by ejektaflex** [comment]
The crash log explains it pretty well:
```
Caused by: java.lang.Exception: 'bountiful/rewards.json' contains one or more invalid rewards. Invalid rewards: 
[
PickedEntry (Stack) [Item: dungeontactics:bag_food, Amount: 300, NBT: null, Weight: 100, Stages: null], 
PickedEntry (Stack) [Item: dungeontactics:bag_potion, Amount: 300, NBT: null, Weight: 100, Stages: null], 
PickedEntry (Stack) [Item: dungeontactics:bag_ore, Amount: 800, NBT: null, Weight: 100, Stages: null], 
PickedEntry (Stack) [Item: dungeontactics:bag_tool, Amount: 800, NBT: null, Weight: 100, Stages: null], 
PickedEntry (Stack) [Item: chancecubes:chance_cube, Amount: 1000, NBT: null, Weight: 100, Stages: null]]
```
Sounds like you downloaded a modpack, then removed Dungeon Tactics and Chance Cubes. The modpack author has configured items from those mods as rewards for bounties. You've got to remove them from `config/bountiful/rewards.json` or the game will crash :+1:

**Comment by Levion1** [comment]
Funny thing is I didn't download a modpack, I got the mod straight out of curse forge, But thanks!

**Comment by ejektaflex** [comment]
Well, you used a bad configuration file from somewhere else, somehow, which was probably from a modpack containing both of those mods. This mod adds none of those things. [This is the list](https://github.com/ejektaflex/Bountiful/blob/1.12/src/main/kotlin/ejektaflex/bountiful/data/DefaultData.kt) of default bounty data in 1.12, and those items are obviously not things that I would add :^)
