### ISSUE TITLE
Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by Tander** [ejektaflex/Bountiful#89]
## Bug Report

**Observed Behaviour**

What happened:
Repetitive exceptions in server console after one of players got [Work for Hire] advancement:
Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER (more in log below)
Looks like your mod calls some client logic on dedicated server.

Console log: 
https://pastebin.com/BYLbBzfJ

**Minimal setup needed to reproduce**

- Forge version: forge-31.2.0
- Bountiful version: Bountiful-1.15.2-3.1.1
- Other mods: Thut's Essentials

**Comment by ejektaflex** [comment]
Fixed in f0f4c0a for 3.1.2 release
