### ISSUE TITLE
Datapack that adds Lycanite's Mobs as Objective labelled as Pig Kills ingame

### ISSUE THREAD

**Issue by DeSyred** [ejektaflex/Bountiful#90]
## Bug Report

**Observed Behaviour**

What happened: 
I made a Datapack that adds Lycanite's Mobs as an Objective Bounty for Mob Hunting. Everything works fine but the Bounty says Pig Kills instead of the actual Mob. The NBT Tag shows the correct information. Killing the Mob said in the NBT Tag registers a kill from its respective Pig Kill. Bug seems to only be a visual bug and only on Lycanite's Mobs

![2020-06-01_21 39 10](https://user-images.githubusercontent.com/5743971/83473929-5cd4a480-a450-11ea-97d5-52014c67846d.png)

![2020-06-01_21 28 13](https://user-images.githubusercontent.com/5743971/83474012-94dbe780-a450-11ea-8653-25f301fb686a.png)

Crash log: None.

**Expected Behaviour**

What should have happened: 
Instead of saying Pig Kills it should "Wraamon Kills" like the "Spider Kills."

**Minimal setup needed to reproduce**

- Forge version: 1.15.2 - 31.2.0
- Bountiful version:  1.15.2 - 3.1.1
- Other mods: Lycanite's Mobs 1.15.2 - 2.2.3.2

**Steps to reproduce**

How to recreate this:
1. Load a Datapack that adds any Lycanite's Mobs into the Objectives.
2. Check the Bounty the NBT that says Pig Kills.

**Comment by ejektaflex** [comment]
Which data pack is this? I don't see any references to pigs in my code or theirs, so I'd like to take a look at the data pack, haha.

**Comment by DeSyred** [comment]
Sorry, I should've included the Datapack. Here's the Datapack I'm using. Also I think the reason why it says Pigs is cause it defaults to that when it can't display the name. Works fine on Modded Items though. 

[Bountiful.zip](https://github.com/ejektaflex/Bountiful/files/4719588/Bountiful.zip)

**Comment by ejektaflex** [comment]
Haha, this is quite the bug. It sounds like Minecraft itself may be defaulting to using the Pig name if the normal name is invalid - I've got to look into it some more, but there shouldn't be a reason for it to be invalid. Considering it happens only with Lycanite's as well, they might be doing entity registration wrong, I'll have to check.

**Comment by ejektaflex** [comment]
I won't be coming back to the 1.16.x version, but if this crops up in 1.19.4+ and Lycanites ever gets an update to that, let me know!
