### ISSUE TITLE
Config in 1.15.2

### ISSUE THREAD

**Issue by seiinaru** [ejektaflex/Bountiful#91]
I dont know if im just stupid, blind or both but in a yt video the guy said you can modify the bounties in the config. Im playing on my own small server but there is no bountiful config. Thx for awnser in advance.

**Comment by ejektaflex** [comment]
Is this Mischief of Mice's video? If so, that's for 1.12, and in that version the config file is at `config/bountiful/bountiful.cfg`. In 1.14/1.15, all settings are serverside, so they exist in the server config location, which is at `[your game world]/serverconfig/bountiful-server.toml`.
