### ISSUE TITLE
Halp consistent crashing.

### ISSUE THREAD

**Issue by AzazelMango** [ejektaflex/Bountiful#93]
java.lang.Exception: JSON Structure of 'bounties.json' is incorrect! Reverting to previous data. Details: com.google.gson.stream.MalformedJsonException: Expected value at line 331 column 5 path $[36].amount.max

Does this mean I have too many entries? Ive gone over the syntaxes and whatnot throughout the file a few times already. Idk what to do at this point. Please and thanks for any halp. 
Version 1.12.2

**Comment by AzazelMango** [comment]
Found the problem XD

**Comment by ejektaflex** [comment]
Glad you figured it out 👍
