### ISSUE TITLE
How to create a mission and bounty?

### ISSUE THREAD

**Issue by zeven001** [ejektaflex/Bountiful#94]
I create a server but i cant understand wiki how to create a bounty and reward?

Im use a Economy inc mod so i needed a mission to give a dollars by reward

**Comment by ejektaflex** [comment]
You haven't specified what you don't understand or the version of Minecraft or Bountiful that you're using, but my general advice is to try making a regular Minecraft datapack and understand how that works. Change something simple, like perhaps a recipe. Then realize that in the same way that you made that datapack, you can make one for Bountiful by doing the same thing with data from Bountiful.
